### ISSUE TITLE
Permission type names on application page are not translatable

### ISSUE THREAD

**Issue by AsciiWolf** [tchx84/Flatseal#103]
The "Shared", "Sockets", Devices" and other permission type names that are displayed on details page for an application in Flatseal do not seem to be translatable.

See this attached screenshot:
![flatseal_details](https://user-images.githubusercontent.com/2339930/87856931-d5b98e00-c922-11ea-9144-99c6cefa036c.png)

**Comment by tchx84** [comment]
The idea was that, it would match the CLI command e.g. just like `--socket=` command which is not translated, so that it would be easier to find things in the UI coming from `flatpak-override`.

But is just my theory ;)

**Comment by AsciiWolf** [comment]
Ah, makes sense. Thanks! :-)
