### ISSUE TITLE
support background permission

### ISSUE THREAD

**Issue by hferreiro** [tchx84/Flatseal#105]
Support adding/removing background permission

**Comment by tchx84** [comment]
Hey @hferreiro, thanks for reaching out.

I believe this uses a different backend / mechanism from what Flatseal can currently handle, but sounds interesting, and ill take a look and see how feasible would be.

**Comment by tchx84** [comment]
I need to study this API a bit more to understand how to better integrate dynamic permissions into Flatseal. https://docs.flatpak.org/en/latest/portal-api-reference.html?highlight=permission#gdbus-org.freedesktop.impl.portal.PermissionStore

**Comment by Arxcis** [comment]
You probably know this already, but for the sake of discussion, you can already toggle:
- "Run in background"
- "Notifications"

in Gnome settings on PopOS20.04.
<img src="https://user-images.githubusercontent.com/3092618/94367649-5bef0f00-00e0-11eb-9106-388e4585e109.png" width=400>
Having said that, I forget that these permissions even exists when they are not available in Flatseal, so I would like to have them there as well :sweat_smile:

The "Built-in permissions" mentioned in the settings here, are not editable in Gnome settings, but are permissions we can edit in Flatseal today.

An interesting observation here is that Gnome-settings differentiate quite clearly between static (non-editable/bundled/built-in) and dynamic (editable) - permissions. Quite different from Flatseals everything is editable/dynamic model.

**Comment by Arxcis** [comment]
On a side-note: The Location permissions is in a different section of the Gnome-settings 
<img src="https://user-images.githubusercontent.com/3092618/94368225-4c24fa00-00e3-11eb-89db-9daeb36c997e.png" width=400>
So today I have 3 different places I have to go, if I want an overview of all the permissions of an app: Flatseal + Gnome-settings/Applications + Gnome-settings/Privacy/Location Services. Would be cool to have them co-located.

**Comment by tchx84** [comment]
Hey @Arxcis ,

Just to clarify. Flatpak supports two types of permissions, static and dynamic. Both can be changed. Static through overrides, and dynamic through portals. The challenge here (for Flatseal, I mean) is that these two use completely different backends, and we would need to think how:

1. Support Dynamic permissions. It's basically dbus, but not completely sure all of these were meant to be modified in the same way Flatseal does it today.
2. Design the right experience. Should we blend these two conceptually different type of permissions as if it was just one? Should we, somehow, present and manage these separately? Plus the technical implications of each decision.

**Comment by Arxcis** [comment]
Excellent summary/clarification @tchx84 :+1: I agree with your concerns 100%. Some thinking is definitely required :smiley:

**Comment by tchx84** [comment]
> Support adding/removing background permission

I just started investigating this, and look promising. See the PR.
