### ISSUE TITLE
flatseal does not detect moved flatpaks

### ISSUE THREAD

**Issue by XN17** [tchx84/Flatseal#120]
system : Debian Buster

When flatpaks are moved to a new location they are detected by flatpak but not by flatseal(not even the flatpaks I installed afterwards)

**Comment by tchx84** [comment]
hey @XN17 ,

Please take a look a https://github.com/tchx84/Flatseal/blob/master/TIPSANDTRICKS.md#enable-custom-installations

Just follow the steps to enable custom installations.
