### ISSUE TITLE
Search permissions

### ISSUE THREAD

**Issue by tchx84** [tchx84/Flatseal#125]
Taken from a  comment in Flatseal gnome-software page

> Only thing missing is a permission search feature

Flatseal currently supports 30 different permissions. Maybe something like [this](https://twitter.com/alexm_gnome/status/1288503112496484355/photo/2) could be of help.

@bertob by any chance, do you know of other examples were search is implemented among settings / options? So I can based this on.

**Comment by bertob** [comment]
Libhandy's HdyPreferencesWindow search is probably a good example to look at

**Comment by tchx84** [comment]
@YaLTeR please feel free to describe your design there :)

**Comment by YaLTeR** [comment]
So my issue is that:
- when opening Flatseal I want to type to search for the app
- when the app is open it would be nice to type to search for permissions

I initially proposed focusing the app search entry by default on launch, however on mobile this brings up the OSK which is awkward.

Therefore my idea is to add an initial empty state with no app selected (currently on launch the first app is selected). When typing on the empty state it will type to search for the app, and when typing on an app permissions page it will type to search for the permissions.

**Comment by tchx84** [comment]
> Therefore my idea is to add an initial empty state with no app selected (currently on launch the first app is selected). When typing on the empty state it will type to search for the app, and when typing on an app permissions page it will type to search for the permissions.

The difficulty I see is that both, the app list and permissions list, "exist" in the exact same place. I am no designer, but wouldn't this feel a bit weird? I mean, to have the exact same action (typing) behaving differently in the exact the same place (the same view/window)?

**Comment by bertob** [comment]
I'd take a step back here and figure out what use cases wer're trying to address here first. Is it about searching for a specific permission within the page of an app? Or searching for the value of the same permission across all apps? Something else?

**Comment by tchx84** [comment]
> I'd take a step back here and figure out what use cases wer're trying to address here first. Is it about searching for a specific permission within the page of an app? Or searching for the value of the same permission across all apps? Something else?

good point, I am assuming the first case (within the page of the currently selected app).

**Comment by bertob** [comment]
In that case a second search button/bar in the content pane would be the most obvious solution, no?

**Comment by tchx84** [comment]
> In that case a second search button/bar in the content pane would be the most obvious solution, no?

This would work for mobile fine but, honest question, for the desktop, wouldn't be confusing to have two search buttons on the same header bar ?

I am quite pragmatic, so if you think that doesn't break some sacred design vow, I wouldn't mind* hah

**Comment by bertob** [comment]
Maybe we could use a different icon (e.g. a funnel for "filter") for the in-panel one?

**Comment by tchx84** [comment]
> Maybe we could use a different icon (e.g. a funnel for "filter") for the in-panel one?

sure, let's try it.

**Comment by Arxcis** [comment]
@tchx84 Did you consider reusing this search-bar design from gnome-settings? 

*Gnome-settings on Pop!OS 20.10*
![didyouconsider](https://user-images.githubusercontent.com/3092618/117176719-79036300-add0-11eb-874b-96a905cb7c68.gif)

Obviously, the root-level would be "Applications" instead of "Settings", and when clicking on an app, you would get search within the selected application.

*From Flatseal. Very similar design already.*
![image](https://user-images.githubusercontent.com/3092618/117177327-31c9a200-add1-11eb-8d1d-bc5ac17bcd08.png)

I think this issue is very related to #166 , and there is a potential to solve 2 issues at the same time here.

**Comment by tchx84** [comment]
It's unlikely that I be working on this anytime soon, if someone feels like designing this, please re-open.

**Comment by hyuri** [comment]
Here's a quick design. One for searching apps that have a particular permission ("network", in this example), and one for searching a permission ("pulseaudio", in this example) within a selected app (Blender, in this example).

![Flatseal Search Permissions Design](https://user-images.githubusercontent.com/18584014/235808909-d58a3d90-a133-43a4-bc30-099f588669f1.png)
(pixelated for security)

Clicking the "filter" icon + "Permission" text, in the apps search, gives you the other filtering options.

Default is "App Name".

The two search bars are independent and unrelated, basically.

Note: The search results are not shown in the picture, as you can see. This was just a quick mock up. But I'm sure you know what's supposed to show up as results of both search queries:
1. In the "Applications" search (on the left), having the filter set as "Permission" and searching for a given permission — such as "network", in the pictured example — results in a list of all the apps that have that permission activated;
2. In the "Application Permission" search (on the right), searching for a given permission causes the selected app page to only display the section(s) containing the query.

**Comment by DominiqueSite** [comment]
It would be really useful to be able to filter all apps for specific permissions (e.g. network access)! Any chance that this (slightly different from searching inside an app page) feature might be implemented now that there's a design suggestion @tchx84?
