### ISSUE TITLE
Better documentation page

### ISSUE THREAD

**Issue by tchx84** [tchx84/Flatseal#126]
Currently using [1], I wonder if there's a better page to replace that one.

[1] https://docs.flatpak.org/page/sandbox-permissions-reference.html

**Comment by TheEvilSkeleton** [comment]
Just curious, what is wrong with that one? It's very well written

**Comment by tchx84** [comment]
hey @TheEvilSkeleton 

Nothing wrong with it, but only explains basic permissions and doesn't really cover other overrides that Flatseal currently support.

I am interested in your feedback though, think is better this way ?

**Comment by TheEvilSkeleton** [comment]
> Nothing wrong with it, but only explains basic permissions and doesn't really cover other overrides that Flatseal currently support.

Understandable. I guess we could contribute to [flatpak/flatpak-docs](https://github.com/flatpak/flatpak-docs)?

I'm *very* new to Flatpak's sandbox permissions, so I may not be really useful here

**Comment by tchx84** [comment]
The closest things I found so far was flatpak-override [manpage](https://manpages.debian.org/testing/flatpak/flatpak-override.1.en.html).

Since Flatseal uses overrides as its back-end, the man page for flatpak-override provide the closest documentation, is just a bit too technical and CLI focused.

EDIT: here's the official doc version of that manpage https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-override

**Comment by TheEvilSkeleton** [comment]
> The closest things I found so far was flatpak-override [manpage](https://manpages.debian.org/testing/flatpak/flatpak-override.1.en.html).

That's really cool. You could create https://github.com/tchx84/Flatseal/wiki and base the wiki on the manpage. That way the user will know exactly what is what

**Comment by tchx84** [comment]
> > The closest things I found so far was flatpak-override [manpage](https://manpages.debian.org/testing/flatpak/flatpak-override.1.en.html).
> 
> That's really cool. You could create https://github.com/tchx84/Flatseal/wiki and base the wiki on the manpage. That way the user will know exactly what is what

That's a great idea, can you help with that ? :)

**Comment by TheEvilSkeleton** [comment]
Sure. I'm pretty sure that GitHub lets you create the wiki for free. If you give me access to write in the wiki then I could get started

**Comment by TheEvilSkeleton** [comment]
This is just a draft. Correct me if I'm wrong:

---

# Flatseal permissions

This documentation indicates the permissions of Flatpak with better integration with Flatseal. It is based on the official [Sandbox Permissions Reference](https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html).

Flatseal uses the `flatpak override` command. Every change the user does will make Flatseal run the `flatpak override` command to override the default permissions that the Flatpak program originally shipped with. All overridden permissions are located inside the `~/.local/share/flatpak/overrides` and `/var/lib/flatpak/overrides` directories. If you want to read more into `flatpak override`, you can look at the [`FLATPAK OVERRIDE(1)` manpage](https://manpages.debian.org/testing/flatpak/flatpak-override.1.en.html).

## Permissions

### Share

List of subsystems shared with the host system.

Name | Permission | Description
--- | --- | ---
Network | `--share=network` | (toggle) - Access the network.
[Inter-process communications](https://en.wikipedia.org/wiki/Inter-process_communication) | `--share=ipc` | (toggle) - Share IPC namespace with the host.

### Socket

List of well-known sockets available in the sandbox.

Name | Permission | Description
--- | --- | ---
X11 windowing system | `--socket=x11` | (toggle) - Show windows using X11.
Wayland windowing system | `--socket=wayland` | (toggle) - Show windows using Wayland.
Fallback to X11 windowing system | `--socket=fallback-x11` | (toggle) - Show windows using X11 if Wayland is not available. This overrides `--socket=x11`.

[...]

---

To be honest, Flatseal could be a great way to educate new Flatpak users.

**Comment by tchx84** [comment]
> This is just a draft. Correct me if I'm wrong:
> 
> # Flatseal permissions
> This documentation indicates the permissions of Flatpak with better integration with Flatseal. It is based on the official [Sandbox Permissions Reference](https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html).
> 
> Flatseal uses the `flatpak override` command. Every change the user does will make Flatseal run the `flatpak override` command to override the default permissions that the Flatpak program originally shipped with. All overridden permissions are located inside the `~/.local/share/flatpak/overrides` and `/var/lib/flatpak/overrides` directories. If you want to read more into `flatpak override`, you can look at the [`FLATPAK OVERRIDE(1)` manpage](https://manpages.debian.org/testing/flatpak/flatpak-override.1.en.html).
> 
> ## Permissions
> ### Share
> List of subsystems shared with the host system.
> 
> Name	Permission	Description
> Network	`--share=network`	(toggle) - Access the network.
> [Inter-process communications](https://en.wikipedia.org/wiki/Inter-process_communication)	`--share=ipc`	(toggle) - Share IPC namespace with the host.
> ### Socket
> List of well-known sockets available in the sandbox.
> 
> Name	Permission	Description
> X11 windowing system	`--socket=x11`	(toggle) - Show windows using X11.
> Wayland windowing system	`--socket=wayland`	(toggle) - Show windows using Wayland.
> Fallback to X11 windowing system	`--socket=fallback-x11`	(toggle) - Show windows using X11 if Wayland is not available. This overrides `--socket=x11`.
> [...]
> 
> To be honest, Flatseal could be a great way to educate new Flatpak users.

That's looking great, how about just a markdown document instead of the wiki? Not like we need many pages or anything, and would be nice to have it as part of the source. It could also absorb https://github.com/tchx84/Flatseal/blob/master/TIPSANDTRICKS.md   

So, maybe just send me a PR with the "DOCUMENTATION.md"?

**Comment by TheEvilSkeleton** [comment]
Sure, I'm working on it

**Comment by TheEvilSkeleton** [comment]
*Cringe incoming*

I forgot to fork. I cloned your repo and started editing it. Now I have to recommit everything again
