### ISSUE TITLE
Long startup time

### ISSUE THREAD

**Issue by haggen88** [tchx84/Flatseal#127]
I installed Flatpak 1.2.5 and Flatseal on antiX 19.2, distribution based on Debian Stable [Kernel 4.9.212 / iceWM 1.6.6-1 as windows manager / Fluxbox 1.3.7-1 as DE], but after reboot, running the command does not start the application.
It shows the following error [it is the only flatpak application that generates this error]:

seba@Seba-pc:~
$ flatpak run com.github.tchx84.Flatseal

(com.github.tchx84.Flatseal:3): Gjs-WARNING **: 00:05:50.613: JS ERROR: GLib.Error g-spawn-exit-error-quark: Error spawning command line “dbus-launch --autolaunch=044f1c256bc13998b94bcf1e5f37530f --binary-syntax --close-stderr”: Child process exited with code 1
get session@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:24
_has_software_manager@resource:///com/github/tchx84/Flatseal/js/widgets/detailsButton.js:71:1
_setup@resource:///com/github/tchx84/Flatseal/js/widgets/detailsButton.js:56:48
_init@resource:///com/github/tchx84/Flatseal/js/widgets/detailsButton.js:49:14
_setup@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:83:37
_init@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:69:14
vfunc_activate@resource:///com/github/tchx84/Flatseal/js/application.js:75:28
main@resource:///com/github/tchx84/Flatseal/js/main.js:32:24
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
@/app/bin/com.github.tchx84.Flatseal:9:17

**Comment by tchx84** [comment]
> I installed Flatpak 1.2.5 and Flatseal on antiX 19.2, distribution based on Debian Stable [Kernel 4.9.212 / iceWM 1.6.6-1 as windows manager / Fluxbox 1.3.7-1 as DE], but after reboot, running the command does not start the application.
> It shows the following error [it is the only flatpak application that generates this error]:
> 
> seba@Seba-pc:~
> $ flatpak run com.github.tchx84.Flatseal
> 
> (com.github.tchx84.Flatseal:3): Gjs-WARNING **: 00:05:50.613: JS ERROR: GLib.Error g-spawn-exit-error-quark: Error spawning command line “dbus-launch --autolaunch=044f1c256bc13998b94bcf1e5f37530f --binary-syntax --close-stderr”: Child process exited with code 1
> get session@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:24

Hmm, this doesn't seem to be related to Flatseal itself. The failure occurs in:

```javascript
        get session() {
            return Gio.bus_get_sync(Gio.BusType.SESSION, null);
        },
```

See https://gitlab.gnome.org/GNOME/gjs/-/blob/gnome-3-36/modules/core/overrides/Gio.js#L453

Can you install d-feet, launch it, and see if you can access the session bus ? You just need check if you can see something like:

![image](https://user-images.githubusercontent.com/481418/90324038-b9b40700-df37-11ea-8b79-5db5a00dc8f5.png)

You can install it from https://flathub.org/apps/details/org.gnome.dfeet

My first guess is that you could be missing some system dependency for Flatpak, but this test should tell us more.

> _has_software_manager@resource:///com/github/tchx84/Flatseal/js/widgets/detailsButton.js:71:1
> _setup@resource:///com/github/tchx84/Flatseal/js/widgets/detailsButton.js:56:48
> _init@resource:///com/github/tchx84/Flatseal/js/widgets/detailsButton.js:49:14
> _setup@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:83:37
> _init@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:69:14
> vfunc_activate@resource:///com/github/tchx84/Flatseal/js/application.js:75:28
> main@resource:///com/github/tchx84/Flatseal/js/main.js:32:24
> run@resource:///org/gnome/gjs/modules/script/package.js:222:19
> @/app/bin/com.github.tchx84.Flatseal:9:17

**Comment by haggen88** [comment]
I can't access the session bus [does not appear as an available option].
Btw running d-feet shows me an error:

>$ flatpak run org.gnome.dfeet
g-spawn-exit-error-quark: Error spawning command line “dbus-launch --autolaunch=437b3b4ac67c831567b25a445f388a79 --binary-syntax --close-stderr”: Child process exited with code 1 (1)
g-spawn-exit-error-quark: Error spawning command line “dbus-launch --autolaunch=437b3b4ac67c831567b25a445f388a79 --binary-syntax --close-stderr”: Child process exited with code 1 (1)
g-spawn-exit-error-quark: Error spawning command line “dbus-launch --autolaunch=437b3b4ac67c831567b25a445f388a79 --binary-syntax --close-stderr”: Child process exited with code 1 (1)
g-spawn-exit-error-quark: Error spawning command line “dbus-launch --autolaunch=437b3b4ac67c831567b25a445f388a79 --binary-syntax --close-stderr”: Child process exited with code 1 (1)

running another app gives me a similar error 
>flatpak run org.atheme.audacious
ERROR dbus-server.cc:928 [dbus_server_init]: D-Bus error: Error spawning command line “dbus-launch --autolaunch=437b3b4ac67c831567b25a445f388a79 --binary-syntax --close-stderr”: Child process exited with code 1
ERROR ../src/pulse/pulse_audio.cc:439 [create_context]: pa_context_connect() failed: Connection refused
WARNING plugin-init.cc:110 [start_plugin]: PulseAudio Output failed to start.
ALSA lib ../../pulse/pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused
ERROR ../src/alsa/config.cc:197 [get_elements]: snd_mixer_attach failed: Connection refused.
ERROR ../src/alsa/config.cc:238 [guess_element]: No suitable mixer element found.
ERROR ../src/mpris2/plugin.cc:310 [init]: Error spawning command line “dbus-launch --autolaunch=437b3b4ac67c831567b25a445f388a79 --binary-syntax --close-stderr”: Child process exited with code 1
WARNING plugin-init.cc:110 [start_plugin]: MPRIS 2 Server failed to start.

**Comment by tchx84** [comment]
Not exactly sure what dependency could be missing... but I am sure folks at https://github.com/flatpak/flatpak will. Please ask them for guidance.

Make sure to mention all the flatpak-related packages you current have installed.

**Comment by haggen88** [comment]
@tchx84 I installed XFCE and the errors disappeared. It must be something related to Fluxbox / IceWM  and Dbus.
Thanks in advance

P.S.

The only error message that comes out is:

>flatpak run com.github.tchx84.Flatseal
(com.github.tchx84.Flatseal:3): dbind-WARNING **: 01:07:07.765: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

And when activating D-bus session bus / D-bus system bus from Flatseal:

>flatpak run com.github.tchx84.Flatseal
(com.github.tchx84.Flatseal:3): dbind-WARNING **: 01:18:25.118: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.


But Flatseal opens although it takes a while, and D-feet now shows the Session Bus option.

**Comment by haggen88** [comment]
@tchx84  I decided that I am going to change the distribution. Do you need me to run any tests before I uninstall antiX?

**Comment by tchx84** [comment]
hey @haggen88 , 

Yes, please check if `org.freedesktop.DBus` is present in your session bus.

**Comment by haggen88** [comment]
![q](https://user-images.githubusercontent.com/68134588/90577809-4caba600-e1b1-11ea-814d-528e002542ee.png)

**Comment by tchx84** [comment]
And if you run Flatseal, with the exact same conditions as you show in that screenshot, does it take long to launch ? (plus the error messages you shown before?)

**Comment by haggen88** [comment]
It takes about 40-45 seconds to open Flatseal, even running D-feet has the same error and takes a similar time to display the application.

**Comment by tchx84** [comment]
> It takes about 40-45 seconds to open Flatseal, even running D-feet has the same error and takes a similar time to display the application.

I will keep these issues in mind (since I have ideas of how to mitigate that from Flatseal side) but, IMHO, this seems too specific to the environment rather than Flatseal itself, so I can't make it a priority for now.

Thanks for all the testing!

**Comment by haggen88** [comment]
I think the same, it must be something related to the desktop environment.
I have tested Flatseal on GNOME / Plasma / Cinnamon / LXQt / LXDE / Xfce / Budgie / MATE / Moksha / Pantheon / Deepin / Openbox / Trinity ...  but only on IceWM and Fluxbox have errors..
Regards

**Comment by haggen88** [comment]
@tchx84 I recently try Flatseal on Star, a Devuan/Debian based distro [without Systemd] with Fluxbox and JWM as DE...  and there were no problems. Apparently the problem is with AntiX and not with DEs.

Fluxbox:
![fluxbox star 2 1 -devuan debian based2](https://user-images.githubusercontent.com/68134588/92299393-d7193700-ef1f-11ea-848f-5ae475c7add4.png)

JWM:
![jwm star 2 1 - devuan debian based2](https://user-images.githubusercontent.com/68134588/92299408-eac49d80-ef1f-11ea-9f61-8fd9b8d10b4b.png)

**Comment by tchx84** [comment]
Interesting, not even the slow start ?

**Comment by haggen88** [comment]
No, start immediately.  Otherwise these are the Flatpak dependencies in antiX when Flatseal {among other apps} shows the error. No dependencies appear to be missing.

![x](https://user-images.githubusercontent.com/68134588/92316435-e486fd80-efc1-11ea-81a6-463950732f34.png)
