### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by lionirdeadman** [tchx84/Flatseal#128]
Tried clearing cache, deleting all the data, flatpak repair but no success.
It won't boot at all.
Log :
```

(com.github.tchx84.Flatseal:2): Gjs-WARNING **: 13:46:31.707: JS ERROR: GLib.Error as-app-error-quark: NoDisplay=true
getDesktopForAppData@resource:///com/github/tchx84/Flatseal/js/models/applications.js:186:13
getAll/<@resource:///com/github/tchx84/Flatseal/js/models/applications.js:266:34
getAll@resource:///com/github/tchx84/Flatseal/js/models/applications.js:264:21
_setup@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:80:49
_init@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:69:14
vfunc_activate@resource:///com/github/tchx84/Flatseal/js/application.js:75:28
main@resource:///com/github/tchx84/Flatseal/js/main.js:32:24
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
@/app/bin/com.github.tchx84.Flatseal:9:17

```

**Comment by tchx84** [comment]
hey @lionirdeadman 

Can you share more info about your system ? e.g.

* Linux distro
* X11 or Wayland
* Flatpak version
* Flatseal version

**Comment by lionirdeadman** [comment]
Yeah sure, sorry.

Distro : Fedora Silverblue 32.20200820.0
Display : Wayland
Flatpak : 1.6.5
Flatseal : 1.6.1 (8913e7ab933674b537a577efe8deda1eef53f0bff18059b8244ad4327590d398)

**Comment by tchx84** [comment]
That's very strange, I have the exact same environment. I assume this happens only to Flatseal right?

My first guess would be that windowing system permissions were removed form Flatseal, and therefore the "no display" error.

So, from the terminal, remove any overrides applied to Flatseal itself (see [tipsandtricks](https://github.com/tchx84/Flatseal/blob/master/TIPSANDTRICKS.md)).

`rm ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal`

**Comment by lionirdeadman** [comment]
I have no overrides and yeah, only Flatseal from what I can tell. I think the "NoDisplay=True" is relating to desktop files though.

**Comment by tchx84** [comment]
> I have no overrides and yeah, only Flatseal from what I can tell. I think the "NoDisplay=True" is relating to desktop files though.

You're right. I misread the error. As you suggested, this happening while parsing some `.desktop` from an application you have installed. Would be great if you could `grep NoDisplay` your installed apps just to see what's the value that's making `AppStreamGlib` crash.

I will try to trigger to it on my end to make things more robust on Flatseal end.

**Comment by tchx84** [comment]
@lionirdeadman I can't reproduce this, so do you mind testing the PR :)? 

Let me know if you need help to do so !

**Comment by lionirdeadman** [comment]
I built it from manifest by changing `HEAD` to `origin/handle-appstreamglib-parsing-issues` and it does work!

Sorry I couldn't help earlier. Thanks!

**Comment by tchx84** [comment]
Great :) Thanks for reporting the issue.

**Comment by lionirdeadman** [comment]
Do you plan to push an update to Flathub or wait for a future release @tchx84?

**Comment by tchx84** [comment]
Planned for Friday ;) I am trying to get something else in. I hope you don't mind running your own special version until then hah.

**Comment by lionirdeadman** [comment]
No problem, works for me. Thanks again!

**Comment by tchx84** [comment]
should be available in flathub in a couple hours ;) thanks for the report!
