### ISSUE TITLE
Does not respect Flatpak theming

### ISSUE THREAD

**Issue by ayhc** [tchx84/Flatseal#133]
Flatseal defaults to Adwaita on my Fedora 32 KDE install.

I have installed the Breeze GTK+ theme from Flathub, and other Flatpak apps detect and use the theme.

**Comment by tchx84** [comment]
Hey @ayhc ,

Is not really an issue on Flatseal. Please, take a look at https://github.com/tchx84/Flatseal/issues/74 , someone has encountered this issue before.

**Comment by ayhc** [comment]
As I noted in my original post on the issue, other Flatpak apps (including Flatpak apps that use GTK+) have no difficulty in detecting the Breeze GTK+ theme installed via Flathub.

Issue 74 is simply not relevant.

**Comment by tchx84** [comment]
> As I noted in my original post on the issue, other Flatpak apps (including Flatpak apps that use GTK+) have no difficulty in detecting the Breeze GTK+ theme installed via Flathub.
> 
> Issue 74 is simply not relevant.

But have you read it ?

**Comment by ayhc** [comment]
> > As I noted in my original post on the issue, other Flatpak apps (including Flatpak apps that use GTK+) have no difficulty in detecting the Breeze GTK+ theme installed via Flathub.
> > Issue 74 is simply not relevant.
> 
> But have you read it ?

Yes, I **have** read it (and the linked Issue #1384).

I can also confirm that Glimpse, installed via Flathub, both detects and respects the Breeze GTK+ theme installed from Flathub.

**Edit:** Note that even in Issue 74, the colour scheme is **still** not correct in Wayland.  (Not relevant in this specific case as I am using X11).

**Comment by tchx84** [comment]
Not all apps are made equal, so telling me that another app does what you want is not really telling me much.

I recommend that you take the time to understand what is going on with #74 (where the same issue is showing up for the same environment you describe) to understand why I am explaining is not a problem I can solve.
