### ISSUE TITLE
Flatseal fails to start

### ISSUE THREAD

**Issue by ghost** [tchx84/Flatseal#137]
Installed Flatseal via Flatpak repos and it won't start. The output seemed to be a dbus issue so I included dbus-monitor output as well.

<details>
	<summary>Output from flatpak run com.github.tchx84.Flatseal</summary>
	<pre>	
(com.github.tchx84.Flatseal:2): Gjs-WARNING **: 12:03:23.947: JS ERROR: GLib.Error g-spawn-exit-error-quark: Error spawning command line “dbus-launch --autolaunch=7126b610f175ab7d5bdf3d0e5f1aa25f --binary-syntax --close-stderr”: Child process exited with code 1
get session@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:24
_has_software_manager@resource:///com/github/tchx84/Flatseal/js/widgets/detailsButton.js:71:1
_setup@resource:///com/github/tchx84/Flatseal/js/widgets/detailsButton.js:56:48
_init@resource:///com/github/tchx84/Flatseal/js/widgets/detailsButton.js:49:14
_setup@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:83:37
_init@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:69:14
vfunc_activate@resource:///com/github/tchx84/Flatseal/js/application.js:75:28
main@resource:///com/github/tchx84/Flatseal/js/main.js:32:24
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
@/app/bin/com.github.tchx84.Flatseal:9:17
	</pre>
</details>

<details>
	<summary>Output from dbus-monitor while trying to run Flatseal.</summary>
	<pre>
signal time=1599509248.604272 sender=org.freedesktop.DBus -> destination=:1.11 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.11"
signal time=1599509248.604311 sender=org.freedesktop.DBus -> destination=:1.11 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.11"
method call time=1599509249.475032 sender=:1.12 -> destination=org.freedesktop.DBus serial=1 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=Hello
method return time=1599509249.475158 sender=org.freedesktop.DBus -> destination=:1.12 serial=1 reply_serial=1
   string ":1.12"
signal time=1599509249.475184 sender=org.freedesktop.DBus -> destination=(null destination) serial=24 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.12"
   string ""
   string ":1.12"
signal time=1599509249.475198 sender=org.freedesktop.DBus -> destination=:1.12 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.12"
method call time=1599509249.475533 sender=:1.12 -> destination=org.freedesktop.DBus serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',path='/org/freedesktop/DBus',arg0='org.freedesktop.Flatpak'"
method return time=1599509249.475548 sender=org.freedesktop.DBus -> destination=:1.12 serial=3 reply_serial=2
method call time=1599509249.476246 sender=:1.12 -> destination=org.freedesktop.DBus serial=3 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=StartServiceByName
   string "org.freedesktop.Flatpak"
   uint32 0
method call time=1599509249.483585 sender=:1.13 -> destination=org.freedesktop.DBus serial=1 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=Hello
method return time=1599509249.483770 sender=org.freedesktop.DBus -> destination=:1.13 serial=1 reply_serial=1
   string ":1.13"
signal time=1599509249.483922 sender=org.freedesktop.DBus -> destination=(null destination) serial=25 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.13"
   string ""
   string ":1.13"
signal time=1599509249.483968 sender=org.freedesktop.DBus -> destination=:1.13 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.13"
method call time=1599509249.491975 sender=:1.13 -> destination=org.freedesktop.DBus serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',path='/org/freedesktop/DBus'"
method return time=1599509249.491997 sender=org.freedesktop.DBus -> destination=:1.13 serial=3 reply_serial=2
method call time=1599509249.492795 sender=:1.13 -> destination=org.freedesktop.DBus serial=3 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RequestName
   string "org.freedesktop.Flatpak"
   uint32 1
signal time=1599509249.492856 sender=org.freedesktop.DBus -> destination=(null destination) serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string "org.freedesktop.Flatpak"
   string ""
   string ":1.13"
method return time=1599509249.492945 sender=org.freedesktop.DBus -> destination=:1.12 serial=4 reply_serial=3
   uint32 1
signal time=1599509249.492969 sender=org.freedesktop.DBus -> destination=:1.13 serial=5 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string "org.freedesktop.Flatpak"
method return time=1599509249.492982 sender=org.freedesktop.DBus -> destination=:1.13 serial=6 reply_serial=3
   uint32 1
method call time=1599509249.493468 sender=:1.12 -> destination=org.freedesktop.DBus serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.Flatpak"
method return time=1599509249.493493 sender=org.freedesktop.DBus -> destination=:1.12 serial=5 reply_serial=4
   string ":1.13"
method call time=1599509249.493775 sender=:1.12 -> destination=:1.13 serial=5 path=/org/freedesktop/Flatpak/SessionHelper; interface=org.freedesktop.Flatpak.SessionHelper; member=RequestSession
method return time=1599509249.494209 sender=:1.13 -> destination=:1.12 serial=4 reply_serial=5
   array [
      dict entry(
         string "path"
         variant             string "/run/user/1000/.flatpak-helper/monitor"
      )
      dict entry(
         string "pkcs11-socket"
         variant             string "/run/user/1000/.flatpak-helper/pkcs11-flatpak-22519"
      )
   ]
method call time=1599509249.494618 sender=:1.12 -> destination=org.freedesktop.DBus serial=6 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RemoveMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',path='/org/freedesktop/DBus',arg0='org.freedesktop.Flatpak'"
method return time=1599509249.494709 sender=org.freedesktop.DBus -> destination=:1.12 serial=6 reply_serial=6
method call time=1599509249.495523 sender=:1.12 -> destination=org.freedesktop.portal.Documents serial=7 path=/org/freedesktop/portal/documents; interface=org.freedesktop.portal.Documents; member=GetMountPoint
method return time=1599509249.495862 sender=:1.6 -> destination=:1.12 serial=12 reply_serial=7
   array of bytes "/run/user/1000/doc" + \0
method call time=1599509249.496773 sender=:1.12 -> destination=org.a11y.Bus serial=8 path=/org/a11y/bus; interface=org.a11y.Bus; member=GetAddress
method return time=1599509249.497066 sender=:1.3 -> destination=:1.12 serial=8 reply_serial=8
   string "unix:abstract=/tmp/dbus-nD7enphZa7,guid=b83ee9baf8d36966169747395f569278"
signal time=1599509249.511164 sender=org.freedesktop.DBus -> destination=:1.12 serial=5 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.12"
signal time=1599509249.511346 sender=org.freedesktop.DBus -> destination=(null destination) serial=7 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.12"
   string ":1.12"
   string ""
	</pre>
</details>

**Comment by tchx84** [comment]
Hey @Daveed9 ,

Can you :
1. Describe a bit more about your system? e.g. distro/version, desktop environment/version, flatpak/version, Flatseal/version  etc.
2. Check https://github.com/tchx84/Flatseal/issues/127 and see if this could be the same issue?

**Comment by ghost** [comment]
1. I'm running Void Linux x64 with libc. My desktop environment is Xfce4 (4.14.1_1). Flatpak 1.6.3 and Flatseal 1.6.2.

2. The issue does appear to be the same, but it doesn't seem that a solution was found. I use XFCE, which they claimed fixed the issue. I installed d-feet and tried to access the session bus, but I was unable to (no errors displayed).
![dfeet](https://user-images.githubusercontent.com/21017248/92417653-44e87d00-f131-11ea-92ea-5780c9ae2c32.png)

**Comment by tchx84** [comment]
@Daveed9 can you help me test this ? (since I can't reproduce this)

PR is https://github.com/tchx84/Flatseal/pull/138
