### ISSUE TITLE
Add undo button

### ISSUE THREAD

**Issue by TheEvilSkeleton** [tchx84/Flatseal#142]
Just a suggestion, it'd be really cool if there was an undo button. Next to the Reset button:

![Screenshot from 2020-09-14 17-03-25](https://user-images.githubusercontent.com/50847364/93137995-dc1f7880-f6cd-11ea-8792-a14ab590bc04.png)

**Comment by tchx84** [comment]
What would be the difference? Compared to reset, I mean.

**Comment by TheEvilSkeleton** [comment]
Let's say you make two changes, but you want to remove the last change, having an Undo button would make it easier because you won't need to rewrite/retoggle the other stuff.

Also, if you use Reset, you could revert the reset by pressing the Undo button.

Not sure, that might be a me thing because I play/test a lot with Flatpak and its permissions.

**Comment by haggen88** [comment]
I also think it would be a good idea to have a button to undo the recent changes.

**Comment by tchx84** [comment]
We will need to think a bit about the UX/UI details, e.g.

* How to display the button
* Where to put it
* What other visual cues we can use to show what is being "reverted"

**Comment by haggen88** [comment]
To visualize the undo, the button could show the check symbol in a square that changes to a green color, for example something like this:

![undo button 1](https://user-images.githubusercontent.com/68134588/93376947-bced2c00-f830-11ea-9ea6-7d84e7585975.png)
![undo button](https://user-images.githubusercontent.com/68134588/93374948-d3de4f00-f82d-11ea-94a1-49672ac1a09f.png)

**Comment by tchx84** [comment]
> To visualize the undo, the button could show the check symbol in a square that changes to a green color, for example something like this:
> 
> ![undo button](https://user-images.githubusercontent.com/68134588/93374948-d3de4f00-f82d-11ea-94a1-49672ac1a09f.png)

I meant, to visualize the permissions that are changed vs the ones that aren't, to make the changes and changes undo process more visual.

**Comment by haggen88** [comment]
How about making the box of the permissions that change, when restored change the color a little bit ? 
Something like that:

A) With changes in the permissions [only the color of the button changes]
![0undo button _start](https://user-images.githubusercontent.com/68134588/93428956-e39e7780-f8af-11ea-8c80-2aed4e83bcd7.png)

B) With permissions restored to their previous condition [compared to how it was when starting the "Flatseal session"].
![1undo button _fnal](https://user-images.githubusercontent.com/68134588/93428966-e600d180-f8af-11ea-8876-3b78519009ea.png)

**Comment by TheEvilSkeleton** [comment]
Won't that ruin other GTK themes, especially in dark themes?

**Comment by haggen88** [comment]
It would be necessary to see how to adapt it to dark themes. Personally I imagine it something like this:
[The green/blue color of the highlighted permission box is the same as the button but with an opacity of 40%].

![z1](https://user-images.githubusercontent.com/68134588/93533131-d5913b00-f931-11ea-9e47-e4b63d372b2e.png)

![z2](https://user-images.githubusercontent.com/68134588/93533146-daee8580-f931-11ea-822e-79f81304ee3b.png)

--

Another option would be to include other buttons that indicate the undo activity for the allowances ... but in that case, in my opinion there would be many buttons.

A less graphic option would be to use logs that indicate what permission changed depending on the application.

**Comment by tchx84** [comment]
Maybe @bertob has some suggestions :)

**Comment by bertob** [comment]
I'm not convinced an undo button is needed here. Generally we use undo in places where you could lose significant amounts of work, which I don't think is the case for switching individual toggles.

The one scenario where I could see it making sense is when you reset the whole panel, but for that you could do a temporary in-app notification, rather than an always-visible button.

**Comment by tchx84** [comment]
> I'm not convinced an undo button is needed here. Generally we use undo in places where you could lose significant amounts of work, which I don't think is the case for switching individual toggles.
> 
> The one scenario where I could see it making sense is when you reset the whole panel, but for that you could do a temporary in-app notification, rather than an always-visible button.

Valid points.
