### ISSUE TITLE
Support switching versions

### ISSUE THREAD

**Issue by Eonfge** [tchx84/Flatseal#145]
With Flatpak, you can easily run a specific version of a specific package. 

Get all versions:
`flatpak remote-info --log flathub org.gnome.Lollypop`

Switch to a version:
` flatpak update --commit=HASH org.gnome.Lollypop`

Would it be interesting to include a UI component for this, so that users can easily roll back a version if there is a breaking change in the never version?

**Comment by tchx84** [comment]
Hey @Eonfge ,

I considered these (and other similar CLI Flatpak utils) at some point but, I decided to keep Flatseal focused on permissions only.

**Comment by Eonfge** [comment]
I totally respect that. It's better to do one thing well, then many things mediocre
