### ISSUE TITLE
Poll on "flatpak equivalent" collumn in DOCUMENTATION.md

### ISSUE THREAD

**Issue by TheEvilSkeleton** [tchx84/Flatseal#158]
I'm opening an issue because I want to know people's thoughts on the `flatpak equivalent` collumn in [`DOCUMENTATION.md`](https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md).

This will be a poll. Whichever gets the most voted will be in DOCUMENTATION.md (if it's okay with @tchx84).

React:
- :+1: for **1.**
- :rocket: for **2.**
- :smile: for **3.**
- :eyes: for **4.**

---

## 1. With `flatpak equivalent` (current)

Name | `flatpak override` equivalent | Type | Description
--- | --- | --- | ---
Network | `--share=network` and `--unshare=network` | Toggle | Allow (`--share=network`) or prohibit (`--unshare=network`) access to the network.
[Inter-process communications](https://en.wikipedia.org/wiki/Inter-process_communication) | `--share=ipc` and `--unshare=ipc` | Toggle | Share (`--share=ipc`) or unshare (`--unshare=ipc`) IPC namespace with the host.

---

## 2. Without `flatpak equivalent`

Name | Type | Description
--- | --- | ---
Network | Toggle | Allow (`--share=network`) or prohibit (`--unshare=network`) access to the network.
[Inter-process communications](https://en.wikipedia.org/wiki/Inter-process_communication) | Toggle | Share or unshare IPC namespace with the host.

---

## 3. With `flatpak equivalent` without mentioning it in the description

Name | `flatpak override` equivalent | Type | Description
--- | --- | --- | ---
Network | `--share=network` and `--unshare=network` | Toggle | Allow or prohibit access to the network.
[Inter-process communications](https://en.wikipedia.org/wiki/Inter-process_communication) | `--share=ipc` and `--unshare=ipc` | Toggle | Share or unshare IPC namespace with the host.

## 4. With `flatpak equivalent` in the last collumn, without mentioning it in the description

Name | Type | Description | `flatpak override` equivalent
--- | --- | --- | ---
Network | Toggle | Allow or prohibit access to the network. | `--share=network` and `--unshare=network`
[Inter-process communications](https://en.wikipedia.org/wiki/Inter-process_communication) | Toggle | Share or unshare IPC namespace with the host. | `--share=ipc` and `--unshare=ipc`

**Comment by tchx84** [comment]
I would say **4.**: just like **3.**, but move the equivalency column to last.

Keep in mind that the goal of Flatseal is to help people have more control over their apps and, therefore, the documentation should serve that purpose, by making it as easier to understand as possible.

It is also true that people use Flatseal simply because is easier to use, and for those would be beneficial to keep the equivalency column, for those coming from CLI.

**Comment by TheEvilSkeleton** [comment]
> I would say **4.**: just like **3.**, but move the equivalency column to last.

I actually preferred **4.** the most. I updated the description so feel free to vote it.

> It is also true that people use Flatseal simply because is easier to use, and for those would be beneficial to keep the equivalency column, for those coming from CLI.

Agreed

**Comment by tchx84** [comment]
> > I would say **4.**: just like **3.**, but move the equivalency column to last.
> 
> I actually preferred **4.** the most. I updated the description so feel free to vote it.
> 
> > It is also true that people use Flatseal simply because is easier to use, and for those would be beneficial to keep the equivalency column, for those coming from CLI.
> 
> Agreed

Just go for it!

**Comment by TheEvilSkeleton** [comment]
> Just go for it!

To be honest, I would also want to have other people's opinion; if they have anything to suggest. I don't mind waiting for a bit.

**Comment by TheEvilSkeleton** [comment]
Does GitHub have a due date like GitLab does? You could add a due date so I can start working on it once it past due.
