### ISSUE TITLE
New icon?

### ISSUE THREAD

**Issue by bertob** [tchx84/Flatseal#17]
If you're interested in a new app icon in the GNOME style, I'd be happy to help with that.

**Comment by tchx84** [comment]
Please :pray:

**Comment by tchx84** [comment]
@bertob any progress on this front? :) Let me know what ideas you have.

**Comment by jpmacdonald** [comment]
![flatseal](https://user-images.githubusercontent.com/61254896/74885303-35dfe000-5343-11ea-862e-5fbb7d9bfc28.png)
Thoughts on something like this?

**Comment by tchx84** [comment]
> Thoughts on something like this?

It looks **a lot** better than my icon :) What do you think @bertob ?

**Comment by tchx84** [comment]
> > Thoughts on something like this?
> 
> It looks **a lot** better than my icon :) What do you think @bertob ?

by any chance @jpmacdonald, do you have a .svg version ?

**Comment by jpmacdonald** [comment]
Yes, seems I can't upload it directly here, hope this works. Feel free to use it or tweak it if you want. 

[svg.zip](https://github.com/tchx84/Flatseal/files/4228495/svg.zip)

**Comment by bertob** [comment]
@jpmacdonald nice, I pretty much had the same thing in mind.

I put your icon on the icon grid, and added a few stylistic flourishes:

![image](https://user-images.githubusercontent.com/1908896/74946741-0f30b080-53fa-11ea-8086-ffa38021f67f.png)

@tchx84 I'm not super happy with it color-wise, since it looks a little boring, but we could ship this for now if you want.

**Comment by tchx84** [comment]
> @jpmacdonald nice, I pretty much had the same thing in mind.
> 
> I put your icon on the icon grid, and added a few stylistic flourishes:
> 
> @tchx84 I'm not super happy with it color-wise, since it looks a little boring, but we could ship this for now if you want.

@bertob looks great to me, let's ship it!

@jpmacdonald can you confirm that you agree licensing your icon under GPLv3 or later (which is the license used in this project)? So we can merge it in the project and use the modifications from @bertob.

**Comment by jpmacdonald** [comment]
I think that looks even better! Nice. You can license it however you want!

**Comment by bertob** [comment]
Ok, here you go:

[com.github.tchx84.Flatseal.zip](https://github.com/tchx84/Flatseal/files/4232725/com.github.tchx84.Flatseal.zip)

Note that the .Source file is the "source" SVG the other ones are exported from. It's recommended to also keep that in your repo, even though it's not actually used as an asset.

**Comment by tchx84** [comment]
> I think that looks even better! Nice. You can license it however you want!

Awesome, thanks!

**Comment by tchx84** [comment]
> Ok, here you go:
> 
> [com.github.tchx84.Flatseal.zip](https://github.com/tchx84/Flatseal/files/4232725/com.github.tchx84.Flatseal.zip)
> 
> Note that the .Source file is the "source" SVG the other ones are exported from. It's recommended to also keep that in your repo, even though it's not actually used as an asset.

Will do, this is great! thanks!
