### ISSUE TITLE
Split headerbar

### ISSUE THREAD

**Issue by bertob** [tchx84/Flatseal#18]
The non-split headerbar is a bit odd, since it mixes gobal controls (primary menu) and ones specific to the currently selected app (title, reset button).

![image](https://user-images.githubusercontent.com/1908896/73927565-e674cb00-48d1-11ea-8c04-486322460e67.png)

I'd change it to what e.g. Disks and Settings do, a split headerbar and the primary menu on the right side of the left panel. This would also make it easier to make the app adaptive with HdyLeaflet later, since you could cleanly split the two panels.

![image](https://user-images.githubusercontent.com/1908896/73927723-3489ce80-48d2-11ea-8ecb-ef2984599018.png)

**Comment by tchx84** [comment]
Yes, in fact, the current "design" is inspired in GNOME settings applications section, which does exactly what you describe.

I just haven't got into it, since I have been prioritizing other things.

**Comment by tchx84** [comment]
I will give it a try today.

**Comment by tchx84** [comment]
This is an initial pass, I just need to check gnome-disks code and see how it does to "sync" both panes.

![Screenshot from 2020-02-06 10-55-43](https://user-images.githubusercontent.com/481418/73943294-461da700-48cf-11ea-95a7-b71db5ea3604.png)

**Comment by bertob** [comment]
Looks great! I'd maybe use the app name as the title on the left panel.

**Comment by tchx84** [comment]
I ended up implementing this with libhandy, behaves pretty decently.
