### ISSUE TITLE
[Suggestion] Add reload/refresh button

### ISSUE THREAD

**Issue by TheEvilSkeleton** [tchx84/Flatseal#187]
The title says all. Flatseal lacks a reload feature. Everytime I install a flatpak, I need to close Flatseal and reopen it, which is a bit annoying.

**Comment by tchx84** [comment]
I suppose this could be done automatically, without the user needing to do something.

**Comment by TheEvilSkeleton** [comment]
That sounds much better.

**Comment by nekohayo** [comment]
Similarly, when you remove a flatpak while flatseal is running, instead of removing it from the view, its icon changes to some generic unknown icon in flatseal; so in a way, maybe flatseal already has a way to know something is going on. Maybe with inotify?

**Comment by tchx84** [comment]
Working on this.
