### ISSUE TITLE
No applications found

### ISSUE THREAD

**Issue by bluewww** [tchx84/Flatseal#189]
I'm using flatpak with
`export FLATPAK_OSTREE_REPO_MODE=user-only`

Flatseal won't find any installed application when using this mode.

**Comment by tchx84** [comment]
hey @bluewww , can you describe your setup a bit more?

e.g. are you overriding any other `FLATPAK_*` environment variable?

e.g. where are your flatpak installations located?

**Comment by tchx84** [comment]
I am closing this, Simply `export FLATPAK_OSTREE_REPO_MODE=user-only` is not enough to reproduce this on my end, so if you ever get the chance to provide more information, feel free to reopen this.
