### ISSUE TITLE
i686 binary build

### ISSUE THREAD

**Issue by sss123next** [tchx84/Flatseal#195]
please upload i686 binary build somewhere, preferable on flathub, building on low-end laptop is pain and for some reason flatpak-builder compaining about missed dependencies

```
flatpak-builder --force-clean --user build com.github.tchx84.Flatseal.json
error: org.gnome.Sdk/i386/3.38 not installed
Failed to init: Unable to find sdk org.gnome.Sdk version 3.38
```

**Comment by tchx84** [comment]
Hey @sss123next 

I don't think there is a i386 version of the GNOME runtime so, being honest, this would be hard to do, since I don't have the infrastructure to build and publish on my own, reason why I publish Flatseal on Flathub.

For the time being, your best chance would be to build Flatseal without flatpak, using system dependencies and meson (or check if Flatseal is available on your distro).

If anyone wants to help with this, more than welcome, btw.

**Comment by sss123next** [comment]
understood, thx for reply.

**Comment by tchx84** [comment]
> understood, thx for reply.

Actually, it seems I was wrong... please try:

```
flatpak install flathub org.gnome.Sdk/i386/3.38
flatpak install flathub org.gnome.Platform/i386/3.38
```
and then try to build it...

**Comment by sss123next** [comment]
sorry, it in non-english, but i think easy to understand by context, can it be what `--user` causing problems ?

also package have .compat postfix ..., maybe this is a problem ?


```
❯ cd Flatseal/
❯ flatpak install --user flathub org.gnome.Sdk/i386/3.38 
Поиск похожих запросов...
Найдена ссылка 'runtime/org.gnome.Sdk.Compat.i386/i386/3.38' в репозитории 'flathub' (user).
Использовать эту ссылку? [Y/n]: 


        ID                                   Ветка            Оп            Удалённый репозиторий           Загрузка
 1. [✓] org.gnome.Sdk.Compat.i386            3.38             i             flathub                         235,6 МБ / 251,8 МБ

Установка завершена.
❯ flatpak install --user flathub org.gnome.Platform/i386/3.38
Поиск похожих запросов...
Найдена ссылка 'runtime/org.gnome.Platform.Compat.i386/i386/3.38' в репозитории 'flathub' (user).
Использовать эту ссылку? [Y/n]: 


        ID                                         Ветка             Оп            Удалённый репозиторий            Загрузка
 1. [|] org.gnome.Platform.Compat.i386             3.38              i             flathub                          < 194,4 МБ

Установка... ████████████████████ 100%  733,7 кБ/s  00:00
❯ flatpak-builder --force-clean --repo=repo --user build com.github.tchx84.Flatseal.json
error: org.gnome.Sdk/i386/3.38 not installed
Failed to init: Unable to find sdk org.gnome.Sdk version 3.38
```

**Comment by tchx84** [comment]
hmm, it could be that these extensions are meant for compatibility for i386 from a x86_64 machine, but not the other way around... 

I think you should ask in [discourse](https://discourse.gnome.org/) what would be the best approach for running (or atleast build) apps for i386, I am sure someone there might know more than I do.

**Comment by sss123next** [comment]
i am runing this on i686 native machine, so it should NOT be compat layer for x86 on x86_64, because host arch is x86 (i686)

**Comment by tchx84** [comment]
Since this isn't really a Flatseal problem, per-se, I am closing this. I hope you found a way to get a i386 runtime running or built Flatseal manually.
