### ISSUE TITLE
Titlebar buttons incorrectly placed when buttons are set in the left

### ISSUE THREAD

**Issue by TheEvilSkeleton** [tchx84/Flatseal#200]
![image](https://user-images.githubusercontent.com/50847364/100402800-31132f80-302b-11eb-8332-2effc92b79a3.png)

The title bar buttons (<kbd>X</kbd> and <kbd>-</kbd>) are placed in the left side of the middle when it should be in the far left.

**Comment by tchx84** [comment]
Hey @TheEvilSkeleton ,

Can you describe your setup ? OS version, Desktop, locale, and any other system configuration you think could be relevant.

I can't reproduce this in any other test machine I use.

**Comment by TheEvilSkeleton** [comment]
OS: Fedora Silverblue
DE: GNOME
Locale: en_CA.UTF-8
The only thing I really changed is setting the titlebar buttons to the left by using GNOME Tweaks; and adding the <kbd>-</kbd>

**Comment by tchx84** [comment]
I can reproduce it now, thanks, it is actually a regression.. as I fixed this before :sweat_smile:
