### ISSUE TITLE
Unset environment variables don't show up/get removed

### ISSUE THREAD

**Issue by BurnerWah** [tchx84/Flatseal#204]
Variables set with `VAR=` get removed from the user config, and don't show up when present in the flatpak metadata.

Setting a variable to an empty string unsets it.

**Comment by tchx84** [comment]
hey @YaBoiBurner , can provide a detailed example? To make sure I understand.

**Comment by BurnerWah** [comment]
For example, here's the `Environment` steam flatpak's metadata (`com.valvesoftware.Steam`):

```desktop
[Environment]
PYTHONPATH=/app/utils/lib/python3.8/site-packages
TZ=
ALSA_CONFIG_PATH=
LC_NUMERIC=C
PROTON_DEBUG_DIR=/var/tmp
STEAM_RUNTIME_PREFER_HOST_LIBRARIES=
DBUS_FATAL_WARNINGS=0
LC_MONETARY=C
STEAM_EXTRA_COMPAT_TOOLS_PATHS=/app/share/steam/compatibilitytools.d
XDG_CONFIG_DIRS=/etc/xdg:/usr/lib/x86_64-linux-gnu/GL:/usr/lib/i386-linux-gnu/GL
SSL_CERT_DIR=/etc/ssl/certs
STEAM_RUNTIME=
LC_TELEPHONE=C
LC_COLLATE=C
LC_NAME=C
MESA_GLSL_CACHE_DIR=
LC_MEASUREMENT=C
SDL_VIDEODRIVER=
PATH=/app/bin:/app/utils/bin:/usr/bin
LC_ADDRESS=C
```

But here's what it looks like in flatseal:

![Screenshot from 2020-12-10 21-10-49](https://user-images.githubusercontent.com/10004812/101857037-80467d80-3b5e-11eb-8d9c-f75e5f490b70.png)

The `TZ`, `ALSA_CONFIG_PATH`, `STEAM_RUNTIME_PREFER_HOST_LIBRARIES`, `STEAM_RUNTIME`, `MESA_GLSL_CACHE_DIR`, and `SDL_VIDEODRIVER` variables don't show up in flatseal.

**Comment by tchx84** [comment]
I see, so is many things:

1. Not showing `TZ=` is by design, it means that variable is "removed" from the app.

2. I think I noticed the other issues you mentioned, that variables still show even after they were actually removed.

I guess fixing (2) takes priority for now.
