### ISSUE TITLE
Flatseal always starts with a maximized window

### ISSUE THREAD

**Issue by ghost** [tchx84/Flatseal#205]
I can observe this on the KDE Plasma desktop environment.

**Comment by tchx84** [comment]
hey @wsdfhjxc !

Thanks for the feedback. Note that this is the intended behavior, and I would prefer to keep it like this.

**Comment by ghost** [comment]
Although I don't understand that decision, this is a minor inconvenience and I guess I can live with it. :slightly_smiling_face:
