### ISSUE TITLE
Remove device=shm

### ISSUE THREAD

**Issue by hfiguiere** [tchx84/Flatseal#209]
Flatseal list "device=shm" as a way to access JACK. The problem is that this doesn't work (it's a JACK thing) and therefor is misleading to advertise it as such.

**Comment by tchx84** [comment]
Hey @hfiguiere , thanks for reaching out.

Flatseal will display it as long as Flatpak supports that static permission. If there's something broken with Flatpak or JACK, please reach to those projects.

**Comment by hfiguiere** [comment]
> Hey @hfiguiere , thanks for reaching out.
> 
> Flatseal will display it as long as Flatpak supports that static permission. If there's something broken with Flatpak or JACK, please reach to those projects.

You could remove the mention of JACK in the UI. Yes everybody is aware it doesn't work with JACK, etc [1]. The point here is just about the UI of Flatseal.


[1] Given the amount of audio stuff I maintain on Flathub....

**Comment by tchx84** [comment]
@hfiguiere would you be kind to point me to the relevant upstream issues ? So I can inform myself.

**Comment by hfiguiere** [comment]
https://github.com/flatpak/flatpak/issues/1509 has the gist of it.

**Comment by tchx84** [comment]
@hfiguiere PR ready, I would strongly suggest you also bring this issue to flatpak documentation since it also mentions JACK in there.
