### ISSUE TITLE
Global permission overrides

### ISSUE THREAD

**Issue by ghost** [tchx84/Flatseal#210]
Is it in the scope of Flatseal that it could also allow managing global permission overrides?

I'm talking about an additional list item called "All applications" (e.g. placed above the search bar), which would display a simplified version of the generic application details view, but containing just the global permission settings (perhaps including a clearly visible warning that global permission overrides have less priority than application-specific permission overrides).

**Comment by Arxcis** [comment]
It is worth mentioning that there are 2 global override files.

**User global override**
When you do:
```
flatpak --user override --nofilesystem=home
```
The following file is produced
```
$ cat ~/.local/share/flatpak/overrides/global 
[Context]
filesystems=!home;
```

**System global override**
When you do
```
sudo flatpak override --nofilesystem=home
```
The following file is produced
```
$ cat /var/lib/flatpak/overrides/global 
[Context]
filesystems=!home;
```

**Comment by tchx84** [comment]
With #423 I am getting closer to this but, to do this with a proper UX, I need to tackle #279 first, or this can become the source of a lot of confusion.

**Comment by tchx84** [comment]
Almost there...
