### ISSUE TITLE
Skype webcam & audio input & output issue

### ISSUE THREAD

**Issue by krishnaTORQUE** [tchx84/Flatseal#213]
I am unable to setup audio & camera on skype.
Skype webcam & audio input & output issue with the permission.

I tried with command line 
`flatpak override --user com.skype.Client --socket=pulseaudio`

I install flatseal & there is not webcam permission I can see. I just installed flatseal & i am new to it.

**Comment by krishnaTORQUE** [comment]
**UPDATE**

I have discovered the webcam section but after checked it & reopen skype its still showing no device available.
![Screenshot_2021-01-11_13-16-34](https://user-images.githubusercontent.com/4960568/104156598-6fb04e00-540f-11eb-93d7-94bfa42a96af.png)

**Comment by krishnaTORQUE** [comment]
**The Issue**

![Screenshot_2021-01-11_13-34-51](https://user-images.githubusercontent.com/4960568/104160995-0ed94380-5418-11eb-86a9-3f8ce0786960.png)

**Comment by tchx84** [comment]
Hey @krishnaTORQUE ,

I believe this is a question for the Flatpak bundle maintainers, so please contact them here https://github.com/flathub/com.skype.Client/issues

Good luck!
