### ISSUE TITLE
Set a minimum content width

### ISSUE THREAD

**Issue by bilelmoussaoui** [tchx84/Flatseal#22]
The GtkScrolledWindow should set a minmium content width otherwise I can resize the app so small like. It should be 360px width
https://valadoc.org/gtk+-3.0/Gtk.ScrolledWindow.set_min_content_width.html

![Screenshot from 2020-02-08 04-32-07](https://user-images.githubusercontent.com/7660997/74078543-fc969e80-4a2b-11ea-9dee-fa7d1f4bb83a.png)

**Comment by tchx84** [comment]
Thanks, I noticed it as well.

I was trying to figure out why it happens only the first time you shrink the window though. Once it switches to folded mode, and you make one transition, it _will_ enforce the size requests I set.

I will try with minimum content width as well then.

**Comment by tchx84** [comment]
I tried it and I can still reproduce the issue. Maybe there is something wrong in the way I am setting up these leaflets (I assume you can't reproduce this in your read-later app).

![Screenshot from 2020-02-08 07-59-35](https://user-images.githubusercontent.com/481418/74084018-35913c00-4a49-11ea-9d89-1074ae6bfe22.png)

**Comment by tchx84** [comment]
Yeah, :sweat_smile: , setting `width-request` directly to the content Leaflet solved the issue.

**Comment by tchx84** [comment]
Thanks again!
