### ISSUE TITLE
Selecting the "Sonic 3 AIR" flatpak causes flatseal to use 99% CPU and freeze

### ISSUE THREAD

**Issue by pizzadude** [tchx84/Flatseal#220]
When selecting the "Sonic 3 AIR" flatpak from flathub (https://flathub.org/apps/details/org.sonic3air.Sonic3AIR) in Flatseal, the program uses 99% CPU and freezes, and needs to be killed. All other flatpaks work fine when selected in the permission manager.

**Comment by tchx84** [comment]
Oh, a fun weekend is coming :laughing:

**Comment by pizzadude** [comment]
Confirmed fixed.

**Comment by tchx84** [comment]
> Confirmed fixed.

Thank you!
