### ISSUE TITLE
Window title buttons appear incorrectly when window buttons are on opposing ends

### ISSUE THREAD

**Issue by electricduck** [tchx84/Flatseal#222]
Fairly niche problem, but I thought I'd bring it up. elementaryOS (or Pantheon DE) uses `close:maximize` by default, which displays like this in applications that render them correctly:

![Screenshot from 2021-01-31 00 22 12](https://user-images.githubusercontent.com/1594644/106371290-a1f00400-635a-11eb-9293-3b575521d16e.png)
The top application is a built-in elementaryOS app; the middle application is GNOME Disks, which works correctly with no modifications; and the bottom is Audacious, with a fairly standard non-unified titlebar.

However, I assume because of the way Flatseal "folds" the window, they appear like this (as well as the titlebar collapsing):

![Screenshot from 2021-01-31 00 21 01](https://user-images.githubusercontent.com/1594644/106371304-c9df6780-635a-11eb-9470-24e40963dcbf.png)

An assumption, but I imagine other DEs that have been configured with a similar "opposing" button layout will also incur this issue. Its also worth noting if Pantheon is configured with a fairly standard layout (such as `:minimize,maximize,close`), they appear correctly, as they would on any other GTK-based DE.

**Comment by tchx84** [comment]
:confused: , will check it out

**Comment by tchx84** [comment]
hey @electricduck ,

If you have the time, can you test this on master and see if there's any difference?

**Comment by electricduck** [comment]
![image](https://user-images.githubusercontent.com/1594644/111055169-08446800-846b-11eb-98e8-d9b7b6d30aa3.png)

Yep, tested on 6893eb6f572e401db49ca09c39555eda1cc7653d and everything works as intended on elementary: the buttons appear correct in both the folded and unfolded states, and the UI has no longer "collapsed".

**Comment by tchx84** [comment]
@electricduck excellent! Thanks for testing.
