### ISSUE TITLE
Invalid validation rule for env vars

### ISSUE THREAD

**Issue by saivert** [tchx84/Flatseal#223]
I'm trying to set an environment variable like so:

    PULSE_PROP_media.category=Manager

But It seems to refuse to add environment variables with a dot.

It works fine if I do it from the command line like so:

    flatpak run --env=PULSE_PROP_media.category=Manager org.pulseaudio.pavucontrol

edit: btw I sumitted a PR to the org.pulseaudio.pavucontrol flatpak repo so this override will soon be unnecessary.

**Comment by tchx84** [comment]
hey @saivert , thanks for reaching out.

> But It seems to refuse to add environment variables with a dot.
> 

What happens is that dots are not valid characters in `bash` syntax. (I suppose this app is not expecting that variable to get exported from the shell or something).

> It works fine if I do it from the command line like so:
> 
> ```
> flatpak run --env=PULSE_PROP_media.category=Manager org.pulseaudio.pavucontrol
> ```
> 

hmm, I will check what Flatpak does, maybe it doesn't validate at all.

> edit: btw I submitted a PR to the org.pulseaudio.pavucontrol flatpak repo so this override will soon be unnecessary.

+1

**Comment by tchx84** [comment]
I assume this was fixed on Flatpak package.
