### ISSUE TITLE
All access are granted if access to ~/foo is enabled

### ISSUE THREAD

**Issue by nidamanx** [tchx84/Flatseal#224]
Hi,
Flatseal allows access to all system if a directory in home is allowed.

To have a better test, I tried 
- to allow **only** /opt and all was fine.
- to allow Download folder using `xdg-download` and it was fine too.

## Example to reproduce with QOwnNotes
`flatpak install flathub org.qownnotes.QOwnNotes`

## FlatSeal enabled settngs
- socket=x11
- socket=wayland
- other files=~/foo/notes

All other settings are disabled

## System
- Debian 10 Buster
- Flatseal 1.6.8

**Comment by tchx84** [comment]
Hey @nidamanx thanks for reaching out.

Do you mind running some steps?

1. Open Flatseal, and go to org.qownnotes.QOwnNotes.
2. Press the reset button, and double check that the override file does not exist, e.g. `cat ~/.local/share/flatpak/overrides/org.qownnotes.QOwnNotes`.
3. Now back to Flatseal and add `~/foo/notes` as per your example, and print the overrides contents, e.g. `cat ~/.local/share/flatpak/overrides/org.qownnotes.QOwnNotes`.

Please paste here the contents of the override file.

**Comment by nidamanx** [comment]
Sure!
```
$ cat ~/.local/share/flatpak/overrides/org.qownnotes.QOwnNotes
[Context]
filesystems=~/Nextcloud/Notes
```

What I can say is:
1) Flatseal is a great tool. It should be installed by default while installing Flatpack
2) I had a chat with org.qownnotes.QOwnNotes Flatpak developers and they explained me I could see all system exposed from the App itself because QOwnNotes runs in a portal. That was alarming me a bit.

So, I think
*all' s well that ends well*

Thank you very much for your reply
Have a nice day/evening

**Comment by tchx84** [comment]
> Sure!
> 
> ```
> $ cat ~/.local/share/flatpak/overrides/org.qownnotes.QOwnNotes
> [Context]
> filesystems=~/Nextcloud/Notes
> ```
> 

Yes, that was were I was going :)

> What I can say is:
> 
> 1. Flatseal is a great tool. It should be installed by default while installing Flatpack
> 2. I had a chat with org.qownnotes.QOwnNotes Flatpak developers and they explained me I could see all system exposed from the App itself because QOwnNotes runs in a portal. That was alarming me a bit.
> 

:+1: 

> So, I think
> _all' s well that ends well_
> 
> Thank you very much for your reply
> Have a nice day/evening

Thanks, you too.
