### ISSUE TITLE
 Flatseal/DOCUMENTATION.md  | Addition of new Language entry

### ISSUE THREAD

**Issue by Ricky-Tigg** [tchx84/Flatseal#230]
Hi. That guidance from _Documetation_  for adding a **new translation** might be a model.
```
$ echo "es" >> po/LINGUAS
$ ninja flatseal-pot
$ ninja flatseal-update-po
$ flatpak config --set extra-languages es
$ flatpak update org.gnome.Platform
$ LC_ALL=es_PY.UTF-8 flatpak run com.github.tchx84.Flatseal
```
I also conceived there might be an **element** among those strings to be modified in order to set a specific language code, let's say _fi_ for Finnish. A source language file must exist as well somewhere. Since there is no official statement yet regarding those considerations, i would need to ensure my interpretations are valid.

**Comment by tchx84** [comment]
hey @Ricky-Tigg ,

Do you mind clarifying your suggestions? I am not entirely sure I understand.

**Comment by Ricky-Tigg** [comment]
Hello.  Strings following "_Add new translations_", as the header suggests it,  have to be interpreted as covering the instruction to follow in order to add a new translation. A language has then to be depicted there. What then could it be if any?

**Comment by Ricky-Tigg** [comment]
System-wide installation | Unknown location of file po/_LINGUAS_ in my system. Is that file intended to be within one of the following directories?
- ~/.var/app/com.github.tchx84.Flatseal/
- ~/.local/share/applications/
- /var/lib/flatpak/app/com.github.tchx84.Flatseal/

**Comment by tchx84** [comment]
> System-wide installation | Unknown location of file po/_LINGUAS_ in my system. Is that file intended to be within one of the following directories?
> 
> * ~/.var/app/com.github.tchx84.Flatseal/
> * ~/.local/share/applications/
> * /var/lib/flatpak/app/com.github.tchx84.Flatseal/

You will need to provide much more context, so I can help you here. Can you describe step by step how you get there?

**Comment by Ricky-Tigg** [comment]
I'd better reformulate entirely. _po/LINGUAS_ that you exhibited has no context. You can notice it by yourself. Indeed you are missing the **whole path**..

**Comment by tchx84** [comment]
> I'd better reformulate entirely. _po/LINGUAS_ that you exhibited has no context. You can notice it by yourself. Indeed you are missing the **whole path**..

Well @Ricky-Tigg , thanks for trying, but I am really lost here regarding what exactly is the problem or how you got there.

If you figure out how to fix this, please send a pull request.

**Comment by Ricky-Tigg** [comment]
II won't have any doubt that you try your best. The lack of absolute path makes the determination of that **file location** challenging. Till now you are still the only one aware of its location.

**Comment by Ricky-Tigg** [comment]
Lack of _glib-compile-resources_
```
$ meson _translate && cd _translate
The Meson build system
Version: 0.59.4
Source dir: /home/yk/Lataukset/Flatseal
Build dir: /home/yk/Lataukset/Flatseal/_translate
Build type: native build
Project name: flatseal
Project version: 1.7.5
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Program appstream-util found: YES (/usr/bin/appstream-util)
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Found pkg-config: /usr/bin/pkg-config (1.8.0)
WARNING: Could not detect glib version, assuming 2.54. You may get build errors if your glib is older.
Program glib-compile-resources found: NO
(...)
```
_Installed:_
```
$ dnf -q --installed rq --archlist noarch,x86_64 --qf '%{name} %{version}' glib? | column
glib2 2.70.4	glibc 2.34
```

**Comment by Ricky-Tigg** [comment]
Lack of _glib-compile-resources_
```
$ meson _translate && cd _translate
The Meson build system
Version: 0.61.3
Source dir: /home/yk/Lataukset/Flatseal
Build dir: /home/yk/Lataukset/Flatseal/_translate
Build type: native build
Project name: flatseal
Project version: 1.7.5
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Program appstream-util found: YES (/usr/bin/appstream-util)
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Found pkg-config: /usr/bin/pkg-config (1.8.0)
WARNING: Could not detect glib version, assuming 2.54. You may get build errors if your glib is older.
Program glib-compile-resources found: NO
(...)
```
_Installed:_
```
$ dnf -q --installed rq --archlist noarch,x86_64 --qf '%{name} %{version}' glib? | column
glib2 2.70.4	glibc 2.34
```

**Comment by Ricky-Tigg** [comment]
`meson _translate && cd _translate` outputs "`po/meson.build:1:5: ERROR: File fi.po does not exist.`". As that error message indicates it,  [instruction](https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md#add-new-translations) is incomplete.

_required_:
`$ touch  po/es.po # 'es' for Spanish` 
_before_:
`$ meson _translate && cd _translate`
