### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by JJ4884** [tchx84/Flatseal#240]
Flatpak for Flatseal does not work in wayland. Tried both in GUI and in terminal. Here is the output from attempting to launch in the terninal. 
![image](https://user-images.githubusercontent.com/13912247/112407840-2755bc00-8ced-11eb-9675-03050e9d8427.png)

**Comment by tchx84** [comment]
> Flatpak for Flatseal does not work in wayland. Tried both in GUI and in terminal. Here is the output from attempting to launch in the terninal.
> ![image](https://user-images.githubusercontent.com/13912247/112407840-2755bc00-8ced-11eb-9675-03050e9d8427.png)

Oh, I can assure you it does work. I am using it right now (so does several other people).

But, I remember seeing something similar once, e.g. I switched to X11 for recording something, then came back to Wayland and saw that problem, but, the issue went away after I restarted the machine (it also happened with other apps, so it must have been a system wide issue). I wonder if you falling into this?

**Comment by JJ4884** [comment]
Distro - OpenSuse Tumbleweed

I have tried restarting and going into the Wayland session directily with the issue not resolving.

**Comment by tchx84** [comment]
Can you try these following commands?

```
rm ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal
flatpak run com.github.tchx84.Flatseal
```

or ...

```
flatpak run --nosocket=wayland --socket=x11 com.github.tchx84.Flatseal
```

or ....

```
flatpak run --nosocket=x11 --socket=wayland com.github.tchx84.Flatseal
```

Did any of these make any diff?

**Comment by JJ4884** [comment]
Output troubleshooting 
`jgjopnsse@localhost:~> rm ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal
rm: cannot remove '/home/jgjopnsse/.local/share/flatpak/overrides/com.github.tchx84.Flatseal': No such file or directory

jgjopnsse@localhost:~> rm ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal
rm: cannot remove '/home/jgjopnsse/.local/share/flatpak/overrides/com.github.tchx84.Flatseal': No such file or directory

jgjopnsse@localhost:~> flatpak run --nosocket=wayland --socket=x11 com.github.tchx84.Flatseal   #Ran successfully 


jgjopnsse@localhost:~> flatpak run --nosocket=x11 --socket=wayland com.github.tchx84.Flatseal
(com.github.tchx84.Flatseal:2): Gtk-WARNING **: 02:55:42.047: cannot open display: 

`

**Comment by tchx84** [comment]
> jgjopnsse@localhost:~> flatpak run --nosocket=wayland --socket=x11 com.github.tchx84.Flatseal #Ran successfully
> 
> jgjopnsse@localhost:~> flatpak run --nosocket=x11 --socket=wayland com.github.tchx84.Flatseal
> (com.github.tchx84.Flatseal:2): Gtk-WARNING **: 02:55:42.047: cannot open display:

Just to make it clear, Flatseal runs just fine in both X11 and Wayland. There is certainly something wrong with your system, but I can't tell what it is exactly. My first guess would be that Wayland is not really o properly installed / running. 

In any case, I would recommend to:

1.  Launch Flatseal with `flatpak run --nosocket=wayland --socket=x11 com.github.tchx84.Flatseal`
2. Change Flatseal's permissions (using Flatseal GUI) to enable X11 and disable Wayland.
3.  So you won't need to do this manually.

good luck!
