### ISSUE TITLE
Add support for enabling GTK Inspector in flatpak apps

### ISSUE THREAD

**Issue by somas95** [tchx84/Flatseal#252]
Since Flatpak apps have a separate GSettings storage file, the global `org.gtk.Settings.Debug enable-inspector-keybinding` setting doesn't apply to them.

The inspector needs to be enabled in a per-app basis with something like:

```
flatpak run --command='sh' org.gnome.Polari
gsettings set org.gtk.Settings.Debug enable-inspector-keybinding true
```

It'd be quite useful and within the scope of Flatseal to have a toggle to enable/disable the inspector in each one of the flatpaks.

Thanks!

**Comment by tchx84** [comment]
hey @somas95 

> It'd be quite useful and within the scope of Flatseal to have a toggle to enable/disable the inspector in each one of the flatpaks.

I agree it would be useful, but I disagree this would be within the scope of Flatseal, as this is not a permission.

But, by mere chance, there is a way to use Flatseal and achieve the same result:

Just export the `GTK_DEBUG=interactive` variable using Flatseal, e.g (note is the actual example heh):
![image](https://user-images.githubusercontent.com/481418/113932379-86bdcc80-97c1-11eb-8a50-6177661fb4f1.png)

There's no support for "global" overrides, so you would still need to do it per-app.

> 
> Thanks!

Hope it helps.

**Comment by somas95** [comment]
Ok, thanks! I wasn't hopping for a global override, just a per-app toggle. I find myself running the command from above quite a lot when coding/debugging, and while a simple toggle would be ideal, the `GTK_DEBUG=interactive` workaround works quite well. Thanks!
