### ISSUE TITLE
Run cleanup functionality 🧹

### ISSUE THREAD

**Issue by Eonfge** [tchx84/Flatseal#26]
Perhaps it would be interesting to include a special button in the UI to clean up unused runtimes. Right now a user can run this him- or herself, but you could consider adding a duster icon above the applications overview to clean up unused runtimes

```
flatpak uninstall --system --unused
```
## Considerations
- Made sure you add `--system`. Without it, you can also throw away your developer dependencies, which would be a serious pain for flathub maintainers. `--system` Is enough for 90% off all users
- Show basic 'in progress' and 'complete' animations so the user knows what's going on

**Comment by Eonfge** [comment]
I've done some tests, and I'm not sure if this is actually possible with the current sandboxing model of Flatpak. Might want to ask the Flatpak masters from Flathub before trying to build it.

**Comment by tchx84** [comment]
I think is a good ideal for a separate app, to handle these kind of tweaks. But for this app I think it should stick to managing permissions.

**Comment by gmagic** [comment]
@tchx84 i would argue. I use your app everyday and it seems for me that flatseal really lacks of such function... just like to set some overrides (setting user theme for flatpak apps).

BTW: thanks for your really "must have" flatseal :)

P.S. and i can agree that this should be the part of software store maybe...
