### ISSUE TITLE
Dark mode broken

### ISSUE THREAD

**Issue by razzeee** [tchx84/Flatseal#272]
Tried using flat seal with `Adwaita Dark` on Manjaro.

![image](https://user-images.githubusercontent.com/5943908/115921067-4f1a7a00-a47b-11eb-817e-73de9aa00d64.png)

**Comment by tchx84** [comment]
hey @Razzeee ,

Ugh, that looks bad, indeed. Do you mind sharing more information about your environment?

If you can share the output of these commands, it will help me understand this better where we are standing.

```
$ flatpak --version
$  cat /etc/os-release
$ echo $XDG_CURRENT_DESKTOP
$ flatpak list | grep -i theme
```

My first guess is that you're using KDE/Plasma, and that whatever theme you're using is not very friendly with Libhandy's widgets. For example, this is how Adwaita Dark looks on my machine:

![image](https://user-images.githubusercontent.com/481418/115932069-364d9c80-a45a-11eb-9ae0-a78c35f01204.png)

But let's see!

**Comment by razzeee** [comment]
```
 ~  flatpak --version
Flatpak 1.10.2
 ~  cat /etc/os-release 
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
 ~  echo $XDG_CURRENT_DESKTOP 
GNOME
 ~  flatpak list | grep -i theme
Matcha-sea GTK theme	org.gtk.Gtk3theme.Matcha-sea		3.22	flathub	system
 ~  

```

It might just be me having broken something on my setup. The flatpak theme looks fishy I guess?

**Comment by tchx84** [comment]
> ```
>  ~  flatpak --version
> Flatpak 1.10.2
>  ~  cat /etc/os-release 
> NAME="Manjaro Linux"
> ID=manjaro
> ID_LIKE=arch
> BUILD_ID=rolling
> PRETTY_NAME="Manjaro Linux"
> ANSI_COLOR="32;1;24;144;200"
> HOME_URL="https://manjaro.org/"
> DOCUMENTATION_URL="https://wiki.manjaro.org/"
> SUPPORT_URL="https://manjaro.org/"
> BUG_REPORT_URL="https://bugs.manjaro.org/"
> LOGO=manjarolinux
>  ~  echo $XDG_CURRENT_DESKTOP 
> GNOME
>  ~  flatpak list | grep -i theme
> Matcha-sea GTK theme	org.gtk.Gtk3theme.Matcha-sea		3.22	flathub	system
>  ~  
> ```
> 

my bad, forgot to add:

```
$ gsettings get org.gnome.desktop.interface gtk-theme
```

> It might just be me having broken something on my setup. The flatpak theme looks fishy I guess?

Probably not, I actually tried it on my end, looks fine and nothing like you show there.

**Comment by tchx84** [comment]
So, I reproduced your setup and this is how it looks:

![Screenshot from 2021-04-23 23-13-25](https://user-images.githubusercontent.com/481418/115945410-b0494a00-a489-11eb-9178-c744d8992047.png)

If you run Flatseal with the following command, you can experiment with different themes:

```
$ GTK_DEBUG=interactive flatpak run com.github.tchx84.Flatseal 
```

That will open the GTK Inspector and, from the "Visual" tab, you can switch between the themes available (and dark variants).

That will probably provide more clues as of what could be happening ;)

**Comment by razzeee** [comment]
```
 ~  gsettings get org.gnome.desktop.interface gtk-theme
'Adwaita'

```

The visual panel looks weird I guess. 
![image](https://user-images.githubusercontent.com/5943908/115953569-8bd28980-a4ec-11eb-9071-bad7b872da64.png)

If I select adwaita and just set it to dark it seems fine.
At this point, I'm not sure if it's really a problem with flatseal.

**Comment by tchx84** [comment]
> ```
>  ~  gsettings get org.gnome.desktop.interface gtk-theme
> 'Adwaita'
> ```
> 

Just to clarify, does Flatseal look OK when it's set only to Adwaita ?

> The visual panel looks weird I guess.
> ![image](https://user-images.githubusercontent.com/5943908/115953569-8bd28980-a4ec-11eb-9071-bad7b872da64.png)
> 

:confused: if I am parsing that image correctly, no themes are showing?

> If I select adwaita and just set it to dark it seems fine.

When you say "I select" where and how is this being done?

How does it looks when you set it using:

```
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
```

> At this point, I'm not sure if it's really a problem with flatseal.

I tend to believe is not really on Flatseal's end, simply because I tested it in several different OS/DE combos. But, there's certainly something broken somewhere.

**Comment by razzeee** [comment]
> > ```
> >  ~  gsettings get org.gnome.desktop.interface gtk-theme
> > 'Adwaita'
> > ```
> 
> Just to clarify, does Flatseal look OK when it's set only to Adwaita ?
> 

yes, non dark mode looks fine to me

> > The visual panel looks weird I guess.
> > ![image](https://user-images.githubusercontent.com/5943908/115953569-8bd28980-a4ec-11eb-9071-bad7b872da64.png)
> 
> confused if I am parsing that image correctly, no themes are showing?

Not on load, they are in the dropdown and available. I guess my laptop might be defaulting to a theme, that's not installed? Then again, the commands you gave me would have revealed that? The list in there is not matching, what Gnome Tweaks has, but I think that's due to flatpak having it's own themes?

> 
> > If I select adwaita and just set it to dark it seems fine.
> 
> When you say "I select" where and how is this being done?

Via the visual tab, that you referenced in the debugger. But as stated, I first need to choose adwaita too.

> 
> How does it looks when you set it using:
> 
> ```
> gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
> ```

Ran this in the terminal then started flatseal via search (not terminal) no change it seems.

> 
> > At this point, I'm not sure if it's really a problem with flatseal.
> 
> I tend to believe is not really on Flatseal's end, simply because I tested it in several different OS/DE combos. But, there's certainly something broken somewhere.

**Comment by tchx84** [comment]
> Not on load, they are in the dropdown and available. I guess my laptop might be defaulting to a theme, that's not installed? 

Oh, I see, yes... please try this:

```
$ flatpak install flathub org.gtk.Gtk3theme.Adwaita-dark
$ gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
```

**Comment by razzeee** [comment]
Hrm, that seems to fix it, thank you.

**Comment by jakiisheep** [comment]
Hello! I have the same issues, but I'm trying to use a system theme, It seems like flatseal does detect it (I checked in GTK Inspector, I guess because I was messing with the flatpak permissions and I somehow got it to detect the theme) 
But the theme works only when I change it from the inspector, and on the next restart, it reverts back to Adwaita 
I even tried Adwaita-dark but it doesn't work, I tried the commands provided here, doesn't work. 
I guess I'm gonna have to give up, and other flatpak apps don't even detect the theme...

**Comment by lenkotarski** [comment]
> > Not on load, they are in the dropdown and available. I guess my laptop might be defaulting to a theme, that's not installed?
> 
> Oh, I see, yes... please try this:
> 
> ```
> $ flatpak install flathub org.gtk.Gtk3theme.Adwaita-dark
> $ gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
> ```

Big freakin thank you.
If any fellow Steam Deck users finds this thread on Google, this is what just worked for me right now.
Also make sure you have
`GTK_THEME=Adwaita-dark`
added as a variable for Flatseal itself, or else Flatseal won't use it!

**Comment by skafiend** [comment]
I haven't managed to force Flatseal to use dark mode even though I can switch between dark and light modes with GTK_DEBUG=interactive, and the app sees my current GTK_THEME but prefers ignore it all together. However, I found a crude workaround.

- Create a new desktop entry "com.github.tchx84.Flatseal.desktop" in "~/.local/share/applications". The name is important. If Flatseal doesn't find the file, it recreates it:

```
[Desktop Entry]
Name=Flatseal
Exec=~/flatseal.sh
Comment=
Terminal=false
Icon=/usr/share/swcatalog/icons/fedora/64x64/com.github.tchx84.Flatseal.png
Type=Application
```

- A put this in the wrapper script:

```
#!/bin/bash

export ADW_DEBUG_COLOR_SCHEME=prefer-dark 
flatpak run com.github.tchx84.Flatseal
```

I tried to set the variable using /env/environment and ~/.profile, but it won't work for Flatseal and might mess with other apps, so it's not worth it.
