### ISSUE TITLE
[Feature Request/Regression] Typeahead

### ISSUE THREAD

**Issue by ManIVIctorious** [tchx84/Flatseal#278]
Recently, flatseal's user interface got a little bit overhauled which led to a few usability issues.
Before, on startup the search field was on focus which made it quite comfortable to use the application via just starting it and typing the name of the desired application. After the recent update one has to click the lence icon on the top left (note I wasn't able to find a shortcut to activate this, neither crtl+f nor ctrl+s worked).

In my opinion the new look is definitely cleaner, but this comes with quite a loss of functionality/usability.
Would it be possible to automatically go into search mode when typing?

Thanks in advance

**Comment by tchx84** [comment]
hey @ManIVIctorious ,

Thanks for reaching out, yes, I added ctrl+f accelerator in https://github.com/tchx84/Flatseal/commit/54a8c326f21c1a6ea1471a3f46c964d26e9d60c7 will be available in the next release (around next week).

**Comment by ManIVIctorious** [comment]
Thanks, at least that would make it more keyboard friendly.
Any chance you could implement true type-ahead (e.g. like in nautilus when you type something it automatically triggers the search), or is this incompatible with your design principles?

**Comment by tchx84** [comment]
> Thanks, at least that would make it more keyboard friendly.
> Any chance you could implement true type-ahead (e.g. like in nautilus when you type something it automatically triggers the search), or is this incompatible with your design principles?

Check this out https://github.com/tchx84/Flatseal/pull/276 , I discussed the idea there.

**Comment by tchx84** [comment]
This is now fixed on master.
