### ISSUE TITLE
Highlight changed permissions

### ISSUE THREAD

**Issue by tchx84** [tchx84/Flatseal#279]
Moving this idea out of https://github.com/tchx84/Flatseal/issues/163 to reduce confusion.

The idea is to somehow highlight permissions rows that were changed (compared to the application defaults), e.g using:

* border
* background-color
*  badge
* etc

@bertob any ideas?

**Comment by bertob** [comment]
Hmmm, is there relevant art for something like this in other apps?

As for ideas, I wonder if something very subtle like just making the description title bold would work?

**Comment by rusty-snake** [comment]
> Hmmm, is there relevant art for something like this in other apps?

dconf-editor:
![Screenshot_2021-07-15_07-47-31-fs8](https://user-images.githubusercontent.com/41237666/125750492-beb89617-c747-41e6-8248-eae433f114ee.png)

firefox (about:config):
![Screenshot_2021-07-15_07-42-34-fs8](https://user-images.githubusercontent.com/41237666/125750547-a13e92ba-31a9-468f-bb30-109ac239f451.png)

chom* (chrome://flags):
![Screenshot_2021-07-15_07-46-46-fs8](https://user-images.githubusercontent.com/41237666/125750605-77abb721-a563-4078-9542-cc0f6e5db653.png)
