### ISSUE TITLE
Flatseal requires a microphone

### ISSUE THREAD

**Issue by saivert** [tchx84/Flatseal#285]
$ flatpak run com.github.tchx84.Flatseal

(com.github.tchx84.Flatseal:2): Gjs-CRITICAL **: 18:55:05.047: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for microphone
_proxyInvoker@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:122:46
_makeProxyMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:147:30
changed@resource:///com/github/tchx84/Flatseal/js/models/portals.js:317:42
_checkIfChanged@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:153:47
_updateProperties@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:180:14
_setup@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:220:14
set appId@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:279:14
_update@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:219:9
_setup@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:197:14
_init@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:73:14
vfunc_activate@resource:///com/github/tchx84/Flatseal/js/application.js:78:28
main@resource:///com/github/tchx84/Flatseal/js/main.js:34:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/app/bin/com.github.tchx84.Flatseal:9:17

What is this?

**Comment by tchx84** [comment]
hey @saivert 

It's Flatseal interacting with the permissions store. Something seems to be failing while reading the application portal data. And no, flatseal does not ` requires a microphone ` .

Do you mind sharing more information about your system? So I can reproduce this, and fix whatever is going on.

1. How did you install Flatseal? package manager? Flathub?
2. what version of flatpak and flatseal is this?
3. what is your distro and its exact version?

**Comment by tchx84** [comment]
> hey @saivert
> 
> It's Flatseal interacting with the permissions store. Something seems to be failing while reading the application portal data. And no, flatseal does not `requires a microphone` .
> 
> Do you mind sharing more information about your system? So I can reproduce this, and fix whatever is going on.
> 
> 1. How did you install Flatseal? package manager? Flathub?
> 2. what version of flatpak and flatseal is this?
> 3. what is your distro and its exact version?

No need, I just found a way to reproduce it.

**Comment by saivert** [comment]
Installed Flatseal from Flathub.
Flatpak 1.10.2
Flatseal 1.7.1
Distro: Fedora 33
Also running pipewire in case that is relevant.

    $flatpak permission-list devices
    Table   Object App Permissions Data
    devices camera     yes         0x00

**Comment by tchx84** [comment]
> Installed Flatseal from Flathub.
> Flatpak 1.10.2
> Flatseal 1.7.1
> Distro: Fedora 33
> Also running pipewire in case that is relevant.
> 
> ```
> $flatpak permission-list devices
> Table   Object App Permissions Data
> devices camera     yes         0x00
> ```

Thanks, yeah, is the same thing I reproduced, fixing it now.

**Comment by tchx84** [comment]
@saivert can you test this PR? https://github.com/tchx84/Flatseal/pull/286

```
$ git clone https://github.com/tchx84/Flatseal.git
$ cd Flatseal
$ git checkout portals-fix-id-support
$ flatpak-builder --force-clean --repo=repo build com.github.tchx84.Flatseal.json
$ flatpak build-bundle repo flatseal.flatpak com.github.tchx84.Flatseal
$ flatpak install flatseal.flatpak
$ flatpak run com.github.tchx84.Flatseal//master
```

**Comment by saivert** [comment]
Yes it works now. And I can see microphone is grayed out under portals as expected.
Is this new portal something that requires newer Flatpak?

**Comment by tchx84** [comment]
> Yes it works now. And I can see microphone is grayed out under portals as expected.
> Is this new portal something that requires newer Flatpak?

Kind of, it's something related to a service called "permissions store". TLDR; Flatseal can't really tell a few things, so it only allows to modify portal permissions when it sees evidence of that portal being used. That's why "camera" is enabled and not "microphone" in your case.

Thanks for testing btw, ill need to clean this up a bit more and will make a new release during the week.
