### ISSUE TITLE
Flatseal always starts in fullscreen

### ISSUE THREAD

**Issue by inorick** [tchx84/Flatseal#287]
The Flatseal windows always starts up in full screen (i.e. maximized). I tried both starting from gnome-shell as well as from CLI using `flatpak run com.github.tchx84.Flatseal`.

**Comment by tchx84** [comment]
hey @inorick

> The Flatseal windows always starts up in full screen (i.e. maximized). I tried both starting from gnome-shell as well as from CLI using `flatpak run com.github.tchx84.Flatseal`.

This is an [explict](https://github.com/tchx84/Flatseal/blob/master/src/widgets/window.js#L74) behavior, I am curious why do you consider this an issue?

**Comment by inorick** [comment]
Hello @tchx84,

I think it is an issue because it differs from the default behavior of other Gnome applications. Most of these applications do two things:

- They have their initial size (first startup) determined by their content, i.e. they are as small as possible without obscuring content.
- They restore their size to the size of their previous run.

The first point follows the recommendations of the [GTK+ developers](https://discourse.gnome.org/t/named-sizes-for-standard-wide-screen/2765/2):
> The size of a window is dictated by the size of its contents, and the size of its contents are dictated by things like UI layout, text (which can be translated), and image data.

and further down:

> In general, never set the size of widget explicitly. Always use the expand/align flags, and let the content dictate the size of a window.

The second point follows the [Gnome developer documentation](https://developer.gnome.org/SaveWindowState/):
> There are few window states that should generally be saved:
> * the window size
> * whether the window is maximized, if the window supports it
> * whether the window is full screen, if the window supports it

In my case, having a window starting up like this (and obscuring all other windows)
![big](https://user-images.githubusercontent.com/27500920/118110629-f0de1880-b3e2-11eb-87b2-24d5528845e7.png)

is less useful than this:
![small](https://user-images.githubusercontent.com/27500920/118110593-e459c000-b3e2-11eb-8a42-0c64f44184d8.png)

**Comment by tchx84** [comment]
I created a PR so we can play around with this...

> The first point follows the recommendations of the [GTK+ developers](https://discourse.gnome.org/t/named-sizes-for-standard-wide-screen/2765/2):
>
> ..
>.
>  In general, never set the size of widget explicitly. Always use the expand/align flags, and let the content dictate the size of a window.
>
> ...
>
> * the window size
> * whether the window is maximized, if the window supports it
> * whether the window is full screen, if the window supports it

~My understanding is that these requirements should not be implemented at the app level, so maybe there is a bug to catch preventing these behaviors...~ Nope, this indeed is a per-app thing.

> In my case, having a window starting up like this (and obscuring all other windows)
> ![big](https://user-images.githubusercontent.com/27500920/118110629-f0de1880-b3e2-11eb-87b2-24d5528845e7.png)
> 

Ugh, it certainly doesn't look good in 4K.

**Comment by tchx84** [comment]
@inorick can you give https://github.com/tchx84/Flatseal/pull/289 a try ?

**Comment by inorick** [comment]
Thanks for the quick fix. I just tested it and it behaves as expected :+1:
