### ISSUE TITLE
Trying to add a Filesystem entry with space in name gives "This is not a valid option" error

### ISSUE THREAD

**Issue by andrevmatos** [tchx84/Flatseal#288]
I'm trying to add `xdg-download/Telegram Desktop:create` to Filesystem's Other Files option (after changing `xdg-download` to `:ro`), but Flatseal gives me `This is not a valid option` error. If I replace the space with e.g. `_`, it works, but Telegram expects by default the above name to download its files to.

**Comment by tchx84** [comment]
hey @andrevmatos 

> I'm trying to add `xdg-download/Telegram Desktop:create` to Filesystem's Other Files option (after changing `xdg-download` to `:ro`), but Flatseal gives me `This is not a valid option` error. If I replace the space with e.g. `_`, it works, but Telegram expects by default the above name to download its files to.

Most likely a bug in the regex that checks these custom paths, but, you shoud know that it will still work (is only a warning)... e.g, check your application override file under `~/.local/share/flatpak/overrides/`.

So, this shouldn't be a blocker for what you're trying to do.

**Comment by andrevmatos** [comment]
I managed to set the permission explicitly for my user with
```sh
flatpak --user override --filesystem=xdg-download/Telegram\ Desktop:create org.telegram.desktop
```
It works fine, the folder is even created by Telegram if it doesn't exist, although Flatseal still shows the warning when I open Telegram settings in it.

**Comment by tchx84** [comment]
> I managed to set the permission explicitly for my user with
> 
> ```shell
> flatpak --user override --filesystem=xdg-download/Telegram\ Desktop:create org.telegram.desktop
> ```
> 
> It works fine, the folder is even created by Telegram if it doesn't exist, although Flatseal still shows the warning when I open Telegram settings in it.

You can still do that from Flatseal, is just a warning. Flatseal will add that permission anyways, even if the warning shows.

**Comment by tchx84** [comment]
hey @andrevmatos ,

Can you test #294 ? Let me know if you need help building it.

**Comment by andrevmatos** [comment]
Sorry for the late reply. Just confirming the issue is fixed. Thanks
