### ISSUE TITLE
Firefox profile changes after altering filesystem permissions

### ISSUE THREAD

**Issue by hellpe** [tchx84/Flatseal#290]
Hello,

This could be a Firefox issue rather than a Flatseal one, but since I'm not sure, I'm submitting it to your judgement:
Currently, when using Firefox 88.0.1 from Flathub on my Arch Linux setup, filesystem access is by defaut set up to "/etc/firefox/policies" and "xdg-download", which is very restrictive (cannot download or upload anything from any other folder than "Downloads").

So, I've tried to enable the "All user files" switch via Flatseal, but after restarting Firefox, it loads on a empty profile, without my cache, history, bookmarks, open tabs, etc. Switching the permission back to "off" and restarting Firefox loads the correct profile. As a workaround, I've tried to manually copy my profile in the folder seemingly used by Firefox when "All user files" is on, but [because of an existing Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1625111), I cannot locate the actual profile directory (it should be sandboxed, but I don't know where to find it).

The whole issue is very annoying, since it basically prevents me of using Flatseal with Firefox. Could it be related to Flatseal itself?

**Comment by tchx84** [comment]
hey @hellpe ,

From what you describe, this seems more like Firefox behaving differently when `--filesystem=home` is enabled, e.g. I can imagine it assumes a different profile path when it can "see" more directories.

But let's double check by doing the same change without Flatseal:

```
$ flatpak --user override --filesystem=home org.mozilla.firefox
```

If the result is the same, then there's nothing Flatseal can do about this.

Also, try this:

```
$ cat  ~/.local/share/flatpak/overrides/org.mozilla.firefox
```
See if the contents of that file is different when you make the change with Flatseal vs flatpak-override (as shown above).

Then we will know for sure.

**Comment by tchx84** [comment]
Feel free to re-open this issue if you find something wrong as-per the test I suggested above.
