### ISSUE TITLE
Add flatpak kill instance

### ISSUE THREAD

**Issue by digitalethics** [tchx84/Flatseal#293]
For some Flatpaks such as [MS Teams](https://flathub.org/apps/details/com.microsoft.Teams), I'd love to have the option in Flatseal to force `flatpak kill com.microsoft.Teams` upon closing the MS Teams window. Others prefer it to be just the way it is, to have MS Teams running in the background despite the window being closed so that they can continue to receive notifications. Do you think there is a viable way to add this to the Flatseal interface or would further adjustments to the actual [MS Teams Flatpak](https://github.com/flathub/com.microsoft.Teams/issues) be required? In my view this permissions model should be agnostic so that regular users could switch between these two modes in Flatseal with a simple click. It is also somewhat security- and privacy-relevant as ideally you'd want to be in control of what applications are still running and which ones aren't.

**Comment by tchx84** [comment]
> For some Flatpaks such as [MS Teams](https://flathub.org/apps/details/com.microsoft.Teams), I'd love to have the option in Flatseal to force `flatpak kill com.microsoft.Teams` upon closing the MS Teams window.

In theory, if you use Flatseal to disable the "background" permission, close the app, it should be killed after a minute or so.

> Do you think there is a viable way to add this to the Flatseal interface or would further adjustments to the actual [MS Teams Flatpak](https://github.com/flathub/com.microsoft.Teams/issues) be required? 

Background permission are defined during runtime, so there's nothing really that could be done at build time (unless you change the app itself).

> In my view this permissions model should be agnostic so that regular users could switch between these two modes in Flatseal with a simple click.

Try Flatseal 1.7.2, disable the "Background" permission and launch the app.

**Comment by tchx84** [comment]
oh, specifically about the title "flatpak kill instance", I don't have any plans to do process management in Flatseal. But this case should be covered with what I mentioned above.

**Comment by digitalethics** [comment]
Thanks!
