### ISSUE TITLE
Highlight changed settings

### ISSUE THREAD

**Issue by ManIVIctorious** [tchx84/Flatseal#30]
First of all, thank you very much for this wonderful application,

I have a few very minor issues with the UX though:
Would it be possible to highlight (e.g. display slightly different background color) on the entries which are not in their default state? That way it would be easily seen which settings have been tweaked by the user. Another possibility (although I think a lot harder to implement) would be to make the "reset" button inline and only displaying it when the setting has been changed.

Additionally it would be cool if the reset button would only show up on applications for which overrides actually exist.

Thank you for considering this and keep up the excellent work.

**Comment by tchx84** [comment]
These are fine suggestions.

Ill try to look into these, after I am done with some other UX improvements I am working on.

**Comment by tchx84** [comment]
> Additionally it would be cool if the reset button would only show up on applications for which overrides actually exist.

I played with this today, the button will only be enabled if there's something to "reset". It's merged on master (not released yet) you can give it a try following the instructions from the README.

**Comment by ManIVIctorious** [comment]
Sry, didn't have the time to try it out in the past few days, but I just saw that it is already included in the release build. Awesome, thank you very much for considering this suggestion
