### ISSUE TITLE
Flatseal doesn't show any GUI

### ISSUE THREAD

**Issue by emanuelserpa** [tchx84/Flatseal#306]
Tried to run with `flatpak run` and shows this:

```
❯ flatpak run com.github.tchx84.Flatseal
Gtk-Message: 19:01:06.512: Failed to load module "appmenu-gtk-module"

(com.github.tchx84.Flatseal:2): Gtk-WARNING **: 19:01:06.655: Theme directory 32@2x/devices of theme Vimix-Amethyst-dark has no size field


(com.github.tchx84.Flatseal:2): Gjs-CRITICAL **: 19:01:06.856: JS ERROR: TypeError: right-hand side of 'in' should be an object, got null
updateProxyProperty/<@resource:///com/github/tchx84/Flatseal/js/models/portals.js:305:17
updateProxyProperty@resource:///com/github/tchx84/Flatseal/js/models/portals.js:297:47
_updateProperties/<@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:190:54
_updateProperties@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:190:31
_setup@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:232:14
set appId@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:292:14
_update@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:228:9
_setup@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:202:14
_init@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:74:14
vfunc_activate@resource:///com/github/tchx84/Flatseal/js/application.js:78:28
main@resource:///com/github/tchx84/Flatseal/js/main.js:34:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/app/bin/com.github.tchx84.Flatseal:9:17
```

I'm on Arch Linux using Sway 1.6.

**Comment by tchx84** [comment]
Hey @emanuelserpa ,

Can you run the following command and share the results here?

```
$ flatpak permissions | grep -v document | grep -v desktop
```

So I can get a better idea of how to reproduce this.

**Comment by emanuelserpa** [comment]
> Hey @emanuelserpa ,
> 
> Can you run the following command and share the results here?
> 
> ```
> $ flatpak permissions | grep -v document | grep -v desktop
> ```
> 
> So I can get a better idea of how to reproduce this.

Looks like is a problem with my flatpak system.

```
$ flatpak permissions | grep -v document | grep -v desktop
error: Message recipient disconnected from message bus without replying
````

So, I looked what journalctl was giving me and seems like the `xdg-permission-store` is breaking:

```
jun 07 21:21:01 cutepad xdg-permission-store[2945]: error: **
jun 07 21:21:01 cutepad xdg-permission-store[2945]: GLib:ERROR:../glib/glib/gvariant-serialiser.c:1367:g_variant_serialised_n_children: code should not be reached
jun 07 21:21:01 cutepad xdg-permission-store[2945]: Bail out! GLib:ERROR:../glib/glib/gvariant-serialiser.c:1367:g_variant_serialised_n_children: code should not be reached
jun 07 21:21:01 cutepad kernel: audit: type=1701 audit(1623111661.086:190): auid=1000 uid=1000 gid=1000 ses=4 pid=2945 comm="xdg-permission-" exe="/usr/lib/xdg-permission-store" sig=6 res=1
jun 07 21:21:01 cutepad audit[2945]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=4 pid=2945 comm="xdg-permission-" exe="/usr/lib/xdg-permission-store" sig=6 res=1
jun 07 21:21:01 cutepad systemd[1462]: xdg-permission-store.service: Main process exited, code=dumped, status=6/ABRT
jun 07 21:21:01 cutepad systemd[1462]: xdg-permission-store.service: Failed with result 'core-dump'.
jun 07 21:21:01 cutepad polkitd[751]: Unregistered Authentication Agent for unix-process:2941:19962 (system bus name :1.124, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale>
```

Looks like very similar to: https://github.com/flatpak/flatpak/issues/3759#issuecomment-696498417

So, I think this is not related with Flatseal, but I don't know what to do now. 🤔

**Comment by tchx84** [comment]
You can test #307 and see if helps... ?

**Comment by emanuelserpa** [comment]
Works now.

Tried to change some permissions in sandboxed apps and apparently works.

![image](https://user-images.githubusercontent.com/934124/121108220-bf891a80-c7df-11eb-9a82-ca6b8883b918.png)

Thanks!

**Comment by tchx84** [comment]
> Works now.

So, it seems you uncovered an underlying issue with the permission store that affect both `flatpak permissions` and Flatseal. Maybe you should consider report the issue to your distribution (and check with upstream https://github.com/flatpak/xdg-desktop-portal.)

Just one more request, can you screenshot the Portals section at the bottom? I just want to make sure this is behaving properly (these options should be disabled / grayed out).

**Comment by emanuelserpa** [comment]
> > Works now.
> 
> So, it seems you uncovered an underlying issue with the permission store that affect both `flatpak permissions` and Flatseal. Maybe you should consider report the issue to your distribution (and check with upstream https://github.com/flatpak/xdg-desktop-portal.)
> 
> Just one more request, can you screenshot the Portals section at the bottom? I just want to make sure this is behaving properly (these options should be disabled / grayed out).

![image](https://user-images.githubusercontent.com/934124/121252886-e9dde500-c87e-11eb-834f-cc5bf8e8c080.png)

I'll try to open a thread on the arch linux forums about that later. But would be cool to know if this is a general Arch Linux issue.
