### ISSUE TITLE
Does not start: Failed to register: Timeout was reached

### ISSUE THREAD

**Issue by sedrubal** [tchx84/Flatseal#310]
When I run flatseal using `flatpak run com.github.tchx84.Flatseal` it seems that flatseal does not start or at least no GUI is shown. The context is running as I can enter it using `flatpak enter`. This is the output of `flatpak run` output:

```sh
$ flatpak run com.github.tchx84.Flatseal

(com.github.tchx84.Flatseal:2): Gtk-WARNING **: 10:38:13.855: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 10:38:13.856: Failed to load module "canberra-gtk-module"
Failed to register: Timeout was reached
```

#### Some info:

```sh
$ flatpak info com.github.tchx84.Flatseal

Flatseal - Manage Flatpak permissions

          ID: com.github.tchx84.Flatseal
         Ref: app/com.github.tchx84.Flatseal/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.7.4
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 2,6 MB
     Runtime: org.gnome.Platform/x86_64/40
         Sdk: org.gnome.Sdk/x86_64/40

      Commit: 17909fe70911ac2db1907a653c21d35de7d36c15c5f7d3a383358fee12f85fe2
      Parent: 4057c5f9337053c554f8ea75b10ffcd124d676c6682306f784973dab85140f1f
     Subject: Update to v1.7.4 (c745a459)
        Date: 2021-06-11 20:55:28 +0000
```
```sh
$ flatpak --version
Flatpak 1.11.1
```

I'm using Arch Linux.

**Comment by tchx84** [comment]
hey @sedrubal , is there any other information you can provide? e.g. desktop environment details.

Or even better, if you can provide the basic information so I can try to reproduce your system on a VM.

**Comment by sedrubal** [comment]
Yes, I'm sorry: I'm using plasma desktop with X11.

I am not sure what the problem was but after a reboot it seems to work again. I'm sorry for opening this issue 👼🏾

**Comment by tchx84** [comment]
> Yes, I'm sorry: I'm using plasma desktop with X11.
> 
> I am not sure what the problem was but after a reboot it seems to work again. I'm sorry for opening this issue 👼🏾

great! :laughing:
