### ISSUE TITLE
Manually added Flatpak "system level" permissions through CLI do not show up in Flatseal

### ISSUE THREAD

**Issue by Perkolator** [tchx84/Flatseal#312]
If a permission is added through Flatpak CLI as a "user level" permission (example below), Flatseal shows the new permission in the GUI.

`flatpak override fr.handbrake.ghb --user --filesystem=xdg-config/gtk-3.0`

But, if the same permission is added as a "system level" permission (sudo needed, example below, `--system` is the default), Flatseal does not show the new permission in the GUI (and obviously does not enable the "reset" function/button either).

`sudo flatpak override fr.handbrake.ghb --filesystem=xdg-config/gtk-3.0`

Is this intended behavior of Flatseal? Should it also show "system level" added permissions?

The "system level" permissions obviously work for every user, so in the case there are those permissions and Flatseal doesn't show them, this might lead to confusion for the Flatseal user.

**Comment by tchx84** [comment]
It is intended behavior.

My current stand is that Flatseal has already enough "power" to be useful, and I rather avoid messing with directories beyond the current user's control.

**Comment by Perkolator** [comment]
Fair enough. I suggest that you tell about this shortcoming on github/flatpak/documentation pages.

**Comment by tchx84** [comment]
> Fair enough. I suggest that you tell about this shortcoming on github/flatpak/documentation pages.

PRs are not only welcome, but encouraged :)

See https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md

**Comment by Perkolator** [comment]
Sorry, I kind of lost interest for Flatseal (uninstalled). Also I don't have much more time (already spent some time figuring and testing this out), and unfortunately I don't think my English is good enough to write documentation to others. :(

But, maybe it could be simple as (with better wording): _Flatpaks allow to set permissions on user and system level. Flatseal only shows and manages user level Flatpak permissions_.

**Comment by tchx84** [comment]
No worries, thanks!
