### ISSUE TITLE
Flatseal shows valid filesystem settings as invalid

### ISSUE THREAD

**Issue by xscd** [tchx84/Flatseal#314]
Telegram has recently added a setting like ```!~/.TelegramDesktop``` but Flatseal shows it as an invalid option where it should be something valid. 

Also see: https://github.com/flathub/org.telegram.desktop/issues/310#issuecomment-911491628

![Screenshot from 2021-09-02 12-54-35](https://user-images.githubusercontent.com/46658470/131829827-1445f0cf-ef66-42ea-82f5-483119a2034f.png)

**Comment by gasinvein** [comment]
I'm not a UI expert by any means, but maybe Flatseal should show "Other files" as read-only rows with switches (like the well-known entries above) instead of the mutable list of text fields? This way it could show `~/.TelegramDesktop` filesystem entry as already disabled.

**Comment by tchx84** [comment]
I am pretty sure I covered this case already, so it might be a regression... in any case, what really matters is whether Flatseal is generating the proper overrides or not, do you mind checking `~/.local/share/flatpak/overrides/` ?

EDIT: I wasn't clear enough, that "invalid" icon is just UI warning, it should still take it in.

**Comment by xscd** [comment]
I have some files in ```~/.local/share/flatpak/overrides/``` but I have also changed some other settings. I do think this is just a visual bug everything else works as expected.

**Comment by gasinvein** [comment]
What happens if you remove such builtin inverse permission via Flatseal? Will it become double-inverse (i.e. starting with `!!` in the overrides file), or it become actually allowed (i.e. `!` removed in overrides)?

**Comment by tchx84** [comment]
> What happens if you remove such builtin inverse permission via Flatseal? Will it become double-inverse (i.e. starting with `!!` in the overrides file), or it become actually allowed (i.e. `!` removed in overrides)?

Try it :)

EDIT: also try `!!`
