### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by Acromonkey** [tchx84/Flatseal#33]
Flatseal version: 1.3.0
OS: Fedora 31

Problem: Flatseal does not save my changes. If a reassign permissions for a program, and then go to another program and then back to the original program, all my changes are dismissed.

**Comment by tchx84** [comment]
I suspect this is the issue I fixed in https://github.com/tchx84/Flatseal/commit/18a81b12c852a94c1d4c8b14563ec795a2cff0dd

Please update Flatseal to the latest version. If for whatever reason you can't update. Doing `mkdir ~/.local/share/flatpak/overrides` should fix it for you.

**Comment by Acromonkey** [comment]
Indeed, your fix works. I am using the Flatpak version of Flatseal, and there it seems not to be updated yet. Thank you very much, I am clsing this issue.

**Comment by tchx84** [comment]
Weird, I maintain the flathub version of Flatseal as well... is it from flathub or somewhere else? If it's from somewhere else I recommend to file a bug report to them so they can update it.

You will help a lot of other people if you do ;)

**Comment by Acromonkey** [comment]
Well, it is from Flathub (dl.flathub.org) and in version 1.4.2 on my computer. Last actualisation was on 08.02.2020.
