### ISSUE TITLE
Navigation with keyboard easier

### ISSUE THREAD

**Issue by juxuanu** [tchx84/Flatseal#344]
Right now, on startup, Flatseal selects the first app. From there, the fastest way to get to the app you are interested in is:

- <kbd>Ctrl</kbd> + <kbd>F</kbd>
- Write name
- Click with the mouse

What about, when on the search box, you can press <kbd>Enter</kbd> to select the top result, so you can get right into the app you wanted to?

**Comment by juxuanu** [comment]
After that, the list of apps could go back to its initial state (pre-search) if only one app has been found.

**Comment by tchx84** [comment]
good idea, let me see how to do this..

**Comment by tchx84** [comment]
Forgot to mention, you can also browse results with the DOWN and UP keys, so there _is_ a way to select search results with the keyboard.

Still, I implemented the activation (ENTER key) idea ;)
