### ISSUE TITLE
Flatseal shows wrong permissions

### ISSUE THREAD

**Issue by rusty-snake** [tchx84/Flatseal#351]
I've `global` overrides where I fix common faults like `filesystem=home;` disable X11.
Unfortunately flatseal then shows wrong (not the actual) permissions for my apps and makes it harder to re-enable X11 for example.

While #210 is about adding editing support for `global`, this ticket only deals with the fact that global overrides are taken into account when reading app permissions (like `flatpak info -M <APP>`).

**Comment by tchx84** [comment]
To clarify how Flatseal works currently; it completely ignores global overrides. So it will only display per-app overrides, it won't "mess" with your global or anything like that (it can't, even if it wanted).

Now, taking global overrides into account should be feasible but, can't promise anything in the short term.

**Comment by tchx84** [comment]
@rusty-snake it took a while, but it's done :)

**Comment by marisolaguilera742-ctrl** [comment]
> I've `global` overrides where I fix common faults like `filesystem=home;` disable X11.
> Unfortunately flatseal then shows wrong (not the actual) permissions for my apps and makes it harder to re-enable X11 for example.
> 
> While #210 is about adding editing support for `global`, this ticket only deals with the fact that global overrides are taken into account when reading app permissions (like `flatpak info -M <APP>`).
