### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by WineBottles** [tchx84/Flatseal#357]
Current version 1.7.4

When using Flatseal on a computer that is using dark mode it is blinding upon launching Flatseal.

Please add a dark mode option.

**Comment by tchx84** [comment]
Hey @Githob2021 , can you clarify what you mean by `It is blinding upon launching Flatseal` ?

Check this out https://twitter.com/tchx84/status/1393714321125949442

**Comment by rusty-snake** [comment]
How did you enabled the dark mode in your system?

Workaround:
```console
$ mkdir -p ~/.var/app/com.github.tchx84.Flatseal/config/gtk-3.0 && cat >~/.var/app/com.github.tchx84.Flatseal/config/gtk-3.0/settings.ini <<EOF
[Settings]
gtk-application-prefer-dark-theme=1
EOF
```

or

```console
$ flatpak override --user --env=GTK_THEME=Adwaita:dark com.github.tchx84.Flatseal
```

**Comment by rusty-snake** [comment]
Flatseal after setting `gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark`:

![Screenshot_2021-11-02_12-41-47-fs8](https://user-images.githubusercontent.com/41237666/139848537-231b453a-6cb2-4646-a331-2d82c40d29ed.png)

**Comment by q7nm** [comment]
Are you installed `runtime/org.gtk.Gtk3theme.Adwaita-dark/x86_64/3.22`?

**Comment by rusty-snake** [comment]
:+1: This makes the gsettings method work too (both methods from https://github.com/tchx84/Flatseal/issues/357#issuecomment-957456546 work without installing additional runtimes).

**Comment by WineBottles** [comment]
> Hey @Githob2021 , can you clarify what you mean by `It is blinding upon launching Flatseal` ?
> 
> Check this out https://twitter.com/tchx84/status/1393714321125949442

Just in general that the application is very very bright. I use KDE dark theme, dark theme in Firefox, dark Joplin. But when I launch Flatseal it's like the sun is on my monitor.

**Comment by WineBottles** [comment]
> Flatseal after setting `gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark`:
> 
> ![Screenshot_2021-11-02_12-41-47-fs8](https://user-images.githubusercontent.com/41237666/139848537-231b453a-6cb2-4646-a331-2d82c40d29ed.png)

I meant the entire UI for Flatseal would ideally be dark mode, not just that on section of toggles.

**Comment by rusty-snake** [comment]
>  I use KDE dark theme, dark theme in Firefox, dark Joplin. But when I launch Flatseal it's like the sun is on my monitor.

Did you enabled a dark theme for GTK(3)? If so how did you? Do you have other GTK Apps with working dark mode?

**Comment by rusty-snake** [comment]
> I meant the entire UI for Flatseal would ideally be dark mode, not just that on section of toggles.

I got that. This was more a "the gsettings method does not work for me" post (I mean black font on dark background). Anyway if you read the following comment(s).

**Comment by WineBottles** [comment]
> > I use KDE dark theme, dark theme in Firefox, dark Joplin. But when I launch Flatseal it's like the sun is on my monitor.
> 
> Did you enabled a dark theme for GTK(3)? If so how did you? Do you have other GTK Apps with working dark mode?

I just did flatpak override --user --env=GTK_THEME=Adwaita:dark com.github.tchx84.Flatseal and it looks amazing. Thank you. This is exactly what I wanted. I don't use any other GTK based stuff.

**Comment by ACR-Jeff** [comment]
> ```
> flatpak override --user --env=GTK_THEME=Adwaita:dark com.github.tchx84.Flatseal
> ```

Nothing else I tried would work, But this still works today, Thank you
