### ISSUE TITLE
Add additional sorting options

### ISSUE THREAD

**Issue by WineBottles** [tchx84/Flatseal#358]
Current version: 1.7.4

It would be beneficial to have additional sorting options (package name A-Z, package name Z-A, date installed, source A-Z, source Z-A).

Currently when I am searching for a package in Flatseal I need to scan up and down trying to find the package I am looking for.

This becomes troublesome when there are a lot of packages installed (example I have 40+)

**Comment by rusty-snake** [comment]
> Currently when I am searching for a package in Flatseal I need to scan up and down trying to find the package I am looking for.
> This becomes troublesome when there are a lot of packages installed (example I have 40+)

![Screenshot_2021-11-02_12-20-31-fs8](https://user-images.githubusercontent.com/41237666/139845030-acc0ea6f-a022-45c5-9cc5-01414f911d2b.png)

**Comment by WineBottles** [comment]
> > Currently when I am searching for a package in Flatseal I need to scan up and down trying to find the package I am looking for.
> > This becomes troublesome when there are a lot of packages installed (example I have 40+)
> 
> ![Screenshot_2021-11-02_12-20-31-fs8](https://user-images.githubusercontent.com/41237666/139845030-acc0ea6f-a022-45c5-9cc5-01414f911d2b.png)

Thank you.

That's a solution to scanning visually, but a sorting option would still be nice to have consistency
