### ISSUE TITLE
Add ability to specify command launch arguments

### ISSUE THREAD

**Issue by juxuanu** [tchx84/Flatseal#360]
I am not entirely sure that:

- this is something that you want to add to this app; at the end of the day, its objective is to manage permissions, but since environmental variables were added, I thought this might be OK as well,
- this is technically feasable.

My idea is to add a new text field for command line arguments. Example use case:

Steam recently added DMABUF screensharing, but it requires to launch steam with `-pipewire-dmabuf`. One could modify the .desktop file, but it would be way cleaner to just add that in Flatseal.

As an extra, I wonder if default launch flags can be detected, if any, as default option.

**Comment by tchx84** [comment]
Don't get me wrong, I think that's a useful idea, but for a different tool.

If there's isn't a way of doing this through overrides or a portal, it simply does not belong in Flatseal.
