### ISSUE TITLE
Not detecting apps in custom installation

### ISSUE THREAD

**Issue by techmagus** [tchx84/Flatseal#381]
Issue: Not detecting apps in custom installation

Steps:
1. Install any app: flatpak --installation=example install anyapp
2. Install flatseal: flatpak --installation=example install flathub com.github.tchx84.Flatseal
3. Run

Flatseal will run but will not show any app.

**Comment by tchx84** [comment]
Hey @techmagus , have you checked the docs?

See https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md#enable-custom-installations

**Comment by techmagus** [comment]
> Hey @techmagus , have you checked the docs?
> 
> See https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md#enable-custom-installations

Yeah. But I took a second look just now and figured out, I was using the incorrect path.

Closing then. Thank you! Shalom!
