### ISSUE TITLE
Unify filesystem options under the same viewer

### ISSUE THREAD

**Issue by tchx84** [tchx84/Flatseal#39]
Hey @bertob, 

I need your feedback once more for some design I am playing with :)

![Screenshot from 2020-02-25 20-36-39](https://user-images.githubusercontent.com/481418/75297641-2531dd00-580f-11ea-8d78-2dc932c72125.png)

**The goal is:** To get rid of the redundant home and host switch options, and uniify these under the filesystems viewer at the bottom.

**The reason is:** I want to reduce as much as possible the visual clutter, and don't have 2 ways of doing the same thing.

**Prototype:** (see screenshot above)

1. Add an information icon at the start of each path. When hovered, it will display a tooltip with explanatory text, e.g. `host:rw` "Can read and write all system directories", or `home:ro` "Can read all of the user's personal files". The widget already has the information to generate that kind of string.

2. Once we provide more information about each of these "token" directories (home, host, xdg-downloads, etc), I can get rid of these redundant switch options, without leaving the user with less information than before.

3. Extra, since I already implemented style classes for each access mode, I can color these info icons (like in the screenshot), a color for read-only and a different color for write access.

What do you think?

**Comment by tchx84** [comment]
> 3. Extra, since I already implemented style classes for each access mode, I can color these info icons (like in the screenshot), a color for read-only and a different color for write access.

Regarding this, it doesn't necessarily need to be color, can be any other css property, btw. e.g. making write access bold type (just saying).

**Comment by bertob** [comment]
Sorry about the belated answer.

I agree that it makes sense to group all file system permissions, but I'm not sure it's better to have host and home be exactly the same as random paths. It seems to me that for those common ones a on/off switch would make more sense than having them be removable.

About the readonly/readwrite icon, I'm not sure this works. Instead of the icon and the :ro type suffixes, what about a button that toggles the state between readwrite and read-only?

Also, I'd go with some more distinct icons for readonly and readwrite. Readonly could be something like `eye-open-negative-filled`, and readwrite could be `document-edit`. I'm not sure we need different styling necessarily.

**Comment by tchx84** [comment]
> Sorry about the belated answer.
> 
> I agree that it makes sense to group all file system permissions, but I'm not sure it's better to have host and home be exactly the same as random paths. It seems to me that for those common ones a on/off switch would make more sense than having them be removable.
> 

I see that as well, but the thing is there are plenty of other common values and, more importantly, these are not boolean values.

> About the readonly/readwrite icon, I'm not sure this works. Instead of the icon and the :ro type suffixes, what about a button that toggles the state between readwrite and read-only?
> 

These "modes" are not boolean. There are 3.5 possible values (`:ro`, `:create` and `:rw` and the absence of suffix, which means it's `:rw`).

So values like `host:ro` and `home:rw` often end up in the filesystem at the bottom section anyway.

> Also, I'd go with some more distinct icons for readonly and readwrite. Readonly could be something like `eye-open-negative-filled`, and readwrite could be `document-edit`. I'm not sure we need different styling necessarily.

What I ended up doing (ignore the grouping of permissions, I am just playing with that):

![Screenshot from 2020-03-01 17-39-29](https://user-images.githubusercontent.com/481418/75633482-d657bf00-5be3-11ea-996a-7acb17b4b2c1.png)

There's only one information icon, which presents a tooltip with a human-readable description of each filesystem permissions, e.g. for a 'host' value, the tooltip displays `Can modify and read: all system files`.

The icons you mentioned look interesting, ill experiment with those.

![Screenshot from 2020-03-01 17-39-48](https://user-images.githubusercontent.com/481418/75633564-9e9d4700-5be4-11ea-8ebb-e0f345296493.png)

Currently, the icon and it's color (and the tooltip) changes when non-valid options is typed in. But is a simple warning.

**Comment by tchx84** [comment]
I reverted the removal of the switch versions with the permissions grouping. since It's way less cluttered now.

It might serve a more gradual transition to the new / enhanced filesystems viewer as well.
