### ISSUE TITLE
Flatseal unusable with dark theme enabled in Cinnamon

### ISSUE THREAD

**Issue by VorpalBlade** [tchx84/Flatseal#391]
Two issues here:
* Dark theme only partially applied.
* Black text on dark background is unreadable

![image](https://user-images.githubusercontent.com/3315306/148575847-6f9f75b0-79ae-450f-b62c-813880a32510.png)

I installed flatseal from flathub: 
```console
$ flatpak install flatseal
Looking for matches…
Found ref ‘app/com.github.tchx84.Flatseal/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: y
Required runtime for com.github.tchx84.Flatseal/x86_64/stable (runtime/org.gnome.Platform/x86_64/41) found in remote flathub
Do you want to install it? [Y/n]: y

com.github.tchx84.Flatseal permissions:
    ipc    fallback-x11    wayland    x11    dri    file access [1]    dbus access [2]

    [1] /var/lib/flatpak/app:ro, xdg-data/flatpak/app:ro, xdg-data/flatpak/overrides:create
    [2] org.freedesktop.impl.portal.PermissionStore, org.gnome.Software


        ID                                   Branch          Op          Remote           Download
 1. [✓] org.gnome.Platform.Locale            41              i           flathub          231,6 kB / 336,5 MB
 2. [✓] org.gnome.Platform                   41              i           flathub          173,3 MB / 289,3 MB
 3. [✓] com.github.tchx84.Flatseal           stable          i           flathub          435,7 kB / 683,8 kB

Installation complete.
```

Then I started it from the Cinnamon launcher menu.

System info:
* Arch Linux (rolling release distro)
* Cinnamon (5.0.7-5)

Theme settings in Cinnamon:
![image](https://user-images.githubusercontent.com/3315306/148576194-0ed1588d-ca4d-441d-b583-0dd15ced4c9a.png)

Is there any other information that would be helpful to you?

**Comment by q7nm** [comment]
Do you have `org.gtk.Gtk3theme.Adwaita-dark` installed?

**Comment by VorpalBlade** [comment]
No I didn't! Installing that helped. Thanks!

Maybe it should be added to the README, or a FAQ or something? Arguably it is a flatpak bug that it doesn't tell you that it needs to install it when you have that as your system theme. I'm also confused as to why other flatpaks just flat out ignores the system theme instead (i.e. Fedora Media Writer, spotify does it's own thing anyway)

**Comment by tchx84** [comment]
hey @VorpalBlade !

Feel free to send a PR for the offline docs see https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md

Under tips and tricks would be fine.
