### ISSUE TITLE
Support applications on external storage devices

### ISSUE THREAD

**Issue by Doomsdayrs** [tchx84/Flatseal#392]
## Steps:
1. Follow https://docs.flatpak.org/en/latest/tips-and-tricks.html#adding-a-custom-installation
2. Open Flatseal to edit the permissions.
3. Note that the app is not in the list

It would be very nice if external storage locations were read.

**Comment by tchx84** [comment]
hey @Doomsdayrs ,

Check this out https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md#enable-custom-installations
