### ISSUE TITLE
Add privacy permissions

### ISSUE THREAD

**Issue by m3thm4th** [tchx84/Flatseal#393]
Add options to hide or spoof hardware properties, OS, clipboard, microphone, camera, etc. to applications, like [XPrivacyLua](https://github.com/M66B/XPrivacyLua) does on Android. A lot of proprietary apps are packaged as Flatpaks and privacy cannot be guaranteed on those.

**Comment by q7nm** [comment]
It's not Flatseal issue, it's flatpak issue.

**Comment by tchx84** [comment]
Flatseal can only cover what Flatpak allows.
