### ISSUE TITLE
Missing .local/share/flatpak/overrides

### ISSUE THREAD

**Issue by egore** [tchx84/Flatseal#394]
When the directory ~/.local/share/flatpak/overrides does not exist, the UI will appear to set values, but not create the override file. The error on the console is:

```
(com.github.tchx84.Flatseal:7868): Gjs-CRITICAL **: 00:01:27.962: JS ERROR: GLib.FileError: Failed to create file ?/home/xxx/.local/share/flatpak/overrides/com.github.qarmin.czkawka.S1D5F1?: No such file or directory
_saveOverrides@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:182:21
_updateModels@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:222:14
main@resource:///com/github/tchx84/Flatseal/js/main.js:34:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/usr/bin/com.github.tchx84.Flatseal:9:17


(com.github.tchx84.Flatseal:7868): GLib-CRITICAL **: 00:01:28.459: Source ID 1054 was not found when attempting to remove it
```

A workaround is to create the directory manually. Please add a "mkdir -p" before creating the files

**Comment by tchx84** [comment]
hey @egore , can you provide some context? e.g. what version of Flatseal, how did you install it, etc.

**Comment by egore** [comment]
Hi @tchx84, this is flatseal 1.7.4-1 on Arch Linux. It should work on every other distribution as well by following these steps:

    rm -rf ~/.local/share/flatpak/overrides
    flatseal

Setting any override will now cause the above error. I also tested this with the master branch on git and verified the error still happens.

**Comment by tchx84** [comment]
ugh, yeah, this could be fixed by flatseal itself... but, for the time being, I highly recommend to use the Flatpak version of Flatseal which does handle this issue.

**Comment by egore** [comment]
Oh nice, great hint. The version from flathub.org works great.

**Comment by WhyNotHugo** [comment]
The Flatpak's manifest is configured to create the directory if it doesn't exist (that's why that one works).

When using a native package, the directory needs to be created for now. Creating the directory [if it does not exist] before saving files should fix this.

Note that the manifest should still keep the `:create` even if this tweak is implemented.

**Comment by tchx84** [comment]
> When using a native package, the directory needs to be created for now. Creating the directory [if it does not exist] before saving files should fix this.

This is correct, it will get fixed ASAP.

**Comment by WhyNotHugo** [comment]
Thanks!
