### ISSUE TITLE
Filesystem suffix "ro" is not applicable for --nofilesystem

### ISSUE THREAD

**Issue by remyabel2** [tchx84/Flatseal#396]
If an app has a filesystem permission like `xdg-downloads:ro`, the override will look something like `!xdg-downloads:ro`. If you then run `flatpak list`, you get the error seen in the title. Not sure if this is a Flatseal or Flatpak problem, but wanted to report it here first. I guess my secondary question is, does this mean the override is useless or can I ignore the diagnostic?

**Comment by q7nm** [comment]
It should be reopened.
