### ISSUE TITLE
Remove `:ro` suffix when overriding existing read-only permissions 

### ISSUE THREAD

**Issue by SaswatPadhi** [tchx84/Flatseal#402]
Hello,

First of all, thanks for this excellent app! Very helpful to spot and overly broad permissions in many Flatpak apps.

I am running Flatseal 1.7.5 from Flatpak. I noticed that when removing permission to existing paths with read-only (`:ro`) access, Flatseal preserves the `:ro` suffix. For example, when removing `home:ro` permission for an app in Flatseal, `!home:ro` is added in its override file.

For instance, you can try removing `home:ro` permission from `fi.skyjake.Lagrange` or `org.telegram.desktop`. The `flatpak` CLI will emit a warning:

```
$ flatpak list
F: Filesystem suffix "ro" is not applicable for --nofilesystem
```

Removing the `:ro` suffix manually from the override file suppresses this warning.

**Comment by rusty-snake** [comment]
#396

**Comment by tchx84** [comment]
hmm, ill see what's going on..

**Comment by tchx84** [comment]
@SaswatPadhi can you specify your environment details? e.g. Flatpak version.

**Comment by SaswatPadhi** [comment]
Hi @tchx84, sure, thanks for looking into this.

I'm running Flatpak 1.12.6 and `flatpak info com.github.tchx84.Flatseal` prints:

```

Flatseal - Manage Flatpak permissions

          ID: com.github.tchx84.Flatseal
         Ref: app/com.github.tchx84.Flatseal/aarch64/stable
        Arch: aarch64
      Branch: stable
     Version: 1.7.5
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 2.6 MB
     Runtime: org.gnome.Platform/aarch64/41
         Sdk: org.gnome.Sdk/aarch64/41

      Commit: 200608ca4f8a9b9caed6f3a9aa0bc1b98dfd8f9ef9e27f84b18724fd67ce5323
      Parent: f65ba447252970c21f7eaa315b4a98923755bbc9bce34133748abf626757cb59
     Subject: Update to v1.7.5 (9156b312)
        Date: 2021-11-19 21:10:57 +0000
```
