### ISSUE TITLE
Some changed settings are not highlighted (no reset button)

### ISSUE THREAD

**Issue by nekohayo** [tchx84/Flatseal#405]
Issue #30 brought a reset button (I think) to indicate settings that have been changed (?), such as "can run in the background", "can send notifications", etc., but not all seem to be covered by that. For example if I go turn off `socket=pulseaudio` or `filesystem=host` for an app in flatseal, there is no visual indication that _these_ particular settings were changed, only the global Reset button is present, which doesn't help me remind myself what was actually changed the last time I used it.

**Comment by tchx84** [comment]
hey @nekohayo , this is fixed now master, ill release soon.
