### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Doomsdayrs** [tchx84/Flatseal#407]
So, Heroic does not show up in app

I do not know what else to say

**Comment by Doomsdayrs** [comment]
Alright, Strange situation. It does not show up if installed on system, but if installed on user it shows

**Comment by tchx84** [comment]
is your system installation under a custom installation path?

**Comment by tchx84** [comment]
@Doomsdayrs I am closing this for now, please re-open if you get the time to provide more information. I tried installing an app to the system installation and I can see it on Flatseal.
