### ISSUE TITLE
Removing a filesystem create permission incorrectly leaves :create at the end of the negation

### ISSUE THREAD

**Issue by TiZ-HugLife** [tchx84/Flatseal#413]
Hi there. Super thankful for this tool, have been using it in pretty much all of my DEs. It even looks and works fine in Plasma.

So there's this app, Zoom. Its [Flathub manifest](https://github.com/flathub/us.zoom.Zoom/blob/master/us.zoom.Zoom.json#L18) requests a default permission to create `~/Documents/Zoom`, which is horrifically bad and absolute anathema. Thankfully, Flatpak's permission model means I can revoke that permission. So I use Flatseal, and revoke that permission I do. However, after I do that, whenever I run a flatpak application in a terminal...

```
❯ flatpak run --command=true us.zoom.Zoom
F: Filesystem suffix "create" is not applicable for --nofilesystem
```

This makes sense when you think about it: a filesystem access negation doesn't need a suffix because you're denying access to it entirely. It can be fixed manually by editing the override file for the app in `$XDG_DATA_HOME/flatpak/overrides`. Just take off the `:create` at the end here:

```
[Context]
filesystems=!~/Documents/Zoom:create
```

So if Flatseal removes a filesystem permission that the app is granted by its manifest, it should not include a suffix for that negation.

**Comment by rusty-snake** [comment]
Related: #402

**Comment by tchx84** [comment]
Fixed on master already, will release soon.

**Comment by rusty-snake** [comment]
Flatseal 1.8.0 is out, we can close here.

**Comment by tchx84** [comment]
thank you @rusty-snake
