### ISSUE TITLE
Feature Request: Setting Descriptions

### ISSUE THREAD

**Issue by trymeouteh** [tchx84/Flatseal#414]
Please add a easy to understand description with every setting for every Flatpak for non-tech savvy users to understand.

FlatSeal is a great tool for making Flatpaks more private and secure and by adding more details on what each setting does, anyone can use FlatSeal!

**Comment by tchx84** [comment]
hey @trymeouteh , although I understand you refer to a instantly accessible description, I wonder if you have found the offline documentation any useful?

**Comment by rusty-snake** [comment]
Related: #383

**Comment by trymeouteh** [comment]
This is actually related to #383. The documentation is also hidden away a bit and I think having a short description on every setting with a link to the full details to the documentation would be best.
