### ISSUE TITLE
Hiding applications not meant to be started manually

### ISSUE THREAD

**Issue by Ricky-Tigg** [tchx84/Flatseal#417]
**com.github.tchx84.Flatseal .v:** 1.7.5

Hello. Among the applications reported by Flatseal there may be some that are not meant to be started manually; attempting to do so would produce errors; _illustration_:

```
$ flatpak run org.flathub.flatpak-external-data-checker
usage: flatpak-external-data-checker [-h] (...) manifest
flatpak-external-data-checker: error: the following arguments are required: manifest
```
Setting permission for such applications would not make sense. Therefore it would be worth not to report them.

**Comment by q7nm** [comment]
There's a meaning. For example, give access to selected directories.

**Comment by Ricky-Tigg** [comment]
Closing if you feel or decide there is nothing there to improve of fix.
