### ISSUE TITLE
Port Flatseal to use the Gnome 42 Platform 

### ISSUE THREAD

**Issue by MikuOcta** [tchx84/Flatseal#418]
It would be nice for the app to be ported to Platform 42 (and possibly to libadwaita) for more consistency with the other apps

**Comment by rusty-snake** [comment]
https://github.com/tchx84/Flatseal/blob/1b9774d92ed54accd2f4e7c84bf61d0f9d276142/com.github.tchx84.Flatseal.json#L3-L4

**Comment by MikuOcta** [comment]
but what about libadwaita port? Libadwaita will give a fresh look and a performance boost

**Comment by tchx84** [comment]
Maybe rename the request to "port to gtk4 / libadwaita" ? re. that It won't happen for the next release, but I really want to make it happen this year (intentions).

**Comment by ghost** [comment]
> https://github.com/tchx84/Flatseal/blob/1b9774d92ed54accd2f4e7c84bf61d0f9d276142/com.github.tchx84.Flatseal.json#L3-L4

And when this commit will hit flathub ? (not a troll i do not know the release time).

**Comment by ghost** [comment]
@tchx84 i ask again to see if there is any news ? because your app is the last one i use to be on 41 all other have switched to 42

**Comment by rusty-snake** [comment]
Flatseal 1.8.0 with org.gnome.Platform//42 is out.

**Comment by tchx84** [comment]
I am closing this since this seems to be more about moving to 42 runtime. Let's leave the port of libadwaita in a new issue.
