### ISSUE TITLE
Group permissions

### ISSUE THREAD

**Issue by bertob** [tchx84/Flatseal#42]
Currently there are a lot of different permissions in a single list, which can make it hard to find individual ones. Grouping related permissions (e.g. all windowing system ones, all dbus ones, etc.) into groups with a header could help with this.

Within groups I'd also remove the vertical margins between the listbox rows to reduce visual complexity a bit.

**Comment by tchx84** [comment]
I experimented with this today.

Note that having some sort of "conceptual abstraction" on top permissions is a non-goal for me.

I want this to be easier to use than CLI, but I don't to hide existing permissions concepts. Therefore, I grouped these permissions by how Flatpak groups in the first place (shared, sockets, devices, features and filesystems).

![Screenshot from 2020-03-01 19-35-47](https://user-images.githubusercontent.com/481418/75635519-94377900-5bf5-11ea-975c-b03580863a7d.png)

![Screenshot from 2020-03-01 19-46-33](https://user-images.githubusercontent.com/481418/75635526-9e597780-5bf5-11ea-86d7-351791482848.png)

what do you think?

**Comment by bertob** [comment]
Looks good to me
