### ISSUE TITLE
"Reset factory defaults" button

### ISSUE THREAD

**Issue by WhyNotHugo** [tchx84/Flatseal#420]
Sometimes I mess up an application's overrides and need to start again from the original settings. This can be done by deleting the override file, but can't be done via the UI.

How about a button, at the end of the override list labeled `Reset factory default` that does the equivalent of emptying the overrides for each application?

**Comment by rusty-snake** [comment]
Can you explain the difference to the current reset button?
![Screenshot_2022-04-14_20-49-10 png-fs8](https://user-images.githubusercontent.com/41237666/163473030-4fd2deed-aa83-4e1a-9d74-d584403972f4.png)

**Comment by WhyNotHugo** [comment]
Doesn't "Reset" just undo changes done in the current session?

**Comment by rusty-snake** [comment]
I made all change to my overrides with `flatpak override --user` and use flatseal only to view permissions but I can click the reset button to delete the override file.

**Comment by WhyNotHugo** [comment]
Oh... That's handy. Never mind then.
