### ISSUE TITLE
KDevelop icon is missing or broken in Flatseal

### ISSUE THREAD

**Issue by ghtesting2020** [tchx84/Flatseal#422]
Out of the 20 or so apps I have in flatpak for some reason KDevelop only has a broken or missing icon in Flatseal. it is showing a white folded paper with a ! point in a triangle. In KDE Plasma the icon works fine so it seems it is only broken in Flatseal.

URL to flathubs KDevelop: https://flathub.org/apps/details/org.kde.kdevelop

![2](https://user-images.githubusercontent.com/69682350/163825623-ce2648f6-6601-48c3-a4e9-8fdc383a9659.png)

![1](https://user-images.githubusercontent.com/69682350/163825631-e0893d2f-976d-4651-8665-23768eb923c6.png)

**Comment by meisme-dev** [comment]
i have the exact same problem

**Comment by prodrigestivill** [comment]
Same problem with:
https://flathub.org/apps/details/com.authy.Authy

**Comment by ghtesting2020** [comment]
Another flatpak that is missing an icon is Filelight org.kde.filelight
https://flathub.org/apps/details/org.kde.filelight

**Comment by tchx84** [comment]
Thanks for the report, I looked at filelight and kdevelop, and I noticed the same thing...

![Screenshot from 2023-04-20 12-39-54](https://user-images.githubusercontent.com/481418/233432277-b91d507b-2f47-4811-9e31-0cfb5f1a5612.png)

After a bit of testing, I noticed it's not a Flatseal-specific issue. It's likely that some metadata is missing in those applications appdata files.

To show this, I can see the same thing happening with GNOME shell:

![Screenshot from 2023-04-20 12-42-29](https://user-images.githubusercontent.com/481418/233432732-c9c23c33-133e-48d3-a242-73cd785bab2f.png)

I would suggest that you reach out to those applications developers instead.

**Comment by prodrigestivill** [comment]
As a reference the authy has been fixed by changing the desktop file icon name:

```patch
[Desktop Entry]
@@ ... @@
-Icon=com.authy.Authy.png
+Icon=com.authy.Authy
``` 

flathub/com.authy.Authy@7772d648fbb6432e908e4ea2d342606861c87171
