### ISSUE TITLE
Sandboxing seems broken, false sense of security

### ISSUE THREAD

**Issue by ghost** [tchx84/Flatseal#424]
Hello,

Thanks for making this application happen. Your work on creating a flatpak applications manager is much appreciated.

I am not a tech person so if my points are not valid from a technical perspective you might close this ticket without any further action. However from a simple users perspective, I can say: I recently run into a situation which made me doubt whether the sandboxing managed by flatseal is broken or just needs some more work.

This is what I have done and this is what the outcome was:

I went to flathub and installed an application called tellico. I then started flatseal and removed all folder access rights for tellico. However, even after removing all the access rights, tellico was still capable of accessing the hosts whole file system. Now I wonder how reliable your sandboxing really is. 

In any case that gave me the impression that flatseal is offering a false sense of security. Whether only this application is affected or others too I do not know. In any case, this is not supposed to happen as the whole point of using flatpak and flatseal is to sandbox applications so they have only those access rights one wants to grant them.

Could you take a look into this?

Thanks

As for the system I used to test this:
Ubuntu 22.04 + latest software version of flatpak and flatseal as of 29.04.2022.

**Comment by rusty-snake** [comment]
> I went to flathub and installed an application called tellico. I then started flatseal and removed all folder access rights for tellico. However, even after removing all the access rights, tellico was still capable of accessing the hosts whole file system.

If you mean it has full file-system access trough [portals](https://docs.flatpak.org/en/latest/basic-concepts.html#portals) (i.e. only with user-interaction) this isn't an issue.

> Now I wonder how reliable your sandboxing really is.

The sandbox is part of flatpak. Flatseal can only be used to configure permissions.

**Comment by ghost** [comment]
Thanks for some explanation. Indeed, I mean file-system access through tellicos file chooser dialog. Why would that not be an issue? If tellico has access via its own file chooser - how would it not have access by other means? 

I get your second point about the sandbox being part of flatpak. However, If you remove access to files via flatseal but still have access to files via the applications file chooser seems wrong to me.

**Comment by rusty-snake** [comment]
If it can only access files where you clicked open in the file-chooser I see no issue. Every access granted this way has an explicit user interaction and is the intention of the user.

> If tellico has access via its own file chooser

Is it the file-chooser of tellico or of the portal?

**Comment by tchx84** [comment]
@yupqw To elaborate a bit more on what @rusty-snake is saying.

The file chooser you see is _not_ part of the app you're running. The file chooser you see it's part of the operating system. So no, the app can't see all of your files, only the files _you_ select through the file chooser.

That's how portals work.

(a LOT of people gets confused when this happens)

**Comment by ghost** [comment]
@rusty-snake @tchx84 Thanks to both of you for that further explanation! It's indeed quite confusing that the file chooser is a portal while it looks like being part of the application itself. 

But in that case I might close this ticket, as the problem that I tried to describe doesn't seem to be a problem after all.
