### ISSUE TITLE
Can't seems to limit the packaged software filesystem access

### ISSUE THREAD

**Issue by yookoala** [tchx84/Flatseal#428]
I have installed a Flatpak Firefox. And I wanted to limit the filesystem access of it:
![2022-05-06 18-19-51 的螢幕擷圖](https://user-images.githubusercontent.com/91274/167113734-077b592e-09cf-4105-a2e8-6de9965cf191.png)

If I understand it correctly, I have limited Firefox to only access my download folder. That means my personal home folder is off limit to it. I expected if I save a file to my home folder, my actual home folder will not be touched. But when I tried, the saved file appears in my personal home folder.

My system:
- Fedora 35
- Flatpak 1.12.7
- Flatseal 1.7.5 (flathub, system)
- Firefox 100 (flathub, user)

**Comment by rusty-snake** [comment]
Duplicated of #424

**Comment by tchx84** [comment]
@yookoala Please see https://github.com/tchx84/Flatseal/issues/424#issuecomment-1114342700 for an explanation. TLDR; your app can't really access all the FS, the file chooser dialog you see is not part of the app, is part of the OS.
