### ISSUE TITLE
[feature request] Unsetting environment variables

### ISSUE THREAD

**Issue by K4rakara** [tchx84/Flatseal#431]
Global overrides are really helpful, especially during this migration between gtk 3 and 4. I have `flatpak override --user --env=GTK_THEME=Adwaita:dark` so that all flatpak gtk 3 apps don't try to use `adw-gtk3`, the theme I have enabled globally, so that my window decorations are all libadwaita style. Then, for every libadwaita app I have, I have `flatpak override --user <app-id> --unset-env=GTK_THEME`. This works perfectly, but it doesn't show up in Flatseal. Being able to see and modify which environment variables are unset would be really helpful.

**Comment by tchx84** [comment]
I _think_ you will be able to handle on the next release, very soon.

**Comment by tchx84** [comment]
@K4rakara have you tried Flatseal 1.8.0 ? Did it help?

**Comment by K4rakara** [comment]
Oh right! I forgot about this issue still being open. Yeah, the new release takes care of this.
