### ISSUE TITLE
Untranslated strings in Flatseal

### ISSUE THREAD

**Issue by ghost** [tchx84/Flatseal#445]
Hi,

When I look apps permissions these strings seems untranslated: Share,  Socket, Device, Allow, Filesystem, Persistent, Environment, System Bus, Session Bus, Portals.

Is it possible to translate these strings?

![Ekran Görüntüsü - 2022-05-21 01-46-28](https://user-images.githubusercontent.com/6218679/169621820-b524f312-063c-485d-9fa4-cb717c13a001.png)

**Comment by tchx84** [comment]
Hey @libreajans , thanks for reaching out.

These strings are referring to `flatpak override` CLI options, which aren't translated. The idea (at least) is to keep those like that, so people can more easily transition from CLI to Flatseal.

**Comment by ghost** [comment]
Is it possible to seperate them, because Flatseal seems half translated and people asks me why these strings were untranslated.
