### ISSUE TITLE
filesystems=!host:reset; does not reset filesystem permissions in flatseals view

### ISSUE THREAD

**Issue by rusty-snake** [tchx84/Flatseal#449]
### Description

`filesystems=!host:reset;` (in `global` overrides for me, but I also tested when added in per apllication override; added via `flatpak override`) does not reset the filesystem permissions in flatseals view.

### STR

Add `filesystems=!host:reset;`

### Expected behaviour

No filesystem permissions from the app manifest are shown (like `flatpak info -M <APP-ID>`).

### Actual behaviour

All filesystem permissions from the app manifest and `!host:reset` are shown.

**Comment by rusty-snake** [comment]
Because of this bug flateal adds in some cases `filesystem=host` to overrides even if you only edit dbus/sockets/... .

**Comment by tchx84** [comment]
hey @rusty-snake ,

I haven't had to think about what the current UX/UI for this reset option would be... but

> Because of this bug flateal adds in some cases filesystem=host to overrides even if you only edit dbus/sockets/... .

Can you provide a way to reproduce this? So I can at least fix this condition for now.

**Comment by rusty-snake** [comment]
STR AFAICTY:

- Add `filesystems=!host:reset;` to `globals` (`flatpak override --user --filesystem=host:reset`)
- If flatseal is installed as flatpak, allow `filesystems=xdg-data/flatpak/overrides:create;/var/lib/flatpak/app:ro;`
- Open any flatpak with `filesystem=host` in its manifest in flatseal
- Trigger a save, i.e. change any setting.
- Look at `flatpak info -M`

**Comment by tchx84** [comment]
> STR AFAICTY:
> 
> * Add `filesystems=!host:reset;` to `globals` (`flatpak override --user --filesystem=host:reset`)

Are you adding that manually?

My understanding is that `reset` is a special case that can only be used with `--nofilesystem`. 

When I do `flatpak override --user --filesystem=host:reset`, Flatseal itself can no longer access any files and thus can't find any application. So, at least for the `global` override, there's no UX for this.

> * If flatseal is installed as flatpak, allow `filesystems=xdg-data/flatpak/overrides:create;/var/lib/flatpak/app:ro;`
> * Open any flatpak with `filesystem=host` in its manifest in flatseal
> * Trigger a save, i.e. change any setting.
> * Look at `flatpak info -M`

**Comment by rusty-snake** [comment]
Ohh, yes I meant using <code>--<strong>no</strong>filesystem</code>, the `filesystems=!host:reset;` line is correct.
