### ISSUE TITLE
No applications found.

### ISSUE THREAD

**Issue by cdoenges** [tchx84/Flatseal#455]
### Steps to reproduce
1. Install flatpak 1.10.7 on Debian 11 as instructed here https://flatpak.org/setup/Debian. 
2. Install Flatseal 1.8.0 using the flatpakref from https://flathub.org/apps/details/com.github.tchx84.Flatseal. This opens up the "Software" app. Click on "Install".
3. Start Flatseal.

### Expected behavior
Flatseal shows a list of applications.

### Actual behavior
Flatseal shows an empty window with "No applications found.":

![flatseal-no-applications](https://user-images.githubusercontent.com/1794439/173228376-58236f6e-08f7-49ce-8314-029162a40192.png)

### Notes
This https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md#enable-custom-installations appears to imply that Flatseal needs permission to `host-etc`.

It appears that Flatseal does not have this permission:
```
$ flatpak permission-show com.github.tchx84.Flatseal

$
```
So I tried
```
$ sudo flatpak override com.github.tchx84.Flatseal --filesystem=host-etc:ro
```
After restarting Flatseal, this did not change the behavior.

**Comment by rusty-snake** [comment]
> 1. Install flatpak 1.10.7 on Debian 11 as instructed here https://flatpak.org/setup/Debian.
>
> This https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md#enable-custom-installations appears to imply that Flatseal needs permission to host-etc.

If you followed the steps from 1. you have a "normal" installation. Flatseal needs `host-etc` only if you want to use a custom installation.

> Flatseal shows an empty window with "No applications found."

Just to make sure, you have other flatpaks installed, right? edit: Even if you don't have any flatpaks, it should show global-overrides.

**Comment by cdoenges** [comment]
> Just to make sure, you have other flatpaks installed, right? edit: Even if you don't have any flatpaks, it should show global-overrides.

Good one! Yes, I have others installed. And from what is shown in the documentation, Flatseal should at least find itself, no?

**Comment by rusty-snake** [comment]
Yeah, just hit this one myself. It happens if you remove `--filesystem=/var/lib/flatpak/app:ro` permission.

What does `flatpak info -M com.github.tchx84.Flatseal` show?

**Comment by tchx84** [comment]
hey @cdoenges , a few questions:

1. Are you using a custom directory for your flatpak installations?
2. Try the following 

```
$  rm ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal # to reset any previous changes to Flatseal permissions
$  flatpak --user override com.github.tchx84.Flatseal --filesystem=host:ro
```

**Comment by cdoenges** [comment]
> Yeah, just hit this one myself. It happens if you remove `--filesystem=/var/lib/flatpak/app:ro` permission.
> 
> What does `flatpak info -M com.github.tchx84.Flatseal` show?

```
[Context]
shared=ipc;
sockets=x11;wayland;fallback-x11;
devices=dri;
filesystems=host-etc:ro;xdg-data/flatpak/overrides:create;/var/lib/flatpak/app:ro;xdg-data/flatpak/app:ro;

[Session Bus Policy]
org.gnome.Software=talk
org.freedesktop.impl.portal.PermissionStore=talk
```

**Comment by cdoenges** [comment]
> hey @cdoenges , a few questions:
> 1. Are you using a custom directory for your flatpak installations?

hey @tchx84,
No, everything is left at defaults. I'm a noob with flatpak ... 🤷

> 2. Try the following
> 
> ```
> $  rm ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal # to reset any previous changes to Flatseal permissions
> $  flatpak --user override com.github.tchx84.Flatseal --filesystem=host:ro
> ```

Before:
```console
$ ls -al ~/.local/share/flatpak/overrides/
total 8
drwxr-xr-x 2 user user 4096 Jun 12 11:54 .
drwx------ 5 user user 4096 Jun 12 11:54 ..
```
After:
```console
$ ls -al ~/.local/share/flatpak/overrides/
total 12
drwxr-xr-x 2 chris chris 4096 Jun 19 10:23 .
drwx------ 5 chris chris 4096 Jun 12 11:54 ..
-rw-r--r-- 1 chris chris   31 Jun 19 10:23 com.github.tchx84.Flatseal
$ cat ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal 
[Context]
filesystems=host:ro;
```
Behavior is the same, "No applications found.". 😢

**Comment by neoedmund** [comment]
same problem.
`flatpak info -M com.github.tchx84.Flatseal`

```
[Context]
shared=ipc;
sockets=x11;wayland;fallback-x11;
devices=dri;
filesystems=host-etc:ro;/usr/local/var/lib/flatpak:ro;xdg-data/flatpak/overrides:create;/usr/local/var/lib/flatpak/app:ro;host:ro;/var/lib/flatpak/app:ro;xdg-data/flatpak/app:ro;

[Session Bus Policy]
org.gnome.Software=talk
org.freedesktop.impl.portal.PermissionStore=talk
```

my flatpak is installed in `/usr/local/var/lib/flatpak` instead of `/var/lib/flatpak`

**Comment by tchx84** [comment]
@neoedmund can you try the following and see if it makes any difference?

From the terminal:
```
$ flatpak --user override --env=FLATPAK_SYSTEM_DIR=/usr/local/var/lib/flatpak com.github.tchx84.Flatseal
$ flatpak --user override --filesystem=/usr/local/var/lib/flatpak com.github.tchx84.Flatseal

```

**Comment by tchx84** [comment]
@cdoenges can you run the following and share the output here?

From the terminal:
```
$ flatpak info --show-location com.github.tchx84.Flatseal
```

Just to confirm where Flatpaks are being installed on your system as well.

**Comment by cdoenges** [comment]
Sure:

```console
$ flatpak info --show-location com.github.tchx84.Flatseal
/var/lib/flatpak/app/com.github.tchx84.Flatseal/x86_64/stable/09d6d0d42d1df5db4fcbd55507e8c32e134f4f6ff334eb5e63af2978db8e4e1a
```

**Comment by tchx84** [comment]
> ### Steps to reproduce
> 1. Install flatpak 1.10.7 on Debian 11 as instructed here https://flatpak.org/setup/Debian.
> 2. Install Flatseal 1.8.0 using the flatpakref from https://flathub.org/apps/details/com.github.tchx84.Flatseal. This opens up the "Software" app. Click on "Install".
> 3. Start Flatseal.

@cdoenges I followed these steps on a VM to see if I could replicate the issue, but no luck.. :thinking: 

```
tchx84@debian11-uni:~$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
tchx84@debian11-uni:~$ flatpak  --version
Flatpak 1.10.7
```

```
tchx84@debian11-uni:~$  flatpak info --show-location com.github.tchx84.Flatseal
/var/lib/flatpak/app/com.github.tchx84.Flatseal/x86_64/stable/09d6d0d42d1df5db4fcbd55507e8c32e134f4f6ff334eb5e63af2978db8e4e1a
```

![Screenshot from 2022-07-13 20-41-11](https://user-images.githubusercontent.com/481418/178860492-a56975db-2cef-45cd-8860-7201052c9485.png)

I really wonder if there's something else different on your system... or something else to reproduce this..

**Comment by neoedmund** [comment]
> @neoedmund can you try the following and see if it makes any difference?
> 
> From the terminal:
> 
> ```
> $ flatpak --user override --env=FLATPAK_SYSTEM_DIR=/usr/local/var/lib/flatpak com.github.tchx84.Flatseal
> $ flatpak --user override --filesystem=/usr/local/var/lib/flatpak com.github.tchx84.Flatseal
> ```

sorry, I just recompile the flatpak with 
```
./autogen.sh  --disable-documentation
./configure --localstatedir=/var  --disable-documentation
make -j22
sudo make install
```
the problem gone. so I guess Flatseal just hardcode the install dir of flatpak. this is the workaround on flatpak for me to use Flatseal.

**Comment by tchx84** [comment]
> sorry, I just recompile the flatpak with
> ...
> the problem gone. so I guess Flatseal just hardcode the install dir of flatpak. this is the workaround on flatpak for me to use Flatseal.

ugh, that's hardcore. The method I mentioned above is the actual Flatpak mechanism to handle cases like this.

**Comment by tchx84** [comment]
> > ### Steps to reproduce
> I really wonder if there's something else different on your system... or something else to reproduce this..

@cdoenges feel free to re-open if you get the time to research more on this. As you can see above, I reproduced your environment on a VM and seems to work fine..

**Comment by SineSwiper** [comment]
This is still a problem for me with Linux Mint.  I'm just doing a standard install of Flatpak and Flatseal with the default Software Manager.  The only thing that shows up is a Flatpak I installed manually from a downloaded file, which is in `~/.local/share/flatpak/app/`.  It does NOT show everything installed in `/var/lib/flatpak/app`, which is the default directory for all of the Mint-managed Flatpaks, installed via Software Manager.

```
$ flatpak info --show-location com.github.tchx84.Flatseal
/var/lib/flatpak/app/com.github.tchx84.Flatseal/x86_64/stable/14ba14f237835365b3b5f2c8f6eee2dcaf7f248d92f3eaf51e00ab28cfe523b1
$ flatpak info -M com.github.tchx84.Flatseal
[Context]
shared=ipc;
sockets=x11;wayland;fallback-x11;
devices=dri;
filesystems=xdg-data/flatpak/overrides:create;/var/lib/flatpak/app:ro;xdg-data/flatpak/app:ro;

[Session Bus Policy]
org.gnome.Software=talk
org.freedesktop.impl.portal.PermissionStore=talk
$ ls -ld /var /var/lib /var/lib/flatpak /var/lib/flatpak/app /usr /usr/lib /usr/lib/flatpak /var/lib/flatpak/app/*Flatseal*
drwxr-xr-x  17 root root 4.0K Jun 14 00:17 /usr
drwxr-xr-x 140 root root 4.0K Dec  6 16:40 /usr/lib
drwxr-xr-x   8 root root 4.0K Dec  6 20:12 /usr/lib/flatpak
drwxr-xr-x  13 root root 4.0K Jun 16 09:29 /var
drwxr-xr-x  75 root root 4.0K Sep  9 20:29 /var/lib
lrwxrwxrwx   1 root root   16 Sep  6 15:29 /var/lib/flatpak -> /usr/lib/flatpak
drwxr-xr-x  17 root root 4.0K Dec  6 19:59 /var/lib/flatpak/app
drwxr-xr-x   3 root root 4.0K Dec  6 19:59 /var/lib/flatpak/app/com.github.tchx84.Flatseal
```

This is also interesting:

```
$ flatpak --user override --filesystem=/usr/lib/flatpak com.github.tchx84.Flatseal
$ flatpak run com.github.tchx84.Flatseal
F: Not sharing "/usr/lib/flatpak" with sandbox: Path "/usr" is reserved by Flatpak
F: Not sharing "/var/lib/flatpak/app" with sandbox: Path "/usr" is reserved by Flatpak
```

Moving the whole Flatpak directory outside of `/usr` seems to work.  No idea why `/usr` is such a sacred cow for Flatpak and Proton...
