### ISSUE TITLE
accept filesystem paths ending in a slash

### ISSUE THREAD

**Issue by chaserene** [tchx84/Flatseal#456]
it took me a long time to notice that filesystem paths that end with a forward slash (/) are deemed invalid by Flatseal. sure, the icon at the beginning of the line turns to an orange exclamation mark, but it doesn't give the impression of some serious trouble, since such an icon in blue is already there for user-edited entries.

terminating paths to a folder with a slash (/foo/bar/) is standard practice in GNU/Linux. could you modify Flatseal to accept this notation?

**Comment by tchx84** [comment]
Ill look into this.
