### ISSUE TITLE
flatseal has issues with dark theme on mint 20.3 xfce 

### ISSUE THREAD

**Issue by AshutoshGitMirror** [tchx84/Flatseal#457]
![image](https://user-images.githubusercontent.com/79195050/174492408-4382c86a-c2c6-4cac-aa4f-ef620a9681f5.png)
![image](https://user-images.githubusercontent.com/79195050/174492434-030a7083-1bd8-4c04-b961-3bcaba15aab0.png)
![image](https://user-images.githubusercontent.com/79195050/174492459-8ca67813-59e9-4206-9ae4-6492808ae8ab.png)

**Comment by rusty-snake** [comment]
What does `flatpak run --command=dbus-send com.github.tchx84.Flatseal --session --dest=org.freedesktop.portal.Desktop --print-reply=literal /org/freedesktop/portal/desktop org.freedesktop.portal.Settings.Read string:"org.freedesktop.appearance" string:"color-scheme"` show?

**Comment by AshutoshGitMirror** [comment]
> What does `flatpak run --command=dbus-send com.github.tchx84.Flatseal --session --dest=org.freedesktop.portal.Desktop --print-reply=literal /org/freedesktop/portal/desktop org.freedesktop.portal.Settings.Read string:"org.freedesktop.appearance" string:"color-scheme"` show?

![image](https://user-images.githubusercontent.com/79195050/174523654-276f07bb-b1d2-4f1a-906d-612c39afe381.png)

**Comment by rusty-snake** [comment]
> Error org.freedesktop.portal.Error.NotFound: Requested setting not found

_Text is better for bandwidth and accessibility than screenshot._

What portal implementation are you running? (`apt list --installed | grep portal` might help)

**Comment by AshutoshGitMirror** [comment]
> > Error org.freedesktop.portal.Error.NotFound: Requested setting not found
> 
> _Text is better for bandwidth and accessibility than screenshot._
> 
> What portal implementation are you running? (`apt list --installed | grep portal` might help)

```
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
xdg-desktop-portal-gtk/una,now 1.8.0-1~flatpak1~20.04 amd64 [installed]
xdg-desktop-portal/una,now 1.8.1-1~flatpak1~20.04 amd64 [installed] ```

**Comment by AshutoshGitMirror** [comment]
any update or solution regarding this?

**Comment by rusty-snake** [comment]
It's not a bug in flatseal, instead in xfce, mint or your configuration but I'm not deep enough in this topic to help you debug.

As a workaround you can set `GTK_THEME=Adwaita:dark` via flatseal of course.

**Comment by AshutoshGitMirror** [comment]
That workaround worked pretty well thanks! Should I close this issue?
