### ISSUE TITLE
"All applications" icon isn't great

### ISSUE THREAD

**Issue by bertob** [tchx84/Flatseal#458]
This icon doesn't look great, I'd go with something like a plain blue circle with the [new flatpak logomark](https://blog.jimmac.eu/2022/flatpak-refresh/) in white on it instead.

![image](https://user-images.githubusercontent.com/1908896/175500094-29a58cb5-ab9c-4b91-a804-2047c55abe5c.png)

**Comment by tchx84** [comment]
hey @bertob , can make the icon? :) Ill gladly accept it.

**Comment by haggen88** [comment]
you could use the [new icon](https://github.com/flatpak/flatpak.github.io/issues/537)

**Comment by haggen88** [comment]
@tchx84 you can try this  [com.github.tchx84.Flatseal.Flatpak  _new.svg.zip](https://github.com/tchx84/Flatseal/files/9078350/com.github.tchx84.Flatseal.Flatpak._new.svg.zip)

ref: https://github.com/flatpak/flatpak.github.io/issues/537

**Comment by tchx84** [comment]
> @tchx84 you can try this [com.github.tchx84.Flatseal.Flatpak _new.svg.zip](https://github.com/tchx84/Flatseal/files/9078350/com.github.tchx84.Flatseal.Flatpak._new.svg.zip)
> 
> ref: [flatpak/flatpak.github.io#537](https://github.com/flatpak/flatpak.github.io/issues/537)

Thanks, ill give it a try :)
