### ISSUE TITLE
Allow file paths with colons (:) and potentially other special characters 

### ISSUE THREAD

**Issue by dustin-richards-was-here** [tchx84/Flatseal#468]
I've come across an issue where I can't add a network share (Samba) managed by GNOME to the "Other files" list since it disallows colons aside from a permissions override. Would it make sense to allow colons that are escaped (\\:) or allow them by some other method?

![image](https://user-images.githubusercontent.com/31833924/188077462-cd22735a-21b3-405a-819a-3914576b41e7.png)

**Comment by dustin-richards-was-here** [comment]
Thought of just adding an override at the end, which works, but seems like it shouldn't be needed.

![image](https://user-images.githubusercontent.com/31833924/188077900-ef5911bc-bec4-4056-805f-eab20a90ef2e.png)

**Comment by dustin-richards-was-here** [comment]
On second thought, this doesn't seem to work (despite the filename input not complaining anymore) as my Firefox claims the directory above is empty and that its child directories don't exist.

**Comment by rusty-snake** [comment]
```console
$ mkdir -p ~/foo:bar/baz
$ flatpak override --user --filesystem=~/foo:bar/baz org.gnome.TwentyFortyEight
F: Unexpected filesystem suffix bar/baz, ignoring
$ cat ~/.local/share/flatpak/overrides/org.gnome.TwentyFortyEight 
[Context]
filesystems=/home/rusty-snake/foo;
$ nvim ~/.local/share/flatpak/overrides/org.gnome.TwentyFortyEight  # Add correct path by hand
$ flatpak run --command=ls org.gnome.TwentyFortyEight      
F: Unexpected filesystem suffix bar/baz, ignoring
```

There's nothing flatseal can do here. You need to report this to flatpak first. As long as this is the behaviour of flatpak, flatseal behaves correct.

**Comment by tchx84** [comment]
Closing this as-per @rusty-snake explanation. Let's re-open this if Flatpak finds a way to allow it.
