### ISSUE TITLE
Allow to differentiate the origin of a permission modified by the user

### ISSUE THREAD

**Issue by ghost** [tchx84/Flatseal#471]
Currently there is no way to know if a permission modified by the user has been done for an app, global or both. It is confusing and prevents to know what are the default permissions of an app even if it has only been modified in global. I suggest putting icons with a different color, maybe also add some easy way to see the original permissions without restoring them.

**Comment by tchx84** [comment]
Hey! This is already addressed (different colors approach) on the master branch and will be available on the next release.
