### ISSUE TITLE
Port Flatseal to use the Gnome 43 Platform

### ISSUE THREAD

**Issue by ghost** [tchx84/Flatseal#475]
Gnome app do start their migration to gnome 43 platform, is it possible to flatseal to follow the move to be able to fastly get rid of 42 on our system when all app will have updated ?

Thanks !

**Comment by rusty-snake** [comment]
Already done: #473 (merged 3 days ago)

**Comment by ghost** [comment]
> Already done: #473 (merged 3 days ago)

yeah but last time, between the merge, and the update month have passed, so it's why i opened an issue, to not let "forget" to push the code to the flatpak (so it can be added to their project) to the next flatpak update.

**Comment by tchx84** [comment]
I maintain the Flathub package too, so it will get updated as soon as I finish this release.
