### ISSUE TITLE
label all buttons to help accessibility

### ISSUE THREAD

**Issue by mhussaincov93** [tchx84/Flatseal#496]
hi,
none of the buttons have lables that can be red by orca the screen reader.
when flatseel is ran the only feedback I get with orca the screen reader, is button button button.
everytime I tab over the buttons.
I would be greatful if you could look in to this.
Majid

**Comment by tchx84** [comment]
I will prioritize this for the next release.

**Comment by tchx84** [comment]
I believe this is fixed now, thanks updates in GTK and Libadwaita. If you find other accessibility issues just let me know.
