### ISSUE TITLE
UI has an issue with Adwaita dark theme

### ISSUE THREAD

**Issue by felipehw** [tchx84/Flatseal#5]
Hi.
I'm using Fedora 31 with Adwaita dark theme.

The Flatseal UI has problems of readability with the dark theme:
![Screenshot from 2020-01-29 13-35-44](https://user-images.githubusercontent.com/4523897/73376493-4baa3a00-429c-11ea-8b3b-44405d411b36.png)

**Comment by tchx84** [comment]
Interesting, I will take a look.

**Comment by tchx84** [comment]
Fixed it. This will be available with the next release (or you can test it yourself with the README instructions). Thanks for reporting this!
