### ISSUE TITLE
Font replaced by blocks

### ISSUE THREAD

**Issue by phil-flip** [tchx84/Flatseal#501]
As pointed out 3 weeks ago int eh issue https://github.com/tchx84/Flatseal/issues/500, The font gets replaced with blocks their solution unfortunately didn't work for me.

![image](https://user-images.githubusercontent.com/27019397/205180670-86e43def-a9f4-4a0d-b6af-b292bb7b3554.png)

```log
[phil@philtower app]$ flatpak run com.github.tchx84.Flatseal
Gtk-Message: 00:24:57.235: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:24:57.235: Failed to load module "pk-gtk-module"
Gtk-Message: 00:24:57.236: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:24:57.236: Failed to load module "pk-gtk-module"

(com.github.tchx84.Flatseal:2): Pango-WARNING **: 00:24:57.287: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell 11'

(com.github.tchx84.Flatseal:2): Pango-WARNING **: 00:24:57.287: font_face status is: file not found

(com.github.tchx84.Flatseal:2): Pango-WARNING **: 00:24:57.287: scaled_font status is: file not found

(com.github.tchx84.Flatseal:2): Pango-WARNING **: 00:24:57.287: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell 11'

(com.github.tchx84.Flatseal:2): Pango-WARNING **: 00:24:57.287: font_face status is: file not found

(com.github.tchx84.Flatseal:2): Pango-WARNING **: 00:24:57.287: scaled_font status is: file not found
```

I run Rocky Linux 9, and it wasn't an issue before I updated my system. But… I'm pretty sure it wasn't font related updates.
The software version is `1.8.1`

**Comment by istori1** [comment]
I have this issue too on AlmaLinux 9.1

![blocks](https://user-images.githubusercontent.com/107304850/205905611-37a4ae1f-2a9d-427a-a07b-26a39432f0b4.png)

**Comment by phil-flip** [comment]
Unfortunately, this doesn't seem to be Flatseal specific, and other software seem to have a similar issue. So nothing that can be done here.

**Comment by rizajur** [comment]
> Unfortunately, this doesn't seem to be Flatseal specific, and other software seem to have a similar issue. So nothing that can be done here.

please reopen , wrong attitude bro 

![a](https://user-images.githubusercontent.com/123980461/215566138-8b3d7367-9d32-4b27-96ac-efa3348c2363.png)

Using AlmaLinux 9 (RHEL 9) - install via flathub

@tchx84 i checked and installed many fonts please provide me with a hint to search your font implementation since other applications work fine and there is no reason to believe we cant do anything about it

@FlipperLP 

>other software seem to have a similar issue

which apps does it effect, who can we "blame" :D and ask how we can help to resolve this issue for all of us and provide support 

first of all i want to line out that the blame goes to RHEL 9
since rpmfusion does it's job okay but not good enough 

which fonts do we need to install for the flatseal application to be able to work with it or we could try and embed the fonts within flatseal to workaround the system font dependency.

**Comment by tchx84** [comment]
Ill try to reproduce it..

**Comment by rizajur** [comment]
`$ grep -R "font" ./`

`./data/icons/com.github.tchx84.Flatseal.Source.svg:         style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:4px;line-height:125%;font-family:Cantarell;-inkscape-font-specification:'Cantarell, Bold';text-align:start;writing-mode:lr-tb;text-anchor:start;display:inline;fill:#000000;fill-opacity:1;stroke:none;stroke-width:0.332649;enable-background:new"
`
looks worth checking out 
font-family: Cantarell - suggests
https://fonts.google.com/specimen/Cantarell

or 

https://github.com/GNOME/cantarell-fonts

@tchx84  no clue please help me out :D

```
$ sudo dnf install abattis-cantarell-fonts
[sudo] password for user: 
Last metadata expiration check: 0:55:42 ago on Mo 30 Jan 2023 19:10:38 CET.
Package abattis-cantarell-fonts-0.301-4.el9.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

hmm looks like i already installed it

**Comment by phil-flip** [comment]
I heard from my roommate that this seems to be a common issue that was introduced into an update at the time. Because the font was completely broken and not working across multiple apps, I ended up switching the font to something that looks similar. Since then i simply forgot, that this was still a problem about my system. ^^'

**Comment by rizajur** [comment]
> across multiple apps, I ended up switching the font to something that looks 
similar 

@FlipperLP  wow thanks i will write a note into the ReadMe.md thanks for the hint... :+1: roommate

**Comment by phil-flip** [comment]
It got really out of hand once I cleared the font cache (don't know the command anymore, tho).
So it might be fixed now and I will check later.

**Comment by rizajur** [comment]
![ab](https://user-images.githubusercontent.com/123980461/215573306-e068867e-e3ed-46d2-93d1-86d9dbd892d2.png)

@FlipperLP  what is the name of the font just to give me a hint :D
quick screenshot from gnome-tweaks font section please :D huge thanks

**Comment by phil-flip** [comment]
![image](https://user-images.githubusercontent.com/27019397/215573890-f248d7c4-97bc-4d44-9f8b-9437b480624d.png)
I just tested again, it's only flatpak that is having issues, specifically Lutris and Flatseal. But for example, the newly installed Firefox in Flatpak (because the normal one had Encoder issues) doesn't have that… So maybe I can't get away by just removing the software and reinstalling… But can't try that today...

**Comment by rizajur** [comment]
https://github.com/tchx84/Flatseal/pull/506 :rocket:  
as long as we don't have a better solution 

> So maybe I can't get away by just removing the software and reinstalling… But can't try that today...

as i said i tried this with more fonts installed later on and this changed nothing. so thanks for the fix

**Comment by rusty-snake** [comment]
Relates to flatpak/flatpak#5288

**Comment by tchx84** [comment]
Now that this problem is well [understood](https://github.com/flatpak/flatpak/issues/3191#issuecomment-1509995663), and that it's a Flatpak-level [issue](https://github.com/flatpak/flatpak/issues/5288), I am closing this.

If you happen to be hit by this issue, the most common workaround is to update the fonts cache like this:

```
flatpak run --command=fc-cache com.github.tchx84.Flatseal  -f -v /usr/share/fonts/cantarell
```
