### ISSUE TITLE
Flatseal is transparent.

### ISSUE THREAD

**Issue by coffseducation** [tchx84/Flatseal#504]
Flatseal is completely transparent.
I have to open Flatseal on top of an opaque dark background in order to read it.
Uninstalling and re-installing do not work.
Removing the file from .var does not work.
Removing .local/share/flatpak/overrides does not work.
Adding Flatseal to opaque apps in Kvantum does not work.

Operating System: Kubuntu 22.10
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.6
Kernel Version: 5.19.0-26-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7820HQ CPU @ 2.90GHz
Memory: 31.2 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630
Manufacturer: Dell Inc.
Product Name: Precision 5520

**Comment by rusty-snake** [comment]
My only idea is that some kind of kwin rule could cause this. Maybe worth to check if this happens in openbox/... too.

**Comment by tchx84** [comment]
@coffseducation very strange.. Ill try to reproduce this sometime this week.

**Comment by tchx84** [comment]
I set up a similar environment to test and, under out-of-the-box conditions, I can't reproduce this on master.

![Screenshot from 2023-04-19 13-06-39](https://user-images.githubusercontent.com/481418/233149076-c92a503a-ae5f-4679-865e-478390f2ed32.png)

![Screenshot from 2023-04-19 13-06-06](https://user-images.githubusercontent.com/481418/233149239-40a9a23f-aaad-426e-a730-0cf604cf6987.png)

Feel free to re-open this is you can still reproduce this after the next release.
