### ISSUE TITLE
All portals are greyed out in every app

### ISSUE THREAD

**Issue by ghost** [tchx84/Flatseal#505]
System: `sway 1.8-3`
I have installed:
```
xdg-desktop-portal 1.16
xdg-desktop-portal-gtk 1.14
xdg-desktop-portal-wlr 0.6
```

verified `xdg-desktop-portal-wlr` running correctly, but in flatseal (installed from flathub) all the portals choices are greyed out doesn't matter which application i check it with, from what i've seen from other users sharing screenshots, both discord and VLC have options for portals but for me they're greyed out.

![20230108_22h50m10s_grim](https://user-images.githubusercontent.com/59608414/211218487-3164af40-2a9b-48ec-af99-c8c624e39cdc.png)

**Comment by rusty-snake** [comment]
If you hover the portals with your cursor a tooltip indicating the reason should show up.

Are you sure those other users had `xdg-desktop-portal-wlr` installed and not `xdg-desktop-portal-gnome` for example with implements much more portals.

**Comment by ghost** [comment]
> If you hover the portals with your cursor a tooltip indicating the reason should show up.
> 
> Are you sure those other users had `xdg-desktop-portal-wlr` installed and not `xdg-desktop-portal-gnome` for example with implements much more portals.

You're right, looking at `xdg-desktop-portal-wlr` it barely has any implementation (just for screenshot and screeshare as far as i can see). 

I suppose this is a `xdg-desktop-portal-wlr` issue and not flatseal.
