### ISSUE TITLE
Flatseal Theme Control

### ISSUE THREAD

**Issue by tenplus1** [tchx84/Flatseal#507]
Would it be possible to add a way so that Flatseal can handle flatpak theming as well using the following link information:

https://itsfoss.com/flatpak-app-apply-theme/

**Comment by rusty-snake** [comment]
You can already do it. Just allow the paths from your link and set the env variables.

Edit: Your link even explains flatseal.

**Comment by tenplus1** [comment]
I mean themeing from within the Flatseal app to avoid terminal for beginners.

**Comment by rusty-snake** [comment]
Where do you need a terminal?

**Comment by rizajur** [comment]
@rusty-snake oh great lord, stop this immature behavior and tell this young (or old) minecraft fellow how he can do it.
And btw i guess you dont talk about the same. 

>set the env variables

Im not sure (noob in terms of flatpaks) if you can set different for each application, that's why im also interested in an answer but dont mind your ping pong use a search engine and dont ask on github attitude

**Comment by KaranAhlawat** [comment]
The original issue was created to find a way to configure Flatpak themes through Flatseal itself. @rusty-snake pointed out it's already possible, and also pointed out that the method is in the original link posted. It's all GUI, no terminal needed.

So, they did provide a straight forward answer (without any immature behavior) to @tenplus1.

@rizajur You can indeed set different GTK_THEME for different Flatpaks through Flatseal itself. It is just a matter of adding an environment variable (through the GUI) called GTK_THEME and setting it's value to the name of the theme.
For future interactions, please refrain from calling people immature without fully understanding the solution that was provided or the previous conversation.

**Comment by tchx84** [comment]
@tenplus1 for reaching out, I think @KaranAhlawat summarized this very well.
