### ISSUE TITLE
[Bug] Flatseal does not allow per application permissions to change back to default when they are overridden by global permissions

### ISSUE THREAD

**Issue by ManIVIctorious** [tchx84/Flatseal#509]
First of all sorry for the convoluted title, if you have a better one feel free to change it / let me know.
I am not exactly sure how to describe the issue so I will start with a summary of how I stumbled upon it:

I noticed this bug when playing with gradience (com.github.GradienceTeam.Gradience) to change my gtk theme.

To enable all flatpaked applications to make use of the theme preset they need access to the following two directories
```
xdg-config/gtk-3.0
xdg-config/gtk-4.0
```
which I enabled globally.

Since I don't want any other applications to mess with these settings I set them to read only
```
xdg-config/gtk-3.0:ro
xdg-config/gtk-4.0:ro
```

Of course, gradience still needs to access these with read and write permissions, which is exactly the issue I encountered:

When a file permission is set globally, flatseal does not allow you to set it in a specific application with a different modifier.

It does seem to understand it though. When removing the :ro flag for gradience the triangle changes from grey (gloablly set) to blue (per application set), unfortunately though it does not create the corresponding override file.

Since this failed completely silently this took me quite some time to figure out...

**Comment by ManIVIctorious** [comment]
I just realised I made a mistake, the changed triangle symbol only appeared for a different application not for gradience and for these it worked properly so here is what I think:

As I understand the permission system the end-result is the stack

application specific
global
default

I believe Gradience already has the two directories set up by default therefore, removing the :ro flag resets it to its default state which then is overridden by the global state.

I am not sure about the proper solution for this, but maybe it would just be to take the global permissions into account when setting per application ones?

Sorry for the confusion, I will updated the title accordingly

**Comment by tchx84** [comment]
@ManIVIctorious can you describe step by step what I need to do to reproduce the issue you're presenting here?

**Comment by ManIVIctorious** [comment]
I already tried so, I'll do my best 😅

1. Install [Gradience](https://flathub.org/apps/details/com.github.GradienceTeam.Gradience)
2. Open flatseal, go to All Applications tab and enable the following file system permissions
    * xdg-config/gtk-3.0:ro
    * xdg-config/gtk-4.0:ro

This should be equivalent to:
```
cat .local/share/flatpak/overrides/global 
[Context]
filesystems=xdg-config/gtk-3.0:ro;xdg-config/gtk-4.0:ro
```

Now all applications should have read only access to the two aforementioned directories.
Unfortunately, this also includes gradience which, by default has (and must have) read write access to them.

3. Jump to the Gradience tab in flatseal

Here, in the file system section, you should now see the two entries
* xdg-config/gtk-3.0:ro
* xdg-config/gtk-4.0:ro

Removing them either by clicking the x-button to the right or removing the :ro flag does not result in the creation of a new file in flatpak overrides and hence, gradience does not get read write access to these directories.

Expected behaviour:
Creation of the following file

```
cat .local/share/flatpak/overrides/com.github.GradienceTeam.Gradience 
[Context]
filesystems=xdg-config/gtk-3.0;xdg-config/gtk-4.0
```
to enable read write access to the two directories.

I hope this is more clear now, feel free to ask for further clarification

**Comment by tchx84** [comment]
@ManIVIctorious thanks, I can reproduce it.. I'll investigate what's going on, but here's a workaround:

On your Step 3, instead of removing the override line, change it from `xdg-config/gtk-4.0:ro` to `xdg-config/gtk-4.0:rw`, and it will work. Adding the `rw` forces that line to take precedence.

**Comment by tchx84** [comment]
I looked into this and determined that the current "language" expressed by Flatseal isn't powerful enough to deal with this particular situation, given that there's really no different between the user writing back an original permission and just having that original permission.

For anyone dealing with this particular issue, the workaround is to find a different way to express that same original permission so that Flatseal can detect it (and differentiate from the original), e.g., using `xdg-config/gtk-4.0:rw` instead.
