### ISSUE TITLE
Flatseal microphone portal

### ISSUE THREAD

**Issue by PeterKW** [tchx84/Flatseal#510]
https://github.com/tchx84/Flatseal/issues/285

Do I need to run a command to give flat seal permission to change access to the microphone? What should I try next?

 
![image](https://user-images.githubusercontent.com/13779157/224831280-15ab4fc3-24af-439f-8f78-5d1d23e5b000.png)

**Comment by tchx84** [comment]
This means that this app has not requested the portal for such access, which probably means it's not accessing that resource through portals. Therefore, even if you force this, it won't do anything.
