### ISSUE TITLE
Duplicates of a folder in the Persistent section show up in the UI until reloading

### ISSUE THREAD

**Issue by feschber** [tchx84/Flatseal#511]
## reproduce
Add "." folder under Persistent -> Files for some application.

It will show up twice (or several times) until switching to a different application and back.

**Comment by tchx84** [comment]
Thanks, I'll check what's going on..

**Comment by tchx84** [comment]
@ferdinandschober can you provide more details? I can't reproduce this. e.g, Flatseal version, and precise steps to reproduce (1,2,3..etc).

**Comment by feschber** [comment]
My Flatseal version is 1.8.1 on flatpak 1.15.4. 
To reproduce:
- Go to the settings of any application
- Scroll down to "Persistent", where it says List of homedir-relative paths created in sandbox
- Add a folder using the icon.
- Add the same folder again. (I used ".local")

At this point the folder shows up twice in the UI until switching to another application and back:

Before UI refresh
![image](https://user-images.githubusercontent.com/40996949/229039346-6f11b217-7cb2-487b-99dd-3c1c0aa4e613.png)

After UI refresh:
![image](https://user-images.githubusercontent.com/40996949/229039390-c7fec715-ef8f-4318-817a-363ea6e301db.png)

**Comment by feschber** [comment]
It's of course not a mayor bug :)

**Comment by tchx84** [comment]
ohh, I understand now, what's the behavior you would expect ? e.g, what should Flatseal do when someone enters the same path twice?

**Comment by feschber** [comment]
> ohh, I understand now, what's the behavior you would expect ? e.g, what should Flatseal do when someone enters the same path twice?

If the path disappears on refresh I would expect it to just never show up in the first place.

**Comment by tchx84** [comment]
It's not very clear how to achieve that sort of UX, without adding a of complexity.  I understand the reasoning on your report, so thanks for sharing it, but I think the current behavior is something we can live with for the time being.
