### ISSUE TITLE
Dependency lookup for libhandy-1 with method 'pkgconfig' failed

### ISSUE THREAD

**Issue by lx-abhi** [tchx84/Flatseal#516]
Hi,
When I try to install the Flatseal from AUR in Manjaro,  with the following command. 

`$ yay -S flatseal`

I get the following error.
Can you please help me to resolve this issue ?

**Dependencies met:**
flatpak - yes
gjs - yes
libhandy - yes
webkit2gtk - yes
flatpak-builder - yes
meson - yes
ninja - yes

![Flatseal_error](https://user-images.githubusercontent.com/129678374/229364532-3e5ca130-1519-48a5-a646-1006c41d3d74.png)

**Comment by q7nm** [comment]
Do you have `base-devel` installed?

**Comment by lx-abhi** [comment]
No, it is not installed. 
Thank you !  

After installing `base-devel`, The issue is resolved.
