### ISSUE TITLE
Can't configure portals

### ISSUE THREAD

**Issue by ghost** [tchx84/Flatseal#520]
OS: Arch Linux
I have both xdg-desktop-portals and one of it's backeds(xdg-deskto-portals-gtk) installed
![image](https://user-images.githubusercontent.com/37870434/230728318-143f6d7d-74ae-49fc-b9cd-945ff3d0e6c6.png)

**Comment by rusty-snake** [comment]
Do you see this for one flatpak or for all?

How does it look for flatseal itself?

**Comment by tchx84** [comment]
@Chromanical tricky to explain but let me try. 

Flatseal can't force an application to use a portal. That's not how portals work. Applications must first support a portal and use it, and only then Flatseal can override the decision made by the user while using that application, 

e.g. Application X that supports the camera portal, asks the user to grant such permission, and then that decision is "recorded". The only thing that Flatseal can do is override that decision.

The message you see there means that the application hasn't use that portal yet (and therefore the decision hasn't been recorded yet) or, the application doesn't support that Portal at all.

**Comment by ghost** [comment]
> @Chromanical tricky to explain but let me try.
> 
> Flatseal can't force an application to use a portal. That's not how portals work. Applications must first support a portal and use it, and only then Flatseal can override the decision made by the user while using that application,
> 
> e.g. Application X that supports the camera portal, asks the user to grant such permission, and then that decision is "recorded". The only thing that Flatseal can do is override that decision.
> 
> The message you see there means that the application hasn't use that portal yet (and therefore the decision hasn't been recorded yet) or, the application doesn't support that Portal at all.

Thank you for the explanation!
