### ISSUE TITLE
Title bar separator misalignment

### ISSUE THREAD

**Issue by deadmeu** [tchx84/Flatseal#522]
Running the Flatseal flatpak in KDE (Arch Linux - Wayland) shows a small misalignment with the height of the left Applications pane and the right details pane:
![2023-04-11_22-19-06-1](https://user-images.githubusercontent.com/12111013/231161084-2b98e973-2ce1-4806-b090-ed5c1e758687.png)

**Comment by rusty-snake** [comment]
What GTK-Theme, Icon-Theme and font settings are you using?

To get the actual used once, run `GTK_DEBUG=interactive flatpak run com.github.tchx84.Flatseal` and go to the visual tab.

Does it work if you set `Adwaita` and `Cantarell Regular 11`?

**Comment by deadmeu** [comment]
I'm using the Breeze GTK+ Theme with the Noto Sans Regular 10 Font (Font scale 1.00). The Icon theme is blank, but in KDE I'm using the default Breeze Dark theme with Papirus-Dark icons.

Setting the GTK+ Theme to Adwaita doesn't seem to change anything but changing the font size does. At a small font size (Noto Sans Regular 9) seems to be small enough to allow the lines to become aligned. As I increase the font size the right header increases and it seems like with the padding it's just expanding while the left header does not:
![2023-04-11_22-49-04](https://user-images.githubusercontent.com/12111013/231167211-2340cd81-f939-4a6c-872e-471a1c0c2009.png)

**Comment by deadmeu** [comment]
I'm not sure if this is a result of me just now changing the font sizes and whatnot but the minimise, maximise, and close icons seem to be a bit blurry and potentially too big? I don't remember what it was like before but it might be a separate issue (or maybe just a GTK vs Qt difference with KDE?) Here it is compared to a regular Qt titlebar:
![2023-04-11_22-57-41](https://user-images.githubusercontent.com/12111013/231169570-c2a4a8b0-2536-4339-9559-0caba64ff578.png)

**Comment by tchx84** [comment]
Thanks for the report. Since we switched to GTK 4 and Libadwaita, I suspect this issue no longer applies (although other similar issues might arise)

**Comment by deadmeu** [comment]
Looks like the issue has resolved itself with 2.0.0 and in general the UI appears more consistent too :slightly_smiling_face:
