### ISSUE TITLE
Leaflet oscillates between folded <-> non-folded

### ISSUE THREAD

**Issue by flxzt** [tchx84/Flatseal#536]
I noticed a bug in the most recent update:

The leaflet that is used to display the application list / app permissions seems to be oscillating between folded / non-folded state when the window has a certain width.

This screencast shows it quite clearly:

[flatseal-oscillating-leaflet.webm](https://user-images.githubusercontent.com/19841886/235115739-a3bfa4d7-3bfa-4ea7-b09f-201d3bc0d080.webm)

I am running on:
Fedora 38, Gnome 44.0
Flatseal 2.0.0

**Comment by tchx84** [comment]
good catch, it seems it has something to do with the length of these header buttons (which happen to be larger in German and other locales). Ill look at this, thanks for the report.

**Comment by tchx84** [comment]
@flxzt would you help me test https://github.com/tchx84/Flatseal/pull/538 ?

**Comment by flxzt** [comment]
Sure!  
#538 seems to have fixed it, I don't experience it any more (only tested it with German locale).
