### ISSUE TITLE
Language setting for programs

### ISSUE THREAD

**Issue by Qronikarz** [tchx84/Flatseal#539]
Hello.

Would it be possible to add language setting for programs in Flatseal? I have some programs that I prefer in different language so I am using `LANGUAGE=en` environment variable, but it would be better and easier if there was some setting for every program to just pick a language from the list since you wouldn't need to worry about finding correct shortened form.

**Comment by tchx84** [comment]
EDIT: My bad I misread ! 

Flatseal scope is to manage permissions, and if within that someone is allowed to do things like setting the locale that's really great. But these use-cases in themselves are way beyond the scope of this application.
