### ISSUE TITLE
App wouldn't recognize dark theme

### ISSUE THREAD

**Issue by Tuba2** [tchx84/Flatseal#540]
### Context

For consistency's sake, while many apps are still migrating to GTK4, I use the adw-gtk3-dark theme, both system-wide and as a Flatpak (```org.gtk.Gtk3theme.adw-gtk3-dark```).

On Flatpak, I install _only the dark variant_.

However, I know the app now runs on GTK4 and Libadwaita.

### System

Fedora 38
GNOME 44.1
Flatseal 2.0.0 - Flatpak (Flathub)
Dark theme and 'prefer-dark' enabled

### What I expected to happen

Firstly, I expected Flatseal to recognize the installed theme and load up with the dark Adwaita look.

However, after remembering the changes in the last update, I just expected the app to follow the system dark theme.

### What actually happened

The app started with the light variant of the old Adwaita theme (GTK3), with the interface text quite cramped — I forgot to screenshot, sorry.

### Steps to reproduce

1 - Set up dark mode and 'prefer-dark' in GNOME
2 - Install ```org.gtk.Gtk3theme.adw-gtk3-dark``` (only the dark variant)
3 - Install Flatseal from Flathub
4 - Run the app

### What fixed it

Running ```sudo flatpak override --env=ADW_DEBUG_COLOR_SCHEME=prefer-dark```, it worked correctly.

However, I tried resetting the overrides and it now just works fine with the dark theme.

Maybe it was a bug with Flatpak environment variables. But it is weird because the issue was only with this app, and only after the recent update.

---

If you need any more info, I'll try to fetch it for you, but even I can't reproduce it anymore.

Edit:
Just edited a few mistakes in the title and in the "Steps to reproduce" section.

**Comment by laniakea64** [comment]
> The app started with the light variant of the old Adwaita theme (GTK3), with the interface text quite cramped

For what it's worth, I saw this when running Flatseal with `GTK_THEME=Adwaita` environment variable set.  It also occurs if I set that environment variable to name a GTK3-only theme.  No idea if that might have anything to do with why it happened to you - if not, sorry for the noise.

**Comment by Tuba2** [comment]
Just edited a few mistakes in the title and in the "Steps to reproduce" section

**Comment by Tuba2** [comment]
Maybe the app update didn't update the previous theme selection in my system. Therefore the app may have tried to load the old GTK3 theme, but with a wrong reference, resulting in a fallback to a light Adwaita GTK3 theme.

I truly have no idea, but it was just weird.

**Comment by tchx84** [comment]
Considering

> However, I tried resetting the overrides and it now just works fine with the dark theme.

And 

>  I saw this when running Flatseal with GTK_THEME=Adwaita environment variable set. It also occurs if I set that environment variable to name a GTK3-only theme.

It's very likely that the wrong theme was being forced into the new version via environment variables. But it will keep an eye if further reports.

**Comment by foopsss** [comment]
I had the same issue. I didn't realize Flatseal was already using Libadwaita, so the override OP suggested did the trick for me, and setting GTK_THEME individually for the other apps just in case.
