### ISSUE TITLE
Selecting an application doesn't work unless clicking quickly

### ISSUE THREAD

**Issue by laniakea64** [tchx84/Flatseal#545]
Using Flatseal version 2.0.1

When clicking an application in the list in Flatseal's left sidebar, the application will not get selected unless there is almost no time between mouse down & mouse up.  Lingering the mouse button down for even a tiny amount of time seems to result in the click doing nothing.

Would it be possible to make selecting an application work regardless of the click duration?

Thanks!

**Comment by tchx84** [comment]
Hi @laniakea64 , this seems to be the intended behavior by either libadwaita or GTK4, e.g. try this with GNOME Settings. In any case, you should contact GTK4 and Libadwaita maintainers.
