### ISSUE TITLE
Seems like flatseal is not showing proper permissions

### ISSUE THREAD

**Issue by rjshrjndrn** [tchx84/Flatseal#546]
I've installed slack, and in flatseal, I can see microphone and camera are greyed out. But while doing, a call, I can access both from slack. Is there something I'm missing?

![image](https://github.com/tchx84/Flatseal/assets/2563385/ce739ee4-5d7b-49c2-a959-f54305d8a511)
![image](https://github.com/tchx84/Flatseal/assets/2563385/8600e596-c8b2-42f3-97e3-285432528adc)

While doing huddle

![image](https://github.com/tchx84/Flatseal/assets/2563385/553afc33-e9bd-4637-86ba-58f191a9277b)

**Comment by rusty-snake** [comment]
These Permissions are for Portals. Portals are rather new and only few programs use them. The most programs required permissions for unsandboxed (=noprompt) access to your mic (`socket=pulseaudio`) and cam (`device=all`, which can be used to execute code outside of the sandbox).

**Comment by rusty-snake** [comment]
Same for gnome privacy settings. See https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2231 for example.

**Comment by rjshrjndrn** [comment]
Thank you for the clarification.
