### ISSUE TITLE
Apps installed with custom Flatpak installations are not detected

### ISSUE THREAD

**Issue by RushingAlien** [tchx84/Flatseal#549]
Hello! I have a custom flatpak installation (`man flatpak-installation`). It is defined in `/etc/flatpak/installations.d/oldarch.conf`, with the following content :
```ini
[Installation "oldarch"]
Path=/mnt/oldArch/flatpak/
DisplayName=oldArch Installation
StorageType=harddisk
```
I install apps to it via `flatpak --installation oldarch install app.id`, however, flatseal does not detect apps installed to the oldarch installation. 

Also note that `/home/raambm/.local/share/gnome-builder/flatpak/etc/installations.d` is also a valid path for this, gnome-builder automatically creates this (gnome-builder non-flatpak)

**Comment by rusty-snake** [comment]
Did you followed the [documentation](https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md#enable-custom-installations)?

**Comment by RushingAlien** [comment]
Ah, my bad, should've looked there first, thanks!
Though it is unfortunate that i have to poke the sandbox to get it

What do you think of fetching the flatpak app list with `flatpak-spawn --host flatpak list`?

**Comment by tchx84** [comment]
> Ah, my bad, should've looked there first, thanks! Though it is unfortunate that i have to poke the sandbox to get it
> 
> What do you think of fetching the flatpak app list with `flatpak-spawn --host flatpak list`?

It's more than just getting the list of apps, e.g. it requires accessing metadata files for these apps. As for any Flatpak app, it is preferred it keep it with minimal permissions.
