### ISSUE TITLE
Close button in the wrong place when configured to appear on the left

### ISSUE THREAD

**Issue by furtarball** [tchx84/Flatseal#55]
I have configured my GNOME to show the close button in the upper left corner, but in Flatseal, instead of there, it appears next to the hamburger menu. I believe it has something to do with the split headerbar.
![image](https://user-images.githubusercontent.com/61846505/77695681-70751200-6fac-11ea-8de8-4ac2215790d6.png)

**Comment by tchx84** [comment]
hmm, Ill take a look.
