### ISSUE TITLE
Flatseal does not start without an error message

### ISSUE THREAD

**Issue by ckeller** [tchx84/Flatseal#550]
Hi
I installed Flatseal (`flatpak install flathub com.github.tchx84.Flatseal`), but running it (`flatpak run com.github.tchx84.Flatseal`) does not display anything and does not output any message.
Below is the output of `flatpak run -v com.github.tchx84.Flatseal`.
Thanks for your help!

```
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/artemis/.local/share/flatpak
F: Opening user flatpak installation at path /home/artemis/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/com.github.tchx84.Flatseal/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/artemis/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/44/4078027bba432a34c29220e86e005b05db89371141bee6f58774932a7b27d119/files/lib32 does not exist
F: Cleaning up unused container id 1740464058
F: Cleaning up per-app-ID state for com.github.tchx84.Flatseal
F: Allocated instance id 2812002707
F: Add defaults in dir /com/github/tchx84/Flatseal/
F: Add locks in dir /com/github/tchx84/Flatseal/
F: Disallowing network access
F: Allowing dri access
F: Allowing wayland access
F: Allowing x11 access
F: Running 'bwrap --args 40 xdg-dbus-proxy --args=43'
F: Running 'bwrap --args 40 com.github.tchx84.Flatseal'
```

**Comment by rusty-snake** [comment]
- If you run `flatpak run com.github.tchx84.Flatseal --help` does it show something?
- Do you have other working flatpaks or is flatseal your only flatpak? It might be a problem with your flatpak installation.
- Can you name some system informations like flatpak version, distribution, desktop environment, x11 or wayland, ...

**Comment by ckeller** [comment]
> * If you run `flatpak run com.github.tchx84.Flatseal --help` does it show something?

It does not output anything.

>     * Do you have other working flatpaks or is flatseal your only flatpak? It might be a problem with your flatpak installation.

I run Steam without problem.

>     * Can you name some system informations like flatpak version, distribution, desktop environment, x11 or wayland, ...

I use Debian sid with kernel 6.1.0-8-amd64, openbox, x11, and flatpak 1.14.4.

**Comment by rusty-snake** [comment]
I don't have any real idea except of reboot and `flatpak repair`.

**Comment by ckeller** [comment]
I still have the same symptoms :-(

**Comment by tchx84** [comment]
Very strange... have you ever ran Flatseal before?

Just in case, do this from the terminal:

```
$ flatpak kill com.github.tchx84.Flatseal
$ flatpak -y uninstall com.github.tchx84.Flatseal
$ rm -rf ~/.var/app/com.github.tchx84.Flatseal/
$ rm -rf ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal
$ flatpak --user -y install flathub com.github.tchx84.Flatseal
$ flatpak run com.github.tchx84.Flatseal
```

And re-try...

**Comment by ckeller** [comment]
Same problem... I never used Flatseal before.
As expected, `flatpak kill com.github.tchx84.Flatseal` returned that it was not running. Also, the directory `~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal` did not exist.

**Comment by tchx84** [comment]
> Same problem... I never used Flatseal before. As expected, `flatpak kill com.github.tchx84.Flatseal` returned that it was not running. Also, the directory `~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal` did not exist.

hmm, does this show any error message?

```
$ flatpak run --command=bash com.github.tchx84.Flatseal
$ cd /app/bin/
$ com.github.tchx84.Flatseal 
```

**Comment by ckeller** [comment]
Yes, that `/app/bin` does not exist.

**Comment by tchx84** [comment]
> Yes, that `/app/bin` does not exist.

That's very strange, it means the previous command, to go in the flatpak container, did not work. This means, something is failing way before Flatseal even runs.

**Comment by ckeller** [comment]
Ok, I can report to Flatpak

**Comment by dnet890** [comment]
me too flatseal does not start on Ubuntu 22.04 and downgrade it does not worked

**Comment by tchx84** [comment]
> me too flatseal does not start on Ubuntu 22.04 and downgrade it does not worked

Can you try this from the terminal ?

```
$ flatpak kill com.github.tchx84.Flatseal

$ rm -rf ~/.var/app/com.github.tchx84.Flatseal/
$ rm ~/.local/share/flatpak/overrides/global
$ rm ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal

$ flatpak run com.github.tchx84.Flatseal
```

**Comment by dnet890** [comment]
@tchx84 Hi
I got this message and it just stuck. What do you think? 

<img width="858" alt="image" src="https://github.com/tchx84/Flatseal/assets/29157187/8df0cd95-a5a6-47fa-95fc-c7f65e36792e">
<img width="923" alt="image" src="https://github.com/tchx84/Flatseal/assets/29157187/ae769690-6f2e-4424-8f28-533f8c6c2f23">

**Comment by tchx84** [comment]
> @tchx84 Hi I got this message and it just stuck. What do you think?
> 
> <img alt="image" width="858" src="https://user-images.githubusercontent.com/29157187/273425441-8df0cd95-a5a6-47fa-95fc-c7f65e36792e.png"> <img alt="image" width="923" src="https://user-images.githubusercontent.com/29157187/273425449-ae769690-6f2e-4424-8f28-533f8c6c2f23.png">

This is quite strange... it seems to suggest your setup does not support file monitoring. 

Can you try this branch https://github.com/tchx84/Flatseal/pull/608 , follow these instructions https://github.com/tchx84/Flatseal/pull/608 ?

**Comment by dnet890** [comment]
Sorry do you mean I need to modify the file src/models/applications.js?

**Comment by tchx84** [comment]
> Sorry do you mean I need to modify the file src/models/applications.js?

Nope, what I meant is that you should build Flatseal with a fix I am trying (in the blind, because I can't reproduce this), by following these commands:

```
git clone https://github.com/tchx84/Flatseal.git
cd Flatseal
git checkout exploring-issue-550
flatpak --user install org.gnome.{Platform,Sdk}//45
flatpak-builder --user --force-clean --install build com.github.tchx84.Flatseal.json
flatpak --user run --branch=master com.github.tchx84.Flatseal
```

**Comment by dnet890** [comment]
Hi
I already installed org.gnome.{Platform,Sdk}//45. But, the thing that is not found on the flathub. What do you think?

<img width="762" alt="image" src="https://github.com/tchx84/Flatseal/assets/29157187/cdd11b9d-b7a3-4217-84cc-87cde1e30061">
<img width="473" alt="image" src="https://github.com/tchx84/Flatseal/assets/29157187/d1be64de-2f94-4be6-932c-c984f482da39">

**Comment by koriit-kontakt** [comment]
Hi, I'm experiencing the same issue as @dtantono . I was already running flatseal just fine in my setup, the only thing that really changed since I last opened it is that I have encrypted my home dir with ecryptfs. Could it be the root cause?

**Comment by rusty-snake** [comment]
If other flatpaks Start fine I don't think so.

**Comment by tchx84** [comment]
> Hi, I'm experiencing the same issue as @dtantono . I was already running flatseal just fine in my setup, the only thing that really changed since I last opened it is that I have encrypted my home dir with ecryptfs. Could it be the root cause?

HI @koriit-kontakt,  Sadly, I can't reproduce this and therefore I am in the dark here, can you test this fix?

Just run the following commands on your terminal:

```
git clone https://github.com/tchx84/Flatseal.git
cd Flatseal
git checkout exploring-issue-550
flatpak --user install org.gnome.{Platform,Sdk}//45
flatpak-builder --user --force-clean --install build com.github.tchx84.Flatseal.json
flatpak --user run --branch=master com.github.tchx84.Flatseal
```

**Comment by koriit-kontakt** [comment]
@tchx84 Good news! I was able to run it from the branch and it works! Thanks!

Though the commands I had to run were:
```
git clone https://github.com/tchx84/Flatseal.git
cd Flatseal 
git checkout exploring-issue-550
flatpak install flathub 'org.gnome.Platform//45'
flatpak install flathub 'org.gnome.Sdk//45' 
flatpak install flathub org.flatpak.Builder
sudo apt install flatpak-builder
flatpak-builder --user --force-clean --install build com.github.tchx84.Flatseal.json
flatpak --user run --branch=master com.github.tchx84.Flatseal
```

This is the full console output:
```
$ flatpak --user run --branch=master com.github.tchx84.Flatseal

(com.github.tchx84.Flatseal:2): GLib-GIO-WARNING **: 20:26:19.225: Failed to create file monitor for /home/olek/.var/app/com.github.tchx84.Flatseal/config/glib-2.0/settings/keyfile: Unable to find default local file monitor type

(com.github.tchx84.Flatseal:2): Gjs-WARNING **: 20:26:19.227: JS ERROR: Gio.IOErrorEnum: Unable to find default local file monitor type
_setup/<@resource:///com/github/tchx84/Flatseal/js/models/applications.js:52:38
_setup@resource:///com/github/tchx84/Flatseal/js/models/applications.js:48:39
_init@resource:///com/github/tchx84/Flatseal/js/models/applications.js:39:14
FlatpakApplicationsModel@resource:///com/github/tchx84/Flatseal/js/models/applications.js:36:4
getDefault@resource:///com/github/tchx84/Flatseal/js/models/applications.js:402:24
_init@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:105:43
FlatpakPermissionsModel@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:97:4
getDefault@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:441:24
_setup@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:85:41
_init@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:75:14
FlatsealWindow@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:72:4
vfunc_activate@resource:///com/github/tchx84/Flatseal/js/application.js:105:28
main@resource:///com/github/tchx84/Flatseal/js/main.js:34:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/app/bin/com.github.tchx84.Flatseal:9:17


(com.github.tchx84.Flatseal:2): Gjs-WARNING **: 20:26:19.227: JS ERROR: Gio.IOErrorEnum: Unable to find default local file monitor type
_setup/<@resource:///com/github/tchx84/Flatseal/js/models/applications.js:52:38
_setup@resource:///com/github/tchx84/Flatseal/js/models/applications.js:48:39
_init@resource:///com/github/tchx84/Flatseal/js/models/applications.js:39:14
FlatpakApplicationsModel@resource:///com/github/tchx84/Flatseal/js/models/applications.js:36:4
getDefault@resource:///com/github/tchx84/Flatseal/js/models/applications.js:402:24
_init@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:105:43
FlatpakPermissionsModel@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:97:4
getDefault@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:441:24
_setup@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:85:41
_init@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:75:14
FlatsealWindow@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:72:4
vfunc_activate@resource:///com/github/tchx84/Flatseal/js/application.js:105:28
main@resource:///com/github/tchx84/Flatseal/js/main.js:34:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/app/bin/com.github.tchx84.Flatseal:9:17
```

**Comment by tchx84** [comment]
> @tchx84 Good news! I was able to run it from the branch and it works! Thanks!
> 
> Though the commands I had to run were:
> 
> ```
> git clone https://github.com/tchx84/Flatseal.git
> cd Flatseal 
> git checkout exploring-issue-550
> flatpak install flathub 'org.gnome.Platform//45'
> flatpak install flathub 'org.gnome.Sdk//45' 
> flatpak install flathub org.flatpak.Builder
> sudo apt install flatpak-builder
> flatpak-builder --user --force-clean --install build com.github.tchx84.Flatseal.json
> flatpak --user run --branch=master com.github.tchx84.Flatseal
> ```
> 
> This is the full console output:
> 
> ```
> $ flatpak --user run --branch=master com.github.tchx84.Flatseal
> 
> (com.github.tchx84.Flatseal:2): GLib-GIO-WARNING **: 20:26:19.225: Failed to create file monitor for /home/olek/.var/app/com.github.tchx84.Flatseal/config/glib-2.0/settings/keyfile: Unable to find default local file monitor type
> 
> (com.github.tchx84.Flatseal:2): Gjs-WARNING **: 20:26:19.227: JS ERROR: Gio.IOErrorEnum: Unable to find default local file monitor type
> _setup/<@resource:///com/github/tchx84/Flatseal/js/models/applications.js:52:38
> _setup@resource:///com/github/tchx84/Flatseal/js/models/applications.js:48:39
> _init@resource:///com/github/tchx84/Flatseal/js/models/applications.js:39:14
> FlatpakApplicationsModel@resource:///com/github/tchx84/Flatseal/js/models/applications.js:36:4
> getDefault@resource:///com/github/tchx84/Flatseal/js/models/applications.js:402:24
> _init@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:105:43
> FlatpakPermissionsModel@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:97:4
> getDefault@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:441:24
> _setup@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:85:41
> _init@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:75:14
> FlatsealWindow@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:72:4
> vfunc_activate@resource:///com/github/tchx84/Flatseal/js/application.js:105:28
> main@resource:///com/github/tchx84/Flatseal/js/main.js:34:24
> run@resource:///org/gnome/gjs/modules/script/package.js:206:19
> @/app/bin/com.github.tchx84.Flatseal:9:17
> 
> 
> (com.github.tchx84.Flatseal:2): Gjs-WARNING **: 20:26:19.227: JS ERROR: Gio.IOErrorEnum: Unable to find default local file monitor type
> _setup/<@resource:///com/github/tchx84/Flatseal/js/models/applications.js:52:38
> _setup@resource:///com/github/tchx84/Flatseal/js/models/applications.js:48:39
> _init@resource:///com/github/tchx84/Flatseal/js/models/applications.js:39:14
> FlatpakApplicationsModel@resource:///com/github/tchx84/Flatseal/js/models/applications.js:36:4
> getDefault@resource:///com/github/tchx84/Flatseal/js/models/applications.js:402:24
> _init@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:105:43
> FlatpakPermissionsModel@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:97:4
> getDefault@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:441:24
> _setup@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:85:41
> _init@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:75:14
> FlatsealWindow@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:72:4
> vfunc_activate@resource:///com/github/tchx84/Flatseal/js/application.js:105:28
> main@resource:///com/github/tchx84/Flatseal/js/main.js:34:24
> run@resource:///org/gnome/gjs/modules/script/package.js:206:19
> @/app/bin/com.github.tchx84.Flatseal:9:17
> ```

Excellent, I will merge that fix and make a release soon. Thanks for testing it.

**Comment by koriit-kontakt** [comment]
> If other flatpaks Start fine I don't think so.

Yea, Chrome works just fine.

**Comment by tchx84** [comment]
Closing this as I just merged the fix to master.
