### ISSUE TITLE
[Feature Request] Allow explicit override of existing permissions

### ISSUE THREAD

**Issue by mooreye** [tchx84/Flatseal#551]
For example, you can't make a global (All Applications) override by setting "All system files" to unchecked. It is unchecked by default, but that means it's not actually written to `global` override file, and if any app adds `filesystem=host` to its permissions in the future, it will have this permission because the "All system files" is implicitly set to "no", not explicitly - I hope you know what I mean.

**Comment by tchx84** [comment]
hey @mooreye , yes, I know exactly what you mean. 

For the **specific** example that you shown, you can do this and it will actually do what you want.

![image](https://github.com/tchx84/Flatseal/assets/481418/d8f3f806-bc14-4021-8b55-c2ad5bb487c0)

But, as for a **general** case, it's a hard limitation of how permissions models were designed. It would require a very _big_ refactor to change this. Which I can't afford to do at the moment.

I am not closed to the idea, but unless someone steps in and do it _properly_, it will have to wait until I can do it myself in the future.

**Comment by mooreye** [comment]
Thank you, that indeed works.
