### ISSUE TITLE
Feature Request: Select last changed/seen application on launch

### ISSUE THREAD

**Issue by FOSSProponent9436** [tchx84/Flatseal#556]
I often open flatseal multiple times when setting and testing permissions on an app. I could leave it open but it is by habit.

I find it a bit jarring when flatseal starts at the first app alphabetically on launching it, to the point where I sometimes almost set permissions on the first app accidentally when I meant to change another app.

I think it would be better if the application first selected in the list was the one that was last selected in the previous session, or the one which last had its permissions changed.

An alternative would be to not show the right side of the menu (where you change permissions) at all until an app has been selected from the list. Because it is statistically unlikely that the user would want to do something with the first app in the list every time they use it. And the first app is not more important than any other app by being at the top when sorted alphabetically.

Perhaps you could go further and add sorting options to the app list. E.g. alphabetically, last set, most recently installed etc. each with ascending and descending options. But that is not necessary to fix this issue.

**Comment by tchx84** [comment]
Something similar is planned as part of another feature I am working on, so it's likely to happen :+1:
