### ISSUE TITLE
[Bug] Flatseal won't launch because of invalid Key file line

### ISSUE THREAD

**Issue by MelonenBiber** [tchx84/Flatseal#558]
The flatseal gui won't show at all, but the process is active in the background.

This is all the output when run in the commandline
```
➜  ~ flatpak run com.github.tchx84.Flatseal

(com.github.tchx84.Flatseal:2): Gjs-CRITICAL **: 20:39:03.772: JS ERROR: GLib.KeyFileError: Key file contains line “;~/.local/share/applications ” which is not a key-value pair, group, or comment
_loadPermissionsForPath@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:130:17
_loadOverrides@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:194:26
_setup@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:276:14
set appId@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:339:14
_updatePermissions@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:279:9
_setup@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:220:14
_init@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:76:14
FlatsealWindow@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:73:4
vfunc_activate@resource:///com/github/tchx84/Flatseal/js/application.js:105:28
main@resource:///com/github/tchx84/Flatseal/js/main.js:34:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/app/bin/com.github.tchx84.Flatseal:9:17
```

The interesting part seems to be 
```(com.github.tchx84.Flatseal:2): Gjs-CRITICAL **: 20:39:03.772: JS ERROR:
GLib.KeyFileError: Key file contains line “;~/.local/share/applications ”
which is not a key-value pair, group, or comment
```
where `~/.local/share/applications` is a path i remember adding for `com.valvesoftware.Steam`.
As I'm not familiar with how flatpak / flatseal works the only thing I've tried is
```
flatpak override --reset com.valvesoftware.Steam
```
which did not fix the issue.

**Comment by MelonenBiber** [comment]
All flatpak / flatseal settings I ever changed were inside the flatpak gui, which should not allow me to register invalid settings, assuming that's the problem. I never edited any config file (?) directly that could have caused this error.

**Comment by rusty-snake** [comment]
Got to `~/.local/share/flatpak/overrides` and use the standard way (`ls`, `grep`, `cat`, ...) to check all files there for this path.

**Comment by MelonenBiber** [comment]
Ok the error originates from Android Studio not Steam like I thought before.

```
➜  overrides cat com.google.AndroidStudio
[Context]
persistent=~/.local/share/icons
;~/.local/share/applications 

```

**Comment by MelonenBiber** [comment]
Removing `com.google.AndroidStudio` temporarily fixes this issue for me.

**Comment by rusty-snake** [comment]
I can confirm that flatseal allows you to save a "~/.testing\n" path in `persistent` (did not tested filesystem; used `echo "~/.testing" | wl-copy`). And that flatseal (after re-opening it) can not navigate to the affected flatpak. For me it does not crash.

**Comment by MelonenBiber** [comment]
Can confirm this aswell, just copying and pasting two lines seems to do the trick.
Flatseal should not allow linebreaks to be saved and either show an error message or create an entry per line.

**Comment by tchx84** [comment]
Thanks for the report, Ill dig deeper into this.

**Comment by tchx84** [comment]
@MelonenBiber @rusty-snake can someone write detailed steps to reproduce this? Including the input I should be pasting to Flatseal?

I have been trying to reproduce this, but I can't.

**Comment by rusty-snake** [comment]
(In flatseal) add two persistent path. First add one then add a second one. The input field is above the first path. This second path must end with a newline character so copy it somewhere (see above comment) and paste it. Now close the flatseal window. Open flatseal again, try to navigate to the flatpak. Except: error in terminal/syslog and app permission view does not load/open.

**Comment by MelonenBiber** [comment]
Copy text with a newline
```
test
test
```

paste it into persistent file paths (of Android Studio in my example)

![image](https://github.com/tchx84/Flatseal/assets/45320352/dd834047-ea39-40e8-85d3-4580b6a4bd9a)

check that the ~/.local/share/flatpak/overrides/com.google.AndroidStudio file now contains the newline
```
➜  overrides cat com.google.AndroidStudio 
[Context]
persistent=test
test
```
and Flatseal won't run anymore
```
➜  overrides flatpak run com.github.tchx84.Flatseal 

(com.github.tchx84.Flatseal:2): Gjs-CRITICAL **: 02:47:31.613: JS ERROR: GLib.KeyFileError: Key file contains line “test” which is not a key-value pair, group, or comment
_loadPermissionsForPath@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:130:17
_loadOverrides@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:194:26
_setup@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:276:14
set appId@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:339:14
_updatePermissions@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:279:9
_setup@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:220:14
_init@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:76:14
FlatsealWindow@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:73:4
vfunc_activate@resource:///com/github/tchx84/Flatseal/js/application.js:105:28
main@resource:///com/github/tchx84/Flatseal/js/main.js:34:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/app/bin/com.github.tchx84.Flatseal:9:17
```

**Comment by tchx84** [comment]
@rusty-snake @MelonenBiber thanks
