### ISSUE TITLE
No applications found

### ISSUE THREAD

**Issue by seahorse41** [tchx84/Flatseal#559]
I see my issue is just like #502 but I can't figure out what directory to set.
My initial installation of flatpak failed due to root partition ran out of space. Needs over 2Gb
Moved what I got so far to the largest partition, created a symlink to replace it, and started over.
▶ ~ ▶sandreas@roxy10-debian11-x64▶
$ ls -ld /var/lib/flatpak
lrwxrwxrwx 1 root root 26 Jul 24 14:40 /var/lib/flatpak -> /usr/share/audvid/flatpak/

I successfully installed the applications I wanted:
▶$ ls -l /var/lib/flatpak/app
total 12
drwxr-xr-x 3 root 4096 2023-07-24 09:25 org.libreoffice.LibreOffice/
drwxr-xr-x 3 root 4096 2023-07-29 16:12 org.gnome.Evince/
drwxr-xr-x 3 root 4096 2023-07-29 16:39 com.github.tchx84.Flatseal/
▶$ flatpak list
`Name                                    Application ID                        Version      Branch        Installation
Flatseal                                com.github.tchx84.Flatseal            2.0.2        stable        system
Freedesktop Platform                    org.freedesktop.Platform              22.08.12.1   22.08         system
Mesa                                    org.freedesktop.Platform.GL.default   23.1.1       22.08         system
Mesa (Extra)                            org.freedesktop.Platform.GL.default   23.1.1       22.08-extra   system
openh264                                org.freedesktop.Platform.openh264     2.1.0        2.2.0         system
Document Viewer                         org.gnome.Evince                      44.3         stable        system
GNOME Application Platform version 44   org.gnome.Platform                                 44            system
LibreOffice                             org.libreoffice.LibreOffice           7.5.5.2      stable        system`

So the apps are installed. But can't load any files due to sandbox, and home is a separate partition. Installed Flatseal,
Start Flatseal, No Applications Found. Search for solutions. From those I have the first configuration showing:
▶$ flatpak info -M com.github.tchx84.Flatseal
[Context]
shared=ipc;
sockets=x11;wayland;fallback-x11;
devices=dri;
filesystems=xdg-data/flatpak/overrides:create;/var/lib/flatpak/app:ro;xdg-data/flatpak/app:ro;

[Session Bus Policy]
org.gnome.Software=talk
org.freedesktop.impl.portal.PermissionStore=talk

▶$ cat ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal 
[Context]
filesystems=host:ro;/usr/local/var/lib/flatpak;

[Environment]
FLATPAK_SYSTEM_DIR=/usr/local/var/lib/flatpak

I might have already tried the host:ro by the time I copied this, but important thing is the directories it points to.
▶Aug23_0953.19▶ ~ ▶sandreas@roxy10-debian11-x64▶0▶
$ ls /usr/local/var/lib/flatpak
ls: cannot access '/usr/local/var/lib/flatpak': No such file or directory

▶$ ls /var/home/user/.flatpak
ls: cannot access '/var/home/user/.flatpak': No such file or directory

So the directories it choose by default do not exist on my Debian system.
▶$ flatpak info --show-location com.github.tchx84.Flatseal
/var/lib/flatpak/app/com.github.tchx84.Flatseal/x86_64/stable/627f4091cfc8c6af3d51034c388c6bf7bcea341399ca49ca2b28590aee60a6c1

▶$ ls -l /usr/share/audvid/flatpak/
total 24
drwxr-xr-x  4 root 4096 2023-07-24 09:25 exports/
drwxr-xr-x  3 root 4096 2023-07-29 15:46 appstream/
drwxr-xr-x 10 root 4096 2023-07-29 16:12 runtime/
drwxr-xr-x  5 root 4096 2023-07-29 16:39 app/
drwxr-xr-x  7 root 4096 2023-07-29 16:39 repo/
drwxr-xr-x  2 root 4096 2023-08-15 14:49 overrides/

▶$ mcedit ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal
[Context]
filesystems=xdg-data/flatpak/overrides:create;host:ro;/usr/share/audvid/flatpak;

[Environment]
FLATPAK_SYSTEM_DIR=/usr/share/audvid/flatpak
FLATPAK_USER_DIR=/home/sandreas/.flatpak

Not sure where the USER_DIR is supposed to be, I've tried various ways without any difference, including same as SYSTEM_DIR.
▶$ flatpak info -M com.github.tchx84.Flatseal
[Context]
shared=ipc;
sockets=x11;wayland;fallback-x11;
devices=dri;
filesystems=xdg-data/flatpak/overrides:create;/usr/share/audvid/flatpak;host:ro;/var/lib/flatpak/app:ro;xdg-data/flatpak/app:ro;

[Session Bus Policy]
org.gnome.Software=talk
org.freedesktop.impl.portal.PermissionStore=talk

[Environment]
FLATPAK_SYSTEM_DIR=/usr/share/audvid/flatpak
FLATPAK_USER_DIR=/home/sandreas/.flatpak

Still No Applications Found
▶$ cat /etc/debian_version 
11.7

I've included all the settings queries that have been asked in other similar issues.
What am I missing?

Thank you

**Comment by rusty-snake** [comment]
FWIW: Inspect filesystem view of a flatpak with `flatpak run --command=bash <APP-ID>`.

`/usr` (and `/app`) is somewhat special. As the `/usr` in a flatpak will always be it's runtime. The host's `/usr` will, if granted, appear under `/var/run/host`. See https://docs.flatpak.org/en/latest/sandbox-permissions.html.

**Comment by tchx84** [comment]
@seahorse41 I would suggest to:

1. Use Flatpak's [custom installation](https://docs.flatpak.org/en/latest/tips-and-tricks.html#adding-a-custom-installation) approach to handle the scenario you're describing, properly.
2. Then, use Flatseal's support for [custom installation](https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md#enable-custom-installations).

If you still want to pursue that way of handling this, you should probably follow what @rusty-snake described, but something else could break later.

**Comment by seahorse41** [comment]
@rusty-snake That helps me see it can not see the mounted partition, but can't make it accept it.
$ flatpak run --command=bash com.github.tchx84.Flatseal
1416.38 system$ df
/dev/sda14     892527364 792994900  99516080  89% /usr
shows the partition mounted at /usr instead of /usr/share/audvid
1523.02 ~$ ls -l /usr/share/audvid
ls: cannot access '/usr/share/audvid': No such file or directory

$ flatpak run --command=bash --filesystem=/usr/share/audvid/flatpak com.github.tchx84.Flatseal
1442.29 ~$ ls -l /usr/share/audvid
ls: cannot access '/usr/share/audvid': No such file or directory

same for --persist=/usr/share/audvid/flatpak
and --persist=/var/lib

@tchx84 trying the other way, I created the file
/etc/flatpak/installations.d/extra.conf
Path=/usr/share/audvid/flatpak/

$ flatpak --installation=extra remote-add flathub https://flathub.org/repo/flathub.flatpakrepo
error: Remote flathub already exists

Is that only going to work if I erase everything and start over?
I intended it to be installed system-wide, but can accept some other scope to only one user.

I think this is more a flatpak problem, maybe I should take this issue over there?

Thank you for your help.

**Comment by rusty-snake** [comment]
> --filesystem=/usr/share/audvid/flatpak

`/usr` will always be the runtime. There is no `--filesystem=/usr`. If you want to access the host's `/usr`, `--filesystem=host-os` which will  mount it under `/var/run/host`. Read the link from above.

> --persist=/usr/share/audvid/flatpak

Persist is always a `$HOME` relative path.

**Comment by rusty-snake** [comment]
> error: Remote flathub already exists

Read the error. 

Better test `flatpak --installation=extra run APP`.

**Comment by seahorse41** [comment]
> Better test `flatpak --installation=extra run APP`.

I'm just showing it isn't a solution for Flatseal by itself.
The quoted command also gives No applications found.

However this does work for Evince, so I can access those directories now. Thanks.

I did read the error, and all the pages referenced, 
With extra included, all apps are in the list twice. I'm sure I need to uninstall everything and start over differently.
When I removed Libreoffice, it asked to remove 1, 2 or both, then gave an error that 2nd was not there. I'm sure this layout isn't what was intended.
`$ flatpak list
Name                                    Application ID                        Version     Branch       Installation
Flatseal                                com.github.tchx84.Flatseal            2.0.2       stable       system
Flatseal                                com.github.tchx84.Flatseal            2.0.2       stable       system (extra)
Freedesktop Platform                    org.freedesktop.Platform              22.08.12.1  22.08        system
Freedesktop Platform                    org.freedesktop.Platform              22.08.12.1  22.08        system (extra)
Mesa                                    org.freedesktop.Platform.GL.default   23.1.1      22.08        system
Mesa                                    org.freedesktop.Platform.GL.default   23.1.1      22.08        system (extra)
Mesa (Extra)                            org.freedesktop.Platform.GL.default   23.1.1      22.08-extra  system
Mesa (Extra)                            org.freedesktop.Platform.GL.default   23.1.1      22.08-extra  system (extra)
openh264                                org.freedesktop.Platform.openh264     2.1.0       2.2.0        system
openh264                                org.freedesktop.Platform.openh264     2.1.0       2.2.0        system (extra)
Document Viewer                         org.gnome.Evince                      44.3        stable       system
Document Viewer                         org.gnome.Evince                      44.3        stable       system (extra)
GNOME Application Platform version 44   org.gnome.Platform                                44           system
GNOME Application Platform version 44   org.gnome.Platform                                44           system (extra)`

**Comment by seahorse41** [comment]
Found a solution.
▶$ nano ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal
[Context]
filesystems=/run/host/run/host/usr/share/audvid/flatpak;/run/host/usr/share/audvid/flatpak;xdg-data/flatpak/overrides:create;host:ro;

[Environment]
FLATPAK_SYSTEM_DIR=/run/host/usr/share/audvid/flatpak
FLATPAK_USER_DIR=/run/host/usr/share/audvid/flatpak

Now I have applications.

**Comment by tchx84** [comment]
Good to hear! 

Whenever you feel like it, try the custom installations as it's the proper approach here.
