### ISSUE TITLE
pop up when application try grab permission

### ISSUE THREAD

**Issue by leslielg** [tchx84/Flatseal#560]
chrome web browser requires ~/.local/share folder write access to install some thing, it pops a window indicate that I can add those folders in flatseal, but a more convenient and user friend way is flatseal directly pop up a window to ask my agree to grab required permision by this application, just like smart phone do, and flatseal changes config files in background by itself.

**Comment by tchx84** [comment]
> chrome web browser requires ~/.local/share folder write access to install some thing, it pops a window indicate that I can add those folders in flatseal, but a more convenient and user friend way is flatseal directly pop up a window to ask my agree to grab required permision by this application, just like smart phone do, and flatseal changes config files in background by itself.

Hi,

I understand what you mean, and the right solution for this scenario is for the web browser to use portals to request such permission directly, without any involvement of a third party application like Flatseal.

I haven't checked recently, but there were technical limitations on the portals side which prevented this use case, but I am sure these limitations will be overcome soon (if they haven't already).

Therefore, this is something that should be discussed with the web browser devs.
