### ISSUE TITLE
Feature Request: Ability to back-up permission settings

### ISSUE THREAD

**Issue by AtFreezingPoint** [tchx84/Flatseal#569]
As title says, the ability to export & import settings would be a life-saver for certain use-cases.

**Comment by rusty-snake** [comment]
`cp -r ~/.local/share/flatpak/overrides /backups/flatpak-overrides`


A GUI for it (or a open in file-manager) would be nice, agree.

**Comment by AtFreezingPoint** [comment]
> `cp -r ~/.local/share/flatpak/overrides /backups/flatpak-overrides`
> 
> A GUI for it (or a open in file-manager) would be nice, agree.

Yeah the whole idea of the app is to like provide a GUI for that type of stuff i'd say lol

**Comment by Jopp-gh** [comment]
+1 for this FR

**Comment by tchx84** [comment]
Many of these use cases are related to replicating environments, e.g, multiple machines in a university laboratory. For those cases I suggest using https://gitlab.gnome.org/Cogitri/flatsync and help with https://gitlab.gnome.org/Cogitri/flatsync/-/issues/16
