### ISSUE TITLE
UI is unusable when Dark Mode is enabled

### ISSUE THREAD

**Issue by jhaygood86** [tchx84/Flatseal#6]
When GNOME's Dark Mode is enabled, the UI is basically completely unusable:

![Screenshot from 2020-01-30 15-45-30](https://user-images.githubusercontent.com/360393/73488795-9351c400-4377-11ea-80bb-5dbaece51121.png)

**Comment by tchx84** [comment]
Already fixed on master. The fix will be available in the next release. Can you help me test it? You can build it from master with the README instructions.

EDIT: I will leave this issue opened, since I suspect more reports will come.

**Comment by tchx84** [comment]
The fix is available now. Just update the application.
