### ISSUE TITLE
Dynamic sidebar width

### ISSUE THREAD

**Issue by bertob** [tchx84/Flatseal#604]
Libadwaita 1.4 allows for dynamic sidebar widths, so you can shrink windows to relatively small sizes without folding, avoiding awkward cases like this:

![image](https://github.com/tchx84/Flatseal/assets/1908896/2bb1370c-b40a-4433-b687-565388005fb2)

Settings for comparison, using a dynamic sidebar width:

![image](https://github.com/tchx84/Flatseal/assets/1908896/ec93a078-758e-4d06-843d-b87c2766b858)

**Comment by tchx84** [comment]
Hey @bertob , if we can find a good combination of parameters, sure!

I quickly tried that before and ended up with something like this:

![Screenshot from 2023-09-29 06-16-07](https://github.com/tchx84/Flatseal/assets/481418/c610477b-122c-47ed-9861-cf67709e46d7)

To which I (quickly, as well) concluded that:

1. It didn't look good.
2. Felt not too useful having all that information ellipsized (but, a problem that could be addressed separately).

At some point having the window displaying the sidebar only it's kind of unavoidable, I wonder what window size you think it wouldn't be considered awkward.

Another thing didn't look good was the default sidebar minimum width

![Screenshot from 2023-09-29 06-25-12](https://github.com/tchx84/Flatseal/assets/481418/1fcc2d5d-f4c4-4d6d-a447-98367ba8a7b0)

That is, considering that Flatseal displays often long app names and long app ids (compared to Settings).

Any suggestions? :)

**Comment by bertob** [comment]
I don't think ellipsizing the name or ID is necessarily a problem here. All of this information is available on the detail view as well anyway, finding the app you're looking for should never be a problem I think.

As for the exact values, I'd try the ones Nautilus or Settings use as a start and iterate from there.
