### ISSUE TITLE
Drop sidebar active state when folded

### ISSUE THREAD

**Issue by bertob** [tchx84/Flatseal#606]
When the split view is folded, there shouldn't be an active element.

![image](https://github.com/tchx84/Flatseal/assets/1908896/dfd593ac-1cb9-45ff-8d23-fb6c2e0c7eec)

**Comment by tchx84** [comment]
You mean when you first open the application?

**Comment by bertob** [comment]
Ah yes, looks like it only happens when you first open the app.
