### ISSUE TITLE
hi, questions regarding flatseal and flatpak

### ISSUE THREAD

**Issue by DOOMMARINE117** [tchx84/Flatseal#609]
im wondering on flatseals. after you install flatpak first, then install flatseal, then install flatseal from flathub.

after you do that. you install a program. like say: "bluemail".

when you do, you can find it in the whisky menu in arch.

so im curious. after you select to add to panel, it shows icon. when selecting add to desktop the icon dont show on desktop.

how to fix it if possible?

**Comment by rusty-snake** [comment]
If you post the same issue in multiple repos you should at least cross link them.

**Comment by rusty-snake** [comment]
To rephrase your STR:

- Install Arch with Xfce
- install flatpak
- install flatseal from AUR
- install flatseal from flathub
- install any flatpak
- try to create a desktop shortcut
- ~/Desktop is empty

**Comment by DOOMMARINE117** [comment]
> To rephrase your STR:
> 
>     * Install Arch with Xfce
> 
>     * install flatpak
> 
>     * install flatseal from AUR
> 
>     * install flatseal from flathub
> 
>     * install any flatpak
> 
>     * try to create a desktop shortcut
> 
>     * ~/Desktop is empty

oops, didnt realize they were all by the same person. lol. 

i figured they were all different devs of repos. oops. my bad. 

should i close the other one then?

how should i fix the no icon thing for the file?

**Comment by tchx84** [comment]
I don't think this can be solved from Flatseal's side, this seems more of a desktop issue.
