### ISSUE TITLE
Custom values under "Persistant" can end up being impossible to remove due to a greyed-out X, forcing you to click "Reset" instead

### ISSUE THREAD

**Issue by NintendoManiac64** [tchx84/Flatseal#616]
This is a really weird one since, as demonstrated in the below video, it actually didn't occur initially, but then *did* occur when attempting it again.

Tested using the live ISO of Linux Mint 21.2 Cinnamon; jump ahead to the 15 minute mark if you want to skip the installation process (included just to fully demonstrate the entire process I went through for easy reproducibility).

[video.webm](https://github.com/tchx84/Flatseal/assets/11896003/3c981d42-f26b-4648-a046-975b12826ee7)

**Comment by tchx84** [comment]
This is fixed on master now, it will be available soon with the new release.
