### ISSUE TITLE
flat seal is not starting with JS ERROR

### ISSUE THREAD

**Issue by mabod** [tchx84/Flatseal#618]
flatseal 2.2.1 is not starting anymore on my EndeavourOS system

there is no error message on the console. It just returns to the prompt immediately. In the journal I see this:

```
Nov 29 13:19:52 rakete com.github.tchx[36467]: JS ERROR: TypeError: component.get_developer_name is not a function
                                               getAppDataForAppId@resource:///com/github/tchx84/Flatseal/js/models/applications.js:318:23
                                               getAll/<@resource:///com/github/tchx84/Flatseal/js/models/applications.js:356:34
                                               getAll@resource:///com/github/tchx84/Flatseal/js/models/applications.js:355:21
                                               _setupApplications@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:145:52
                                               _setup@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:130:14
                                               _init@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:75:14
                                               FlatsealWindow@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:72:4
                                               vfunc_activate@resource:///com/github/tchx84/Flatseal/js/application.js:105:28
                                               main@resource:///com/github/tchx84/Flatseal/js/main.js:34:24
                                               @/usr/bin/com.github.tchx84.Flatseal:9:17
```

Packages installed:

```
flatseal 2.1.0-1
flatpak 1:1.15.6-1
flatpak-builder 1.2.3-2
gjs 2:1.78.0-4
webkitgtk-6.0 2.42.2-1
```
Any idea what the issue is? How can I debug this any further?

**EDIT:**
In the meantime I also tried the flatpak version of flatseal. I followed the installation instruction givene here on github:

```
git clone https://github.com/tchx84/Flatseal.git
cd Flatseal
flatpak --user install org.gnome.{Platform,Sdk}//45
flatpak-builder --user --force-clean --install build com.github.tchx84.Flatseal.json
flatpak --user run --branch=master com.github.tchx84.Flatseal
```

The result is the same. The app does not start. It returns immediately to the prompt and the JS ERROR shows up in the journal.

**Comment by tchx84** [comment]
This is a problem caused by some API breakages in AppStream dependency... can you clarify a couple things?

1. Can you double check again the Flatseal version? The lastest version is 2.1.0, there no 2.2.1 version.

2. This issue should not affect the Flatpak version, since the GNOME runtime still uses the old AppStream version... so I am a bit confused... Can you run `$ flatpak kill com.github.tchx84.Flatseal` before running it? Just to make sure there's not another broken instance already running.

**Comment by yselkowitz** [comment]
see https://github.com/tchx84/Flatseal/pull/617

**Comment by AtmosphericIgnition** [comment]
I'm having the same problem, I tried both building Flatseal from the AUR, and installing it as a Flatpak, but I'm having the same issue on with both installation methods. When I go into the system logs, I always see two things right after trying to start Flatseal from my DE:

`Started app-flatpak-com.github.tchx84.Flatseal-89990.scope.`

Followed, less than a second later by:

`JS ERROR: TypeError: component.get_developer_name is not a function
getAppDataForAppId@resource:///com/github/tchx84/Flatseal/js/models/applications.js:318:23
getAll/<@resource:///com/github/tchx84/Flatseal/js/models/applications.js:356:34
getAll@resource:///com/github/tchx84/Flatseal/js/models/applications.js:355:21
_setupApplications@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:145:52
_setup@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:130:14
_init@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:75:14
FlatsealWindow@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:72:4
vfunc_activate@resource:///com/github/tchx84/Flatseal/js/application.js:105:28
main@resource:///com/github/tchx84/Flatseal/js/main.js:34:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/usr/bin/com.github.tchx84.Flatseal:9:17`

When I try and run `flatpak run com.github.tchx84.Flatseal`, seemingly nothing happens, but when I open the system monitor on my DE, I can see that the process "com.github.tchx84.Flatseal" is active, but sleeping with 44.9 MB of memory in use, but the graphical interface is not showing up. When I try and kill it with `flatpak kill com.github.tchx84.Flatseal`, I get `error: com.github.tchx84.Flatseal is not running`, despite the process still showing up.

I then went and used the "terminate" option in the Gnome System Monitor on the process, tried launching Flatseal again, and everything starts working as expected. This time, when Flatseal is running correctly, I also see that there are two other processes associated with it (2x bwrap), which weren't there when I was having issues.

I have also been able to replicate this problem on a different system running the latest version of Fedora 39, but on that system, the problem only happened when I installed Flatseal as a Flatpak, but worked without issue when installed from the official Fedora repo. 

I'm pretty new to trying to help debug a program, so if you point me to the right direction, I can give you more info.

My system:

Arch Linux (Linux 6.7)
Gnome 45.3 (using Wayland)
nvidia GPU with prop. drivers

2nd system:

Fedora 39 (Linux 6.6.9)
Gnome 45.3
Intel HD 630 (integrated)

**Comment by yselkowitz** [comment]
There is no way that should happen when run as a flatpak, because the flatpak is tied to a particular runtime, and the latest runtimes (both from Flathub and Fedora) have the previous appstream 0.16 API.  The only time I've seen this in Fedora is on Rawhide which now has the appstream 1.0 API, and we're now carrying a patch to handle that.  FWIW I'm using the Fedora flatpak build of flatseal without any issues, but the Flathub flatpak should also just work.

**Comment by AtmosphericIgnition** [comment]
In any case, my fix is:

1. Start Flatseal, the GUI won't appear.
2. Open system monitor, search for Flatseal, and terminate the process, and all processes related to it.
3. Open Flatseal again, and everything would work as expected.

**Comment by mabod** [comment]
For me Flatseal works again since a while. I dont know what caused the fix. Could be that it was the sequence @AtmosphericIgnition is describing because I did a similar exercise a while ago. I am closing this issue now, because it is solved for me.
