### ISSUE TITLE
installation on external sd-card: permission denied

### ISSUE THREAD

**Issue by maymage** [tchx84/Flatseal#620]
Hi all, 

I have an extra installation on my sd-card.

Granting to Flatseal the following permissions

* device=all
* filesystem=host
* filesystem=host-os

and adding `/media/sd-card/flatpak:ro` does result in Flatseal not
starting anymore and I have to resort to `rm ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal`.

The path is correct

![grafik](https://github.com/tchx84/Flatseal/assets/36572014/2b4360c5-f7dc-46af-b335-2091cc9dcd29)

and running from terminal results in 

```
flatpak run com.github.tchx84.Flatseal 

(com.github.tchx84.Flatseal:2): Gjs-CRITICAL **: 09:42:22.735: JS ERROR: GLib.FileError: Keine Berechtigung
_parseCustomInstallation@resource:///com/github/tchx84/Flatseal/js/models/applications.js:121:17
_getCustomInstallationsPaths@resource:///com/github/tchx84/Flatseal/js/models/applications.js:164:37
_getInstallationsPaths@resource:///com/github/tchx84/Flatseal/js/models/applications.js:179:28
_setup@resource:///com/github/tchx84/Flatseal/js/models/applications.js:48:14
_init@resource:///com/github/tchx84/Flatseal/js/models/applications.js:39:14
FlatpakApplicationsModel@resource:///com/github/tchx84/Flatseal/js/models/applications.js:36:4
getDefault@resource:///com/github/tchx84/Flatseal/js/models/applications.js:398:24
_init@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:105:43
FlatpakPermissionsModel@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:97:4
getDefault@resource:///com/github/tchx84/Flatseal/js/models/permissions.js:436:24
_setup@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:85:41
_init@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:75:14
FlatsealWindow@resource:///com/github/tchx84/Flatseal/js/widgets/window.js:72:4
vfunc_activate@resource:///com/github/tchx84/Flatseal/js/application.js:105:28
main@resource:///com/github/tchx84/Flatseal/js/main.js:34:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/app/bin/com.github.tchx84.Flatseal:9:17
```

Not sure, whether I did something wrong but

## Expected Results

* Flatseal let's me manage the otherwise working apps on the extra installation
* Flatseal does not block, if a permission-denied error occurs.

**Comment by tchx84** [comment]
@maymage did you ever get to resolve this? You should follow either the first OR the second suggestion, no need to do both at once or anything else not recommended on the docs. See https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md#enable-custom-installations

Also, double check that you can actually access these directories content, e.g., via terminal.
