### ISSUE TITLE
__NV_PRIME_RENDER_OFFLOAD=org.inkscape.Inkscape not working

### ISSUE THREAD

**Issue by ShonkaiDJ** [tchx84/Flatseal#624]
I have tried a few ways to offload Inkscape to my dedicated GPU. Adding the environmental variable to Flatseal seems to be the most user-friendly way and that is important since my users are no tech savvy. Yet I don't see my app appear as a process running on the NVidia GPU. (nvtop)

When I add the variable, launching the program gives me an error: 'Can't find run'. This article made me realize I may need to reboot my PC: [https://www.reddit.com/r/pop_os/comments/13vp1us/how_do_i_run_flatpak_apps_on_discrete_gpu_by/]

That worked. After the restart Inkscape would launch again. But as said: env. var. set but nothing happening on my GPU. What am I doing wrong? Does flatpak know what to do next?

I'm on Ubuntu 20.04.2 with KDE Plasma installed.

**Comment by rusty-snake** [comment]
1. IDK if this works at all with flatpaks. IDK if this works at all with inkscape.
2. I'm not sure that __NV_PRIME_RENDER_OFFLOAD works that way. I found 3 sources stating 3 different things.
3. Try to give it `devices=all` permission.

**Comment by flexagoon** [comment]
Try setting two environment variables like this:

`__NV_PRIME_RENDER_OFFLOAD=1`
`__GLX_VENDOR_LIBRARY_NAME=nvidia`

**Comment by tchx84** [comment]
Thanks @rusty-snake @flexagoon for jumping in, I hope these helped. I believe this issue is a bit too specific for Flatseal, maybe there's a more suitable place to get that kind of assistance.
