### ISSUE TITLE
[RFE] Could there be an option to change the command line (Exec=)?

### ISSUE THREAD

**Issue by genodeftest** [tchx84/Flatseal#626]
Would it be possible to override the `Exec=` line through flatseal?

Background: For some flatpak applications, it would be nice to override command line options. For example for Signal, I'd like to add some command line options (see [details](https://github.com/signalapp/Signal-Desktop/issues/3411#issuecomment-1763576244)). Would this be possible with Flatseal?

**Comment by rusty-snake** [comment]
No, there is currently no way to change the Exec line of the generated .desktop files with overrides. 

If https://github.com/flatpak/flatpak/issues/2913#issuecomment-731864389 gets implemented flatseal will support it.

**Comment by genodeftest** [comment]
Thanks :)
