### ISSUE TITLE
Icewm drag on title bar makes pc unresponsive

### ISSUE THREAD

**Issue by MANICX100** [tchx84/Flatseal#630]
Very weird behavior tested on Icewm 3.4.1 and Icewm 3.4.5 on Ubuntu 23.10.

Other apps work fine but with flatseal if I drag (not click) between Show Details and Reset my cursor changes and I can no longer interact with anything on my desktop.

Note: everything is still working and I can move the mouse/ clock is counting up.

I have a attached a video. Luckily I could switch tty and kill the window manager.

The gray background on the list appears on right clicking.

I thought it might be a GNOME/x11 thing but gnome-software center works fine.

https://github.com/tchx84/Flatseal/assets/5303241/b9273a07-4fed-42e2-96b0-1145dd9b0de2

**Comment by tchx84** [comment]
@MANICX100 when you say "Other apps work fine", does that include other GTK4 applications? e.g. [Decibels](https://flathub.org/apps/com.vixalien.decibels).

**Comment by MANICX100** [comment]
> @MANICX100 when you say "Other apps work fine", does that include other GTK4 applications? e.g. [Decibels](https://flathub.org/apps/com.vixalien.decibels).

Interesting, no it does not.

Must be a GTK4 thing, so not a Flatseal issue closed report.

Any idea how to fix this though?
