### ISSUE TITLE
[Feature Request] Show correponding command line for each change

### ISSUE THREAD

**Issue by albertoridolfi** [tchx84/Flatseal#636]
While Flatseal is a very useful tool for a single workstation, when managing multiple workstations, it can be a pain to use it to manage apps in multiple workstations, due to having to remeber each change made in each app.

My idea is this: in the bottom of the permissions list of a select app, add a read-only text box containing the flatpak command line arguments that could be invoked on another machine for the same app. This would simplify keeping multiple machines configuration consistent.

This will allows scripting the changes for those who have no time to go deep into Flatpak docs (otherwise they wouldn´t be using Flatseal in1st place)

This would make provisioning new desktops workstations much, much faster, and less error prone.

I'm sketching an example and attaching it here.
![sketch](https://github.com/tchx84/Flatseal/assets/6587294/4440dad4-7193-4fe5-9e9f-140bd252353f)

**Comment by albertoridolfi** [comment]
Or this also could be hidden behind a "Show Advanced" button or put in a menu "Show advanced" to enable this, so new users wouldn´t get confused.

**Comment by albertoridolfi** [comment]
To make it more clear: every single change via the GUI should be added to the CLI text box below

**Comment by tchx84** [comment]
hey @albertoridolfi ,

I understand the scenario you describe but, Flatseal is not really meant for "managing multiple workstations".

If you're managing multiple machines, you should probably use something more suited like https://gitlab.gnome.org/Cogitri/flatsync and help them implement this feature https://gitlab.gnome.org/Cogitri/flatsync/-/issues/16
