### ISSUE TITLE
Doesn't see alternative installations

### ISSUE THREAD

**Issue by TiZ-HugLife** [tchx84/Flatseal#64]
Hi there, I have all of my flatpak applications installed in an alternative installation in `/xusr/flatpak`, where `/xusr` is a separate subvolume. I have granted Flatseal read permissions to `/xusr/flatpak/app` but it doesn't see any of the apps there.

**Comment by tchx84** [comment]
Alternative installation paths are currently not supported, but ill look into it.

**Comment by tchx84** [comment]
I opened a PR, hope you can help me test it :) Let me know if you need guidance on how to do that

**Comment by TiZ-HugLife** [comment]
Hiya, I do indeed need guidance on how to do that since I've got this installed as a Flatpak right now. Since you have done the work to make it, I definitely want to test it for you.

**Comment by tchx84** [comment]
> Hiya, I do indeed need guidance on how to do that since I've got this installed as a Flatpak right now. Since you have done the work to make it, I definitely want to test it for you.

Alright, step by step:

1. From the terminal:
```
$ flatpak uninstall com.github.tchx84.Flatseal # uninstall the version you have to avoid confusions
$ git clone https://github.com/tchx84/Flatseal.git
$ cd Flatseal
$ git checkout support-custom-installations # to build the right version
$ flatpak-builder --force-clean --repo=repo build com.github.tchx84.Flatseal.json
$ flatpak build-bundle repo flatseal.flatpak com.github.tchx84.Flatseal
$ flatpak --user install flatseal.flatpak
```

2. From Flatseal:
Once you launched Flatseal, modify Flatseal permissions, enable `host` in the filesytems section (or type host:ro below). Restart Flatseal, and you should see your apps.

**Comment by TiZ-HugLife** [comment]
Thanks for walking me through that! The changes work for me, all the applicaitons in my /xusr flatpak are now there. :)

**Comment by tchx84** [comment]
> Thanks for walking me through that! The changes work for me, all the applicaitons in my /xusr flatpak are now there. :)

wow, wasn't expecting it to get right the first time haha, glad to hear. Ill include this in the next release, you can keep using this custom version for yourself meanwhile.
