### ISSUE TITLE
[Feature request] Uninstall-button

### ISSUE THREAD

**Issue by Arxcis** [tchx84/Flatseal#65]
**Description**
I have a humble request for an "Uninstall"-button, right next to the "Reset"-button. I know this might be out of scope of Flatseal, so feel free to shut me down.

![image](https://user-images.githubusercontent.com/3092618/78885562-25073d00-7a5d-11ea-8db1-4d25654a6c40.png)

For me Flatseal has become a natural place for me to go when I want a quick overview of which applications are installed on my computer, and of course what they are allowed to do. Sometimes I see apps I want to get rid of when I am inside Flatseal. Getting rid of an app entirely is the best way to ensure it cannot effect my system anymore, so one could argue this is within scope of Flatseal.

Anyway, not up to me to decide. Take it or leave it. Happy easter! 🐣

**Comment by tchx84** [comment]
Hi Jonas,

I have been tempted myself to do this and other things but, like you mentioned, Flatseal should focus on managing permissions.

Thanks for your feedback!

**Comment by Arxcis** [comment]
> Hi Jonas,
> 
> I have been tempted myself to do this and other things but, like you mentioned, Flatseal should focus on managing permissions.
> 
> Thanks for your feedback!

I totally understand. The line has to be drawn somewhere :+1: Thank you for a quick response
