### ISSUE TITLE
Does this expose all portals

### ISSUE THREAD

**Issue by korpe1** [tchx84/Flatseal#653]
XDG portals are used also outside Flatpaks, does this expose them? What API this use?

**Comment by rusty-snake** [comment]
Yes, `org.free desktop.portals.*` is allowed unconditionally.

**Comment by tchx84** [comment]
Thanks @rusty-snake for answering. 

To expand, assuming that by "this" you refer to Flatseal, the answer is no, it does not expose all portals data, only the ones listed under the "Portals" section of the UI.
