### ISSUE TITLE
Flatseal does not run on Ubuntu 22.04

### ISSUE THREAD

**Issue by dnet890** [tchx84/Flatseal#655]
Hi
I tried to run flatseal on Ubuntu 22.04. But, I got this error message
flatpak run com.github.tchx84.Flatseal

(process:365422): flatpak-WARNING **: 11:06:36.877: Error writing credentials to socket: Error sending message: Broken pipe

<img width="925" alt="image" src="https://github.com/tchx84/Flatseal/assets/29157187/b4767fda-d891-48aa-8c80-5c923351cf38">

**Comment by tchx84** [comment]
hey @dtantono , can you build / install master and try?

```
flatpak kill com.github.tchx84.Flatseal

git clone https://github.com/tchx84/Flatseal.git
cd Flatseal
flatpak --user install org.gnome.{Platform,Sdk}//45
flatpak-builder --user --force-clean --install build com.github.tchx84.Flatseal.json
flatpak --user run --branch=master com.github.tchx84.Flatseal
```

**Comment by dnet890** [comment]
will this package replace the flathub package and stop getting update from flathub?

**Comment by tchx84** [comment]
> will this package replace the flathub package and stop getting update from flathub?

no, it's a different branch, and you can always uninstall it.

**Comment by dnet890** [comment]
Thanks and here is the new error
<img width="563" alt="image" src="https://github.com/tchx84/Flatseal/assets/29157187/b3402965-79b7-423b-a4eb-72d808a98cca">

**Comment by tchx84** [comment]
Hmm, try with `flatpak --user install flathub org.gnome.{Platform,Sdk}//45`

**Comment by dnet890** [comment]
Hi
it shows nothing
<img width="620" alt="image" src="https://github.com/tchx84/Flatseal/assets/29157187/60f718bb-436a-4fc6-aa44-62fd87a54179">

**Comment by SolidStateDj** [comment]
I am having this exact same issue on Arch. 

Both the AUR and Flatpak package do not run, both either giving no error or the same error as originally reported. 

Building manually still results in below or no output.
```
** (process:43327): WARNING **: 01:58:48.433: Error writing credentials to socket: Error sending message: Broken pipe
```

Purging cache and reinstalling also does not work, changing sockets does nothing.

The only app that is broken (from my testing) is Flatseal. Discord, Bottles, Prism-Launcher, Flatsweep, Builder, and OBS-Studio all work.

**Comment by tchx84** [comment]
hey @dtantono ,  I tried to reproduce this today but could not.

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
```

![Screenshot from 2024-02-04 23-36-05](https://github.com/tchx84/Flatseal/assets/481418/21a2066e-af08-47f0-b305-236eeeda14bc)

Unless I can reproduce it, I honestly can't help much... but I suggest you try resetting everything that has to do with Flatseal in the following way (from the terminal):

```
# Make sure no instance of Flatseal is running
flatpak  kill com.github.tchx84.Flatseal
pkill -f "com.github.tchx84.Flatseal"

# Reset all user data related to Flatseal
rm -rf ~/.var/app/com.github.tchx84.Flatseal/
rm ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal
rm ~/.local/share/flatpak/overrides/global

# Build Flatseal from master branch
git clone https://github.com/tchx84/Flatseal.git
cd Flatseal
flatpak --user install org.gnome.{Platform,Sdk}//45
flatpak-builder --user --force-clean --install build com.github.tchx84.Flatseal.json

# Run it
flatpak --user run --branch=master com.github.tchx84.Flatseal
```

@SolidStateDj maybe you can try this too..

**Comment by dnet890** [comment]
I tried that solution provided. the command line does not worked
<img width="653" alt="2024-02-05_13-16_1" src="https://github.com/tchx84/Flatseal/assets/29157187/ac89e1a3-9dd5-4c94-8882-e55e6616c045">
<img width="735" alt="2024-02-05_13-16" src="https://github.com/tchx84/Flatseal/assets/29157187/7e63b700-2b4b-433d-bc9d-a5d9d0053c65">

**Comment by tchx84** [comment]
> I tried that solution provided. the command line does not worked <img alt="2024-02-05_13-16_1" width="653" src="https://private-user-images.githubusercontent.com/29157187/302174181-ac89e1a3-9dd5-4c94-8882-e55e6616c045.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMDcyOTAsIm5iZiI6MTcwNzEwNjk5MCwicGF0aCI6Ii8yOTE1NzE4Ny8zMDIxNzQxODEtYWM4OWUxYTMtOWRkNS00Yzk0LTg4ODItZTU1ZTY2MTZjMDQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA0MjMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3YWQ4ZTc4YjE0MjFiMTIzNWExNzUxNmFhN2FkNGNkZWZiODllMDhiYmU3MjQzM2IwMmY0NDEzODM1YWEzNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p-myrDUi4_fn8mAetiAMrxbctYefn1HRi6zqx5XlQUA"> <img alt="2024-02-05_13-16" width="735" src="https://private-user-images.githubusercontent.com/29157187/302174193-7e63b700-2b4b-433d-bc9d-a5d9d0053c65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMDcyOTAsIm5iZiI6MTcwNzEwNjk5MCwicGF0aCI6Ii8yOTE1NzE4Ny8zMDIxNzQxOTMtN2U2M2I3MDAtMmI0Yi00MzNkLWJjOWQtYTVkOWQwMDUzYzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA0MjMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYjExY2E1Y2ViN2ZmZDlhMjc3Y2VlMzYyYjZjOTZkMjg3OTgyZTRkNGYyZDkzNzYyMmM5YjM5NTZhNDU3ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mOIu_t-QxgGT9BQO6wWGCBNDVTJ3KrxhRcF6UpnynI4">

Try without the `$`s

**Comment by dnet890** [comment]
I removed the dollar sign and I have same result
<img width="846" alt="2024-02-05_13-26_1" src="https://github.com/tchx84/Flatseal/assets/29157187/1fcd9838-c1a9-4d06-85e5-c5c118ed8c1a">
<img width="886" alt="2024-02-05_13-26" src="https://github.com/tchx84/Flatseal/assets/29157187/e874904e-2f99-48e0-a6e3-189c8d5da699">

**Comment by tchx84** [comment]
@SolidStateDj it seems you don't have flathub set up under the user installation, so do this:

```bash
flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
```

And **then** run all those previous commands.

**Comment by SolidStateDj** [comment]
> @SolidStateDj it seems you don't have flathub set up under the user installation, so do this:
> 
> ```shell
> flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
> ```
> 
> And **then** run all those previous commands.

I cannot verify whether or not this fixed it, as it _appeared_ to begin working again after installing KDE-plasma6 a few days ago, running the X11 session, and then rebooting. I have since uninstalled plasma, but Flatseal remains working (for now). 

Sorry I couldn't be of more help, but thanks for helping me.

**Comment by tchx84** [comment]
It's OK! good to hear it's working now.

**Comment by dnet890** [comment]
@tchx84 How come it is closed? because that commandline does not worked?

# Make sure no instance of Flatseal is running
flatpak  kill com.github.tchx84.Flatseal
pkill -f "com.github.tchx84.Flatseal"

# Reset all user data related to Flatseal
rm -rf ~/.var/app/com.github.tchx84.Flatseal/
rm ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal
rm ~/.local/share/flatpak/overrides/global

# Build Flatseal from master branch
git clone https://github.com/tchx84/Flatseal.git
cd Flatseal
flatpak --user install org.gnome.{Platform,Sdk}//45
flatpak-builder --user --force-clean --install build com.github.tchx84.Flatseal.json

# Run it
flatpak --user run --branch=master com.github.tchx84.Flatseal

**Comment by tchx84** [comment]
@dtantono considering that tried to mimic your setup and still couldn't reproduce this,  unless you can provide a way for me to reproduce this, I can't really help..

**Comment by tchx84** [comment]
@dtantono from the screenshots you're showing you need to install Flathub first...

```bash
flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
```

**Comment by dnet890** [comment]
So, My steps are:

sudo apt install flatpak-builder
flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
# Make sure no instance of Flatseal is running
flatpak  kill com.github.tchx84.Flatseal
pkill -f "com.github.tchx84.Flatseal"

# Reset all user data related to Flatseal
rm -rf ~/.var/app/com.github.tchx84.Flatseal/
rm ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal
rm ~/.local/share/flatpak/overrides/global

# Build Flatseal from master branch
git clone https://github.com/tchx84/Flatseal.git
cd Flatseal
flatpak --user install org.gnome.{Platform,Sdk}//45
flatpak-builder --user --force-clean --install build com.github.tchx84.Flatseal.json

# Run it
flatpak --user run --branch=master com.github.tchx84.Flatseal

That works. But, it is quite annoying if we need to run those set of command for long term to get the flatseal to work. Can you create the FAQ on the readme for troubleshooting purpose? So, the noobs who want to use the app can use it easily.

**Comment by tchx84** [comment]
> That works. But, it is quite annoying if we need to run those set of command for long term to get the flatseal to work. Can you create the FAQ on the readme for troubleshooting purpose? So, the noobs who want to use the app can use it easily.

To be clear, these steps are quite unique to your scenario. Other users don't need to do these steps.

From this I conclude that the next release does fix some ubuntu-specific cases, so the chances that people would need this sort of nuclear-reset are less likely now.

Glad it help.
