### ISSUE TITLE
How to allow access to all subfolders?

### ISSUE THREAD

**Issue by Francewhoa** [tchx84/Flatseal#656]
#### User Story 

As a user of Flatseal, I need to allow access to all subfolders and their files. So that a trusted Flatpak application can read, write, create folders and files within any of those.

For example, at `/media/<VOLUME NAME>/<PATH TO EXTERNAL VOLUME>/<SUBFOLDERS START HERE>/*`

#### Steps to reproduce

1. Install a Flatpak application which is able to read, write, and create data to an external folder. For example, Betterbird at https://flathub.org/apps/eu.betterbird.Betterbird

   By external, I mean an external volume. For example, a storage mounted at `/media/<VOLUME NAME>/<PATH TO EXTERNAL VOLUME>/<SUBFOLDERS START HERE>/*`

1. Configure this Flatpak application to store its data to an external folder

1. Start the application. The application needs to create large amount of folder subfolders. Each with large amount of files. Many of those are random names.

1. The application tries to create those folders and files but this fails. This is the challenge.

#### What I tried that did not work

* Add a `/*` suffix to the folder. But Flatseal does not seem to presently support this

* Searched but found no answer at:

  * https://docs.flatpak.org/en/latest/index.html
  * https://docs.flatpak.org/en/latest/sandbox-permissions.html
  * https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html
 
* `--filesystem=host` does not meet my need. As it would be a significant security risk.

* Adding all possible paths to "Filesystem" ---> "Other folders". This is not realistic, because the Flatpak application needs to create large amount of subfolders and files. Including many subfolders with large amount of files. Many of those are random names. Many devices have more than 1 TB of data with hundred of thousand of subfolders and files.

#### New feature request?

If somehow Flatseal is not presently able to allow acces to subfolders and their files, if needed, I could create a new ticket. I suggest this new feature. Simply allow the prefix `/*` at the end of "Other folders". 

#### Example 1

`/media/<VOLUME NAME>/<PATH TO EXTERNAL VOLUME>/<SUBFOLDERS START HERE>/*`

The above example 1 would allow access to all subfolders and subfiles. Such as, but not limited to:

* `/media/<VOLUME NAME>/<PATH TO EXTERNAL VOLUME>/<SUBFOLDERS START HERE>/<SUBFOLDER 1>`

* `/media/<VOLUME NAME>/<PATH TO EXTERNAL VOLUME>/<SUBFOLDERS START HERE>/<SUBFOLDER 1>/<SUB-SUBFOLDER 1>`

* `/media/<VOLUME NAME>/<PATH TO EXTERNAL VOLUME>/<SUBFOLDERS START HERE>/<SUBFOLDER 1>/<SUB-SUBFOLDER 1>/<SUB-SUBFOLDER 1>`

#### Example 2

In this second example, by adding this prefix `:create`, the application would be allowed to read, write, and create folders and files into any of those subfolders at:

* `/media/<VOLUME NAME>/<PATH TO EXTERNAL VOLUME>/<SUBFOLDERS START HERE>/*:create`

Any volunteer for a patch? Both me and the Ubertus.Org team would be happy, as volunteer, to contribute testing and documentation, if needed.

**Comment by rusty-snake** [comment]
Why not just allow `/media/<VOLUME NAME>/<PATH TO EXTERNAL VOLUME>/<SUBFOLDERS START HERE>/`?

**Comment by Francewhoa** [comment]
Thanks @rusty-snake :) This works

It was my mistake. My Flatseal was not configured appropriately. The Flatpak application needed access to 3 different arbitrary paths:
1. `/media/<VOLUME 1 NAME>/<PATH TO EXTERNAL VOLUME>/<SUBFOLDERS START HERE>/`
2. `/media/<VOLUME 2 NAME>/<PATH TO EXTERNAL VOLUME>/<SUBFOLDERS START HERE>/`
3. `/media/<VOLUME 3 NAME>/<PATH TO EXTERNAL VOLUME>/<SUBFOLDERS START HERE>/`

Not just the first path above. Otherwise, somehow, my Flatpak application can't access any of those 3 path. After I added the appropriate "Other folders" permissions for those 3 paths, it worked. This is great :) And now I understand that each arbitrary path include its subfolders and files if any. Awesome sauce :)

I'm closing this ticket now

I'll try to contribute a patch. About adapting this doc at https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html So that it is clearer to newcomers, like me, that Flatseal "Other folders" feature, includes all its subfolders and files if any.
