### ISSUE TITLE
Backup Flatpak settings

### ISSUE THREAD

**Issue by Jopp-gh** [tchx84/Flatseal#661]
The most tedious, time-consuming task when you set up a new system or when you've to roll back to a previous snapshots is, you need to review / update a ton of application preferences.

Would be so awesome and useful if Flatseal could backup and restore all flatpak app preferences - and I do not mean Flatseal's preferences, but individual Flatpak settings.

**Comment by tchx84** [comment]
I highly recommend you check FlatSync https://gitlab.gnome.org/Cogitri/flatsync , and keep an eye on https://gitlab.gnome.org/Cogitri/flatsync/-/issues/16
