### ISSUE TITLE
Help passing options

### ISSUE THREAD

**Issue by rgeditz** [tchx84/Flatseal#663]
Currently I need to start my app like this from the command line:

`flatpak run com.vscodium.codium --disable-features=WaylandFractionalScaleV1`

Or else the UI looks blurry. 

Can I add this flag to flatseal? I tried adding `DISABLE_FEATURES=WAYLAND_FRACTIONAL_SCALING_V1` in the `Environment` -> `Variables` section but to no avail.

**Comment by rusty-snake** [comment]
See #626

**Comment by rusty-snake** [comment]
And check if your flatpak has speciall support for options/flags. The brave flatpak for example reads flags from `~/.var/app/com.brave.Browser/config/brave-flags.conf`.

**Comment by rgeditz** [comment]
Thanks for the information, I guess this means it's not easily possible
