### ISSUE TITLE
filesystems=other error

### ISSUE THREAD

**Issue by Amandaville** [tchx84/Flatseal#67]
I keep all of my data on a usb external drive mounted at /mnt/data-drive.  Most Flatpak applications can only access my /home directory due to permissions, but is useless to me since I do not keep any data there.  I was hoping to use Flatseal to allow Bookworm eBook reader to be able to access my ebooks located at /mnt/data-drive/ebooks.  When trying to select that directory in Flatseal | Filesystems | Other files |, I get an error, "This is not a valid option".  In fact, I cannot select any directory under Other Files.

![Screenshot_2020-05-03_08-10-05](https://user-images.githubusercontent.com/37563017/80896191-23582e80-8d16-11ea-86ee-14f598e3fd1f.png)

I did get Bookworm to work by selecting the All System Files (filesystems=host) option, but I was hoping to limit access to only certain directories for better security.

**Comment by tchx84** [comment]
Hi @Amandaville , all you need to do is pasting the path to that text entry.

![image](https://user-images.githubusercontent.com/481418/80897454-c1bca380-8cc6-11ea-98e7-7f9dd67d7562.png)

Give it a try, and let me know!

**Comment by tchx84** [comment]
Just re-open this issue if that didn't help.
