### ISSUE TITLE
[Feature Request] Group applications by permissions

### ISSUE THREAD

**Issue by nicolae-stroncea** [tchx84/Flatseal#68]
I sometimes want to view all of the applications which have a specific permission in order to see if there are any applications which have permissions that they shouldn't. This is especially relevant for permissions with big security implications like access to all devices, and access to all system files. Currently, the workflow of doing that requires that I go through every single app. 

It would be very useful to have some sort of toggle (Applications|Permissions), where if I click Permissions, the sidebar turns into a list of all Flatpak permissions instead of a list of apps. I can now click on each permission and see all of the applications which have it.

Thank you for considering it

**Comment by tchx84** [comment]
Hello @nicolae-stroncea ,

Thanks for the feedback.

Even though I recognize that this could be useful, I am not sure the benefit would outweigh the cost of having this. Basically, it would require to:

1. have a completely different UI implementation.
2. have a mechanism to index and query app permissions.

Both of which are not minor efforts, and would add complexity to the project.

Maybe there's something else we could consider (aligned to how Flatseal works) that would respond to the need of identifying apps that require certain permissions more easily.
