### ISSUE TITLE
All Flatseal Window's texts / labels disappear on mouse motion

### ISSUE THREAD

**Issue by sophisticatedDreamer** [tchx84/Flatseal#689]
[ Ubuntu-22.04.4 LTS + Mate desktop + X11 window manager]

_Flatseal is a great tool for me, being new to Flatpak permission stuff. It easily solved some  permission glitches I had, due to my ignorance -  thanks for it!_

**ISSUE:**

1. starting Flatseal > _no texts / labels are visible_ . The colorful buttons on the left side are and remain _always_ visible as well as the active or greyed-out _switches_ on the right side.
2. texts / labels _appear_ when the **mouse is moved** ("paints") over the left and/or right side of the window
3. moving the mouse (accidentally) out of it's window > **all** texts / labels **completely disappear on both sides**
4. moving the mouse back in, text, field contents and labels only reappear _where the mouse is moved_ ("paints") - elsewhere everything remains empty / white
5. texts / labels and field contents reappear also, when _scrolling_ the right side of the window _with the mouse button_ only. **A single "step" up or down with the mouse wheel** is sufficient to make **all(!)** texts/labels on the right side visible again. The left side stays empty / white (apart from the colorful buttons)

All implemented functions / settings I tried seem to work, though.

**Screenshot 1:** No texts / labels after launch of Flatseal
![Flatseal-1](https://github.com/tchx84/Flatseal/assets/102172570/03db41c3-e44f-4e61-907e-1261a1700195)

**Screenshot 2:** Labels / texts only appear where the mouse moved (center right to upper-center left, in this case)
![Flatseal-2](https://github.com/tchx84/Flatseal/assets/102172570/02ddd6a1-c21b-4d31-a735-51bcaceee7b2)

**Screenshot 3:** Field contents remains only _always visible_ when the text contents is longer than the visible field _(reproducable!)_
![Flatseal-3](https://github.com/tchx84/Flatseal/assets/102172570/df9096a9-3d50-42ba-a815-ee742c148f52)

**Comment by tchx84** [comment]
@sophisticatedDreamer hey, this looks awful... I will need a bit more context though.

Can you provide the output for the following commands:

* `flatpak --version`
* `flatpak info com.github.tchx84.Flatseal`
* `cat ~/.local/share/flatpak/overrides/global`
* `cat ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal`

Also, can you check other GTK4 + Libadwaita application? e.g. https://flathub.org/apps/re.sonny.Workbench . To see if those issues appear with those too?

EDIT: Plus, can you recall since when this started to happen?

**Comment by sophisticatedDreamer** [comment]
```
% export LANG=en
% flatpak --version
Flatpak 1.14.4
```

```
% flatpak info com.github.tchx84.Flatseal

Martin Abente Lahaye - Manage Flatpak permissions

          ID: com.github.tchx84.Flatseal
         Ref: app/com.github.tchx84.Flatseal/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2.1.2
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 1.6?MB
     Runtime: org.gnome.Platform/x86_64/46
         Sdk: org.gnome.Sdk/x86_64/46

      Commit: 5906e6f8d7ab4bcad66cac7bfcd76571b8f93034ee65822d1b2fda9e52555286
      Parent: 1300a0e261fb02ac68960e93a563923fa999f2606d64297b76af9ada8af1d588
     Subject: Update to v2.1.2 (535d18d8)
        Date: 2024-03-26 15:34:56 +0000
```

```
% cat ~/.local/share/flatpak/overrides/global
cat: /home/frank/.local/share/flatpak/overrides/global: No such file or directory
```

```
% cat ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal 
[Context]
shared=network
```

I add some environment variables because I noticed rare issues depending  on the GTK or Qt toolkit:
```
GTK_IM_MODULE=ibus
GTK_MODULES=appmenu-gtk-module:gail:atk-bridge:canberra-gtk-module
GTK_OVERLAY_SCROLLING=0
```

```
QT_ACCESSIBILITY=1
QT_QPA_PLATFORMTHEME=gtk3
QT_IM_MODULE=ibus
QT_FONT_DPI=93
QT_SCALE_FACTOR=1
```
**?:** _"can you recall since when this started to happen?"_
**!:** I installed _Flatseal_ today and it happened from the very first start.

I have already several _Flatpaks_ installed which do not show this behaviour, e.g.:
```
org.gimp.GIMP
org.gimp.GIMP.Plugin.GMic
net.ankiweb.Anki
net.mkiol.SpeechNote
net.mkiol.SpeechNote.Addon.nvidia
org.gnome.Platform   # Branch 44 + 45 + 46
```

Hope this helps!

**Comment by tchx84** [comment]
> ```
> % export LANG=en
> % flatpak --version
> Flatpak 1.14.4
> ```
> 
> ```
> % flatpak info com.github.tchx84.Flatseal
> 
> Martin Abente Lahaye - Manage Flatpak permissions
> 
>           ID: com.github.tchx84.Flatseal
>          Ref: app/com.github.tchx84.Flatseal/x86_64/stable
>         Arch: x86_64
>       Branch: stable
>      Version: 2.1.2
>      License: GPL-3.0-or-later
>       Origin: flathub
>   Collection: org.flathub.Stable
> Installation: system
>    Installed: 1.6?MB
>      Runtime: org.gnome.Platform/x86_64/46
>          Sdk: org.gnome.Sdk/x86_64/46
> 
>       Commit: 5906e6f8d7ab4bcad66cac7bfcd76571b8f93034ee65822d1b2fda9e52555286
>       Parent: 1300a0e261fb02ac68960e93a563923fa999f2606d64297b76af9ada8af1d588
>      Subject: Update to v2.1.2 (535d18d8)
>         Date: 2024-03-26 15:34:56 +0000
> ```
> 
> ```
> % cat ~/.local/share/flatpak/overrides/global
> cat: /home/frank/.local/share/flatpak/overrides/global: No such file or directory
> ```
> 
> ```
> % cat ~/.local/share/flatpak/overrides/com.github.tchx84.Flatseal 
> [Context]
> shared=network
> ```
> 
> I add some environment variables because I noticed rare issues depending on the GTK or Qt toolkit:
> 
> ```
> GTK_IM_MODULE=ibus
> GTK_MODULES=appmenu-gtk-module:gail:atk-bridge:canberra-gtk-module
> GTK_OVERLAY_SCROLLING=0
> ```
> 
> ```
> QT_ACCESSIBILITY=1
> QT_QPA_PLATFORMTHEME=gtk3
> QT_IM_MODULE=ibus
> QT_FONT_DPI=93
> QT_SCALE_FACTOR=1
> ```
> 
> **?:** _"can you recall since when this started to happen?"_ **!:** I installed _Flatseal_ today and it happened from the very first start.
> 
> I have already several _Flatpaks_ installed which do not show this behaviour, e.g.:
> 
> ```
> org.gimp.GIMP
> org.gimp.GIMP.Plugin.GMic
> net.ankiweb.Anki
> net.mkiol.SpeechNote
> net.mkiol.SpeechNote.Addon.nvidia
> org.gnome.Platform   # Branch 44 + 45 + 46
> ```
> 
> Hope this helps!

Just for completeness, can you install `re.sonny.Workbench` and run it? (it's an app that uses the same stack as Flatseal).

**Comment by sophisticatedDreamer** [comment]
_"Just for completeness, can you install **re.sonny.Workbench** and run it? (it's an app that uses the same stack as Flatseal)."_

I'll do it in a minute. Meanwhile I captured a screencast clearly demonstrating the behavior:

https://github.com/tchx84/Flatseal/assets/102172570/3b6cdbcb-ab56-4938-bd9b-8f6ea6ef389a

**Comment by sophisticatedDreamer** [comment]
Very strange ... **_re.sonny.Workbench_** shows a similar effect but _sort of_ "inversed" - watch the mouse position when it happens:

https://github.com/tchx84/Flatseal/assets/102172570/2cbcaa29-bebc-4b26-b8e9-c412b85b0042

**ATTENTION:**
When  _**re.sonny.Workbench**_ started I noticed the following _Warning_ in the terminal from which I launched it:
```
(re.sonny.Workbench:5): Gjs-WARNING **: 17:09:10.437: Gio.UnixInputStream has been moved to a separate platform-specific library. Please update your code to use GioUnix.InputStream instead.
```
Well, it's just a _warning_ but it talks about ```Unix Input Stream``` and _mouse motion_ (pointer focus) may have to do with it: The behavior I document is dependent on whether I move the mouse out of the (strange behaving) window to the desktop's background only - where no _input stream_ is active - or to a different application (here: web issue form, terminal window ...) which are listening to _input streams_ .

Just a wild guess ...

**Comment by tchx84** [comment]
> Very strange ... **_re.sonny.Workbench_** shows a similar effect but _sort of_ "inversed" - watch the mouse position when it happens:
> 
>  vokoscreenNG-2024-04-18_16-36-00.mp4 
> **ATTENTION:** When I started I noticed the following //Warning// in the terminal where I launched it:
> 
> ```
> (re.sonny.Workbench:5): Gjs-WARNING **: 17:09:10.437: Gio.UnixInputStream has been moved to a separate platform-specific library. Please update your code to use GioUnix.InputStream instead.
> ```
> 
> Well, it's just a _warning_ but it talks about `Unix Input Stream` and _mouse motion_ (pointer focus) may have to do with it: The behaviour I document is dependend on whether I move the moust out of the (strange behaving) window to the desktop's background only - where no //input stream// is active - or to a different application (web issue form, terminal window ...) which listens to _input streams_ .
> 
> Just a wild guess ...

I suspect that the stream error is unrelated... To me this looks more of a rendering issue. Note that since GNOME runtime 46 the default renderer changed. Can you try the following?

```
GSK_RENDERER=gl flatpak run com.github.tchx84.Flatseal
GSK_RENDERER=gl flatpak run re.sonny.Workbench
```

This will force the old default renderer

**Comment by sophisticatedDreamer** [comment]
**Direct hit! That's it!**

Seems we need to define _one more_ environment variable ... 8-)

**Comment by tchx84** [comment]
> **Direct hit! That's it!**
> 
> Seems we need to define _one more_ environment variable ... 8-)

Perfect, I highly recommend that you check GTK's [issues](https://gitlab.gnome.org/GNOME/gtk/-/issues) in case it hasn't been reported yet, and if it hasn't that you create a new issue there. It will certainly help, given how awful this looks.

**Comment by sophisticatedDreamer** [comment]
Thanks for your fast and helpful investigation -  great support!
