### ISSUE TITLE
[feature request] Run the flatpak apps with a different HOME env variable

### ISSUE THREAD

**Issue by omega3** [tchx84/Flatseal#691]
I found this solution:
`env HOME=/path/to/your/custom/flatpak/home flatpak run your-app`
It creates new /home. 

I request adding option to enable it for all apps installed as flatpak so that when app is installed all config goes to this fake /home.

I don't know it is ok from security point of view but it may be useful for users who want to keep their app configs in separate folder due to specific backup preference. For example, when I revert /home from snapshot I don't want loose my browser bookmarks disappear. That is a good reason to keep things separate.

**Comment by rusty-snake** [comment]
Spoofing the environment for `flatpak run` is not possible for flatseal.

**Comment by tchx84** [comment]
See @rusty-snake reply. Flatseal can't do anything that flatpak-overrides does not support.
