### ISSUE TITLE
Portal data has not been set up yet

### ISSUE THREAD

**Issue by ghost** [tchx84/Flatseal#692]
When I open Flatseal, I can't change the `Microphone`, `Speakers`, `Camera`, and `Location` permissions, they're greyed out with the message `Portal data has not been set up yet`.

Here's my output of `flatpak info -M com.github.tchx84.Flatseal`

```
[Context]
shared=ipc;
sockets=x11;wayland;fallback-x11;
devices=dri;
filesystems=xdg-data/flatpak/overrides:create;/var/lib/flatpak/app:ro;xdg-data/flatpak/app:ro;

[Session Bus Policy]
org.gnome.Software=talk
org.freedesktop.impl.portal.PermissionStore=talk
```

![1](https://github.com/tchx84/Flatseal/assets/167981125/72cfd239-acfd-4bb7-bae7-bf5703f9ff8f)

**Comment by tchx84** [comment]
hi @olafSheeran, 

This is intended behavior...

That message means that the app (e.g. spotify) has not requested that permission (e.g. speakers) to that specific portal yet.

Note that Flatseal won't set a portal permission (e.g. speakers) if the app (e.g. spotify) hasn't requested that permission yet. What flatseal will do is to override/change the permissions that has properly been made in the past.

**Comment by ghost** [comment]
Greetings @tchx84 
Sorry for my inadequate expression. No, this application was Telegram and it was using my microphone and camera, that's why I headed to flatseal just to find out that the controls are greyed out.

**Comment by tchx84** [comment]
> Greetings @tchx84 Sorry for my inadequate expression. No, this application was Telegram and it was using my microphone and camera, that's why I headed to flatseal just to find out that the controls are greyed out.

That's because telegram is not using the portal API, but the static permissions API see [this](https://github.com/flathub/org.telegram.desktop/blob/beta/org.telegram.desktop.yml#L12), hence the grayed out sections.

**Comment by ghost** [comment]
@tchx84 Got it, thanks mate :)
