### ISSUE TITLE
Show more information

### ISSUE THREAD

**Issue by bertob** [tchx84/Flatseal#70]
It could be nice to show a little bit more information about apps in the detail pane, e.g. app version, source/branch, runtime version, and so on.

Here's a quick and dirty mockup:

![image](https://user-images.githubusercontent.com/1908896/81165999-3deb0b80-8f93-11ea-80ec-82c6836ee7a7.png)

On narrow widths/mobile the icon/name could be arranged vertically, like so:

![image](https://user-images.githubusercontent.com/1908896/81166135-81457a00-8f93-11ea-954a-79ca6644070f.png)

**Comment by tchx84** [comment]
Looks good, should we also display the flatpak version being used? I think it would make sense give that some permissions are disabled if not supported.

**Comment by tchx84** [comment]
Also, I was thinking that maybe we can squeeze it a bit more? e.g. the following "layout"

```
 [icon]
 [name]    [other info]
[author]
```

this way it wouldn't too much vertical space and it would give more vertical space for adding more info about the app and the runtime.

That's for the "expanded" version of course.

For the mobile version it would look exactly as the mockup.

**Comment by bertob** [comment]
Sure, feel free to try some different layouts, I just wanted to quickly illustrate the general idea :)
