### ISSUE TITLE
Flatseal cannot see/manage the non-default dir installations

### ISSUE THREAD

**Issue by dib-78h** [tchx84/Flatseal#701]
I've created a secondary location using a flatpak config file (/etc/flatpak/installations.d/extra.conf) with the following content:
```
[Installation "extra"]
Path=/data/-flatpaks/
DisplayName=Extra Installation
StorageType=harddisk
```
I moved all the installations there. But unfortunately flatseal cannot see them (they are working fine). 

![image](https://github.com/tchx84/Flatseal/assets/42845346/45edd742-9f61-48bd-bd27-ab856177b28c)
If I install something to the default system location, then it shows up on flatseal's radar, but the others are not.
Are there any way I can point it to the extra dirs also?

HW info:
██████████████████     ████████   dib@dib-linux-x64 
██████████████████     ████████   ----------------- 
██████████████████     ████████   OS: Manjaro Linux x86_64 
██████████████████     ████████   Host: X570 AORUS ELITE -CF 
████████                                            ████████   Kernel: 6.6.32-1-MANJARO 
████████       ████████      ████████   Uptime: 12 hours, 46 mins 
████████       ████████      ████████   Packages: 2032 (pacman), 29 (flatpak), 3 (snap) 
████████       ████████      ████████   Shell: zsh 5.9 
████████       ████████      ████████   Resolution: 1920x1080 
████████       ████████      ████████   DE: Plasma 6.0.5 
████████       ████████      ████████   WM: kwin 
████████       ████████      ████████   Theme: Breeze Dark [Plasma], Qogir-dark [GTK2/3] 
████████       ████████      ████████   Icons: breeze-dark [Plasma], breeze-dark [GTK2/3] 
████████       ████████      ████████   Terminal: mc 
                               CPU: AMD Ryzen 7 5700X (16) @ 3.400GHz 
                               GPU: AMD ATI Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT 
                               GPU: AMD ATI Radeon R7 360 / R9 360 OEM 
                               Memory: 11749MiB / 32016MiB

**Comment by tchx84** [comment]
Follow what the docs suggest https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md#enable-custom-installations

**Comment by dib-78h** [comment]
Thanks, somehow I've missed this one...
In my defense, it seems that the Flatseal installation must be in the default location.
