### ISSUE TITLE
how to run multiple instnaces of Flatpak apps using Flatseal

### ISSUE THREAD

**Issue by harshakp06** [tchx84/Flatseal#703]
I am trying to use same Flatpak app with different login details and their is to be separated 

Can we do use Flatseal for this ?

If yes, please share the steps to follow

**Comment by rusty-snake** [comment]
No, this is not possible. Flatseal is just a UI for `flatpak override` to change static permissions¹.

What you want sounds like https://github.com/flatpak/flatpak/issues/3913.

¹ there is some limited support for portal permissions.

**Comment by tchx84** [comment]
As @rusty-snake mentioned, it can't.
