### ISSUE TITLE
Blurriness with fractional scaling

### ISSUE THREAD

**Issue by WhyNotHugo** [tchx84/Flatseal#71]
Would it be possible to have Wayland support on Flatseal itself?

Given that it's GTK3+, it should work out of the box (native apps use wayland out-of-the-box).

Currently Flatseal runs via xwayland, which makes it render super blurry when using screen scaling (which is kind of a must on highdpi displays).

**Comment by tchx84** [comment]
Hii @WhyNotHugo, unless there's a bug somewhere, it should be running just fine on wayland natively, see https://github.com/tchx84/Flatseal/blob/master/com.github.tchx84.Flatseal.json#L11

Do you __see__ any difference when running:

```
flatpak run --nosocket=x11 --nosocket=fallback-x11 --socket=wayland com.github.tchx84.Flatseal
```
vs 

```
flatpak run com.github.tchx84.Flatseal
```
?

**Comment by tchx84** [comment]
> Hii @WhyNotHugo, unless there's a bug somewhere, it should be running just fine on wayland natively, see https://github.com/tchx84/Flatseal/blob/master/com.github.tchx84.Flatseal.json#L11
> 
> Do you **see** any difference when running:
> 
> ```
> flatpak run --nosocket=x11 --nosocket=fallback-x11 --socket=wayland com.github.tchx84.Flatseal
> ```
> 
> vs
> 
> ```
> flatpak run com.github.tchx84.Flatseal
> ```
> 
> ?

Just to clarify, I don't see any difference between these two, so I will need your assistance to figure this out.

**Comment by WhyNotHugo** [comment]
Huh. I just did the `xeyes` test, and it does seem to be running under wayland, so the problem is something else.

For some reason, flatseal isn't scaling properly (like "native" gtk3 apps do), but rather scaling "blurrily" (like XWaylands usually do).

I can usually tell xwayland vs wayland apps because the former always render blurred due to fractional scaling -- it's the first time I've come across a native app having this issue. Any hints on what to look for?

**Comment by WhyNotHugo** [comment]
Flatseal:

![2020-05-10T14:24:00,869957772+02:00](https://user-images.githubusercontent.com/730811/81499216-203ae080-92ca-11ea-9d57-dcac9dd08667.png)

D-Feet (native):

![2020-05-10T14:24:05,915169235+02:00](https://user-images.githubusercontent.com/730811/81499208-19ac6900-92ca-11ea-97a3-0463b5e21844.png)

(It's more obvious on the larger texts here)

**Comment by tchx84** [comment]
hmm, quite puzzling.

I am also using scaling in wayland and can't notice any blurriness. Just a hunch, try running it with `--device=dri`?
```
flatpak run --device=dri --nosocket=x11 --nosocket=fallback-x11 --socket=wayland com.github.tchx84.Flatsea
```

**Comment by WhyNotHugo** [comment]
Nope, no difference.

FWIW, I'm using a fractional scaling, maybe your testing was with integer scaling?

**Comment by tchx84** [comment]
> Nope, no difference.
> 
> FWIW, I'm using a fractional scaling, maybe your testing was with integer scaling?

I was using fractional scaling, as well.

At this point I am clueless as why I can't reproduce this. Can you can share more details about your setup, and Ill try to reproduce it, e.g. linux distribution, desktop environment, scaling value, and flatpak version.

**Comment by tchx84** [comment]
Posting my own `xeyes` test now...

Flatseal, running with the cmd I showed above (maximize image to inspect it):

![Screenshot from 2020-05-10 12-37-49](https://user-images.githubusercontent.com/481418/81505152-37be9d00-92bb-11ea-8804-29de324bcbb6.png)
![Screenshot from 2020-05-10 12-38-04](https://user-images.githubusercontent.com/481418/81505156-3db47e00-92bb-11ea-91e8-237815302bac.png)

An example of a blurry app:

![Screenshot from 2020-05-10 12-38-33](https://user-images.githubusercontent.com/481418/81505158-4016d800-92bb-11ea-8804-f37ca77c53e4.png)

EDIT: Take into account the image compression, Flatseal looks even sharper here.

**Comment by WhyNotHugo** [comment]
Hmm, odd.

I'm using flatpak 1.7.2 under swaywm on Arch.

**Comment by WhyNotHugo** [comment]
Scaling is set to 1.5.

**Comment by tchx84** [comment]
> Hmm, odd.
>

Indeed.
 
> I'm using flatpak 1.7.2 under swaywm on Arch.

but, we will figure this out.

**Comment by WhyNotHugo** [comment]
If you have hints on how to help debug this, I'm happy to help.

**Comment by tchx84** [comment]
@WhyNotHugo Thanks.

Can you try to run Flatseal without Flatpak? So we can remove that variable out. I suspect it shouldn't do any difference, but we need somewhere to start.

**Comment by WhyNotHugo** [comment]
So I'm not sure how to run this natively, I tried this:

```console
$ git clone https://github.com/tchx84/Flatseal.git
$ cd Flatseal
$ flatpak install org.gnome.Sdk/x86_64/3.36  #  Note: This step is missing in the README
$ flatpak-builder --force-clean --repo=repo build com.github.tchx84.Flatseal.json
$ flatpak build-bundle repo flatseal.flatpak com.github.tchx84.Flatseal
$ cd build
$ ./files/bin/com.github.tchx84.Flatseal

(com.github.tchx84.Flatseal:3803): Gjs-WARNING **: 19:56:15.375: JS ERROR: ImportError: No JS module 'main' found in search path
@./files/bin/com.github.tchx84.Flatseal:9:1


(com.github.tchx84.Flatseal:3803): Gjs-CRITICAL **: 19:56:15.375: Script ./files/bin/com.github.tchx84.Flatseal threw an exception
```

Also tried:
```console
$ meson
$ cd build
$  ./files/bin/com.github.tchx84.Flatseal

(com.github.tchx84.Flatseal:3803): Gjs-WARNING **: 19:56:15.375: JS ERROR: ImportError: No JS module 'main' found in search path
@./files/bin/com.github.tchx84.Flatseal:9:1


(com.github.tchx84.Flatseal:3803): Gjs-CRITICAL **: 19:56:15.375: Script ./files/bin/com.github.tchx84.Flatseal threw an exception
```

I'm sure I'm missing something that must be obvious to you :sweat_smile:

**Comment by tchx84** [comment]
Try this:

```
$ meson build
$ cd build/
$ meson install
$ com.github.tchx84.Flatseal
```

Make sure to have libhandy 0.0.13 or newer installed, see https://github.com/tchx84/Flatseal/blob/master/com.github.tchx84.Flatseal.json#L45

**Comment by WhyNotHugo** [comment]
```
$ meson install
ninja: Entering directory `.'
ninja: no work to do.
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/usr/bin/python' as the super user
Authenticating as: root
Password:
```

I'm prompted for a root password (spoiler: my root user doesn't have a password).

Does this need to run as root? What's this trying to do exactly?

**Comment by WhyNotHugo** [comment]
Managed it!

There's no blurriness running it natively.
Also confirmed again (just in case!), and flatpak version is still blurry.

**Comment by WhyNotHugo** [comment]
Also built the v1.5.3 tag with the same results (just in case something in `master` was making a difference).

**Comment by WhyNotHugo** [comment]
AFAIK flatpak packages embed dependencies inside the package, rather than using the OS ones, right?

Might the difference between those be the cause?

**Comment by tchx84** [comment]
That's good (and bad :rofl:) news.

The fact that I can't reproduce it tells us that there is something specific to your setup to triggers this issue (or something in mine that avoids it). But let's try to narrow this a bit more.

Let's see if you can reproduce this with a similar app:

```
$ flatpak install flathub com.belmoussaoui.ReadItLater 
$ flatpak run com.belmoussaoui.ReadItLater
```

Does it look blurry for you?

**Comment by WhyNotHugo** [comment]
ReadItLater is also blurry, so it might be something on my flatpak setup. :thinking: 

Any hints on what it might be? Maybe I should open a ticket with flatpak, right?

BTW: I greatly appreciate your patience debugging this :)

**Comment by tchx84** [comment]
> ReadItLater is also blurry, so it might be something on my flatpak setup. 
> 
> Any hints on what it might be? Maybe I should open a ticket with flatpak, right?
> 

Yes, there has to be more people with this issue.

EDIT: re. what might be, I can only image two things, 1) more likely, some missing package that somehow provides the information needed for proper scaling, or 2) less likely, a bug in flatpak itself?

> BTW: I greatly appreciate your patience debugging this :)

No problem, make sure to reference this issue so they can see what we tried so far.
