### ISSUE TITLE
[Feature Request] Show details button

### ISSUE THREAD

**Issue by Johnn3y** [tchx84/Flatseal#72]
It would be great to have a "Show Details" button available when there is GNOME-Software installed calling `gnome-software --details app-id` similar to what GNOME-Shell does. 
![Screenshot 1](https://user-images.githubusercontent.com/37875319/81505772-04e3cb80-92f2-11ea-85ac-35ad1357bdbc.png)
![Screenshot 2](https://user-images.githubusercontent.com/37875319/81505771-044b3500-92f2-11ea-84cc-2a4fcbf5774b.png)

**Comment by tchx84** [comment]
hi @Johnn3y, 

Thanks for the feedback, do you mind explaining why this would beneficial ?

PersonalIty, I struggle to imagine a reason for why this should be exposed to the user in such visible way.

**Comment by tchx84** [comment]
> hi @Johnn3y,
> 
> Thanks for the feedback, do you mind explaining why this would beneficial ?
> 
> PersonalIty, I struggle to imagine a reason for why this should be exposed to the user in such visible way.

Take a look at this https://github.com/tchx84/Flatseal/issues/70 , maybe serves the same purpose ?

**Comment by Johnn3y** [comment]
> Take a look at this #70 , maybe serves the same purpose ?

That and #65.

But in the end, it's not that important.

**Comment by tchx84** [comment]
Well, I am sure it would be useful for the use case you are considering (which is completely valid) but, like I mentioned in #65, I am explicitly trying to prevent Flatseal to become a general "apps manager".

I believe it will better serve it's purpose by focusing on managing permissions only.

But it doesn't mean what I won't consider your suggestion when I start implementing #70 ;)

**Comment by Johnn3y** [comment]
>I am explicitly trying to prevent Flatseal to become a general "apps manager"

I had that in mind, so my suggestion was only adding a single button which redirects to an external application handling "apps manager" stuff like #70, #65 , etc. so Flatseal can focus on permission management.

**Comment by tchx84** [comment]
> > I am explicitly trying to prevent Flatseal to become a general "apps manager"
> 
> I had that in mind, so my suggestion was only adding a single button which redirects to an external application handling "apps manager" stuff like #70, #65 , etc. so Flatseal can focus on permission management.

Understood. I guess my message got lost during all that rambling of mine hah, but I think #70 could be a nice bridge to get something like this implemented. 

It probably won't just go in the header bar since there's already little available space in "mobile" mode.

**Comment by tchx84** [comment]
Hey @bertob , now that we landed the app information widget... any design that comes to your mind to have something like mentioned here?

I think our header bar is out of space now, specially in mobile/compact mode, but maybe there is a clean way to link to gnome-software / whatever other store.

As @Johnn3y mentioned here, this could help to alleviate all those requests about having more "app management options" in Flatseal.

**Comment by bertob** [comment]
Adding a button to the left side of the header bar makes sense to me, perhaps it's just a matter of finding a shorter label? In English "Details" might work, not sure about other languages though...

Alternatively we could consider removing the name from the headerbar altogether since it's now shown at the top of the view anyway.

**Comment by tchx84** [comment]
> Adding a button to the left side of the header bar makes sense to me, perhaps it's just a matter of finding a shorter label? In English "Details" might work, not sure about other languages though...
> 

Yeah, that's the thing, e.g. dutch

![image](https://user-images.githubusercontent.com/481418/82732807-8c134500-9cdd-11ea-896b-09a4eb344fa4.png)

> Alternatively we could consider removing the name from the headerbar altogether since it's now shown at the top of the view anyway.

I thought about this as well, but in mobile/compact it kind of helps to have the name on top since the info widget "disappears" once you scroll down. I think is good to have the name visible to avoid confusion (or need to scroll up just to double check what app you changing).

Maybe there's something we could add to the info widget?

**Comment by tchx84** [comment]
> Maybe there's something we could add to the info widget?

Another option could be to replace the reset text for an icon, and that would make enough room (unaffected by i18n)... my only concern there is that the reset button is such an important feature and we shouldn't obscured it.

**Comment by bertob** [comment]
Another option could be to have two buttons at the top at wider window sizes, and add an action bar at the bottom at narrow sizes (with "Show Details" on the left and "Reset" on the right). As a side benefit the actions would also be more ergonomic to tap on mobile.

**Comment by tchx84** [comment]
> Another option could be to have two buttons at the top at wider window sizes, and add an action bar at the bottom at narrow sizes (with "Show Details" on the left and "Reset" on the right). As a side benefit the actions would also be more ergonomic to tap on mobile.

~~Is there any existing app you would recommend to use as design reference?~~ EDIT: nvm, it's clear now.

**Comment by WhyNotHugo** [comment]
Changes for this look beautiful! Thanks! :1st_place_medal:
