### ISSUE TITLE
Flatseal not opening after the recent Runtime update

### ISSUE THREAD

**Issue by Angxddeep** [tchx84/Flatseal#725]
This happened after the recent update, the application is not opening at all. There is not even a crash in KDE it just doesn't open up I am using KDE plasma 6.1.5, but I think that really doesn't matter/ 
I tried running **flatpak run com.github.tchx84.Flatseal** and got these errors

> MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:763: FINISHME: support YUV colorspace with DRM format modifiers
> MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers
> Gdk-Message: 12:40:16.168: Error 71 (Protocol error) dispatching to Wayland display.

**Comment by Angxddeep** [comment]
@tchx84 Do you think I should file this issue on upstream gnome runtime too? It may be a problem on their end. No other application is currently using org.gnome.Platform 47 so I am not sure that if it's an issue with flatseal only or an issue with org.gnome.Platform

**Comment by rusty-snake** [comment]
Did you modified the permissions of flatseal? Does it have `devices=dri`? I saw broken cpu fallback on Intel systems with recent mesa versions if `/dev/dri` wasn't allowed.

**Comment by Angxddeep** [comment]
Nah, I didn't do that, even I added `flatpak override --user --device=dri com.github.tchx84.Flatseal` just now and still it doesn't work & gives the same error

**Comment by tchx84** [comment]
@Angxddeep you should definitely open a [GTK](https://gitlab.gnome.org/GNOME/gtk/-/issues) issue, with this information... 

There have been some changes in the rendering side of things recently, so Just for curiosity, can run `GSK_RENDERER=gl flatpak run com.github.tchx84.Flatseal` ?

**Comment by Angxddeep** [comment]
> @Angxddeep you should definitely open a [GTK](https://gitlab.gnome.org/GNOME/gtk/-/issues) issue, with this information...
> 
> There have been some changes in the rendering side of things recently, so Just for curiosity, can run `GSK_RENDERER=gl flatpak run com.github.tchx84.Flatseal` ?

Yeah, it opened up with this GSK_RENDERER=gl flatpak run com.github.tchx84.Flatseal
But it's all weird, see the video
https://github.com/user-attachments/assets/fd1a14e1-93d2-4233-992b-93e8e8a40d8e

**Comment by Angxddeep** [comment]
@tchx84 So, I created an issue on the GTK GitLab instance, and they said that I need a runtime with gtk 4.16.2. He said the update will come in some time.

**Comment by tchx84** [comment]
> @tchx84 So, I created an issue on the GTK GitLab instance, and they said that I need a runtime with gtk 4.16.2. He said the update will come in some time.

Glad there's a solution! Hopefully that lands soon.

**Comment by TheOverpassArsonist** [comment]
> > [@Angxddeep](https://github.com/Angxddeep) you should definitely open a [GTK](https://gitlab.gnome.org/GNOME/gtk/-/issues) issue, with this information...
> > There have been some changes in the rendering side of things recently, so Just for curiosity, can run `GSK_RENDERER=gl flatpak run com.github.tchx84.Flatseal` ?
> 
> Yeah, it opened up with this GSK_RENDERER=gl flatpak run com.github.tchx84.Flatseal But it's all weird, see the video https://github.com/user-attachments/assets/fd1a14e1-93d2-4233-992b-93e8e8a40d8e

I know this is closed but for whatever it's worth on an uptodate garuda install I'm having this exact issue currently, and this fix _does_ still solve it. (so I think it's the same issue through and through)
