### ISSUE TITLE
Flatseal delete `persistent` overrides

### ISSUE THREAD

**Issue by WhyNotHugo** [tchx84/Flatseal#73]
Flatseal seems to delete `persistent` overrides (I'm guessing it overwrites things it doesn't support)?

```
$ flatpak override --user --show us.zoom.Zoom
[Context]
sockets=wayland;
shared=!ipc;
filesystems=!home;
persistent=.config;.zoom;
$ com.github.tchx84.Flatseal  # Do something like, turn wayland off and on again, or any other no-op
$ flatpak override --user --show us.zoom.Zoom
[Context]
sockets=wayland
shared=!ipc
filesystems=!home
```

It also seems that `flatpak --override` adds trailing `;` and Flatseal deletes them, making tracking my diffs quite a bit harder.

**Comment by tchx84** [comment]
Brain dump:

1. Yes, it currently does not support mixed usage with flatpak-override. It will only load what's supported and discard what's not.

2. I do have an experiment branch that adds support persistence (see #54), but it showed that Flatseal model needs a huge refactor to deal with others overrides. So, I still need to find the time to work on that. Plus, I have this "inner-fight" of whether Flatseal should be a permissions manager only vs a general "tweaking" tool.

3. The `;` issue would  be easy to fix but, for my own curiosity, what do you mean by "tracking my diffs"?

**Comment by WhyNotHugo** [comment]
> Yes, it currently does not support mixed usage with flatpak-override. It will only load what's supported and discard what's not.

I'm fine with some features not being supported, but trimming away those that aren't does result in losing some data.  
Also keep in mind that _new_ options might be added in future and it might take some time for `Flatseal` to support them.

> The ; issue would be easy to fix but, for my own curiosity, what do you mean by "tracking my diffs"?

I track my dotfiles using git, and I've included the overrides there too. I mostly include the overrides so I can have a history of them in case I ever completely break everything or something.

**Comment by tchx84** [comment]
> I track my dotfiles using git, and I've included the overrides there too. I mostly include the overrides so I can have a history of them in case I ever completely break everything or something.

I see, note that there's is no guarantee that Flatseal will write overrides in the same order as flatpak-override does, so beware of that too.

**Comment by tchx84** [comment]
@WhyNotHugo I am working on that branch so Flatseal would not-mess with the overrides that were added by flatpak-override , in case you want to me help me test it :)

This is very early WIP though, I should probably have something more solid by Sunday.
