### ISSUE TITLE
Support for more flatpak installations

### ISSUE THREAD

**Issue by Twig6943** [tchx84/Flatseal#736]
Ability to change settings of flatpaks that are installed on other drives/installations

**Comment by rusty-snake** [comment]
Did you read [Enable custom installations](https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md#enable-custom-installations)?

**Comment by Twig6943** [comment]
> Did you read [Enable custom installations](https://github.com/tchx84/Flatseal/blob/master/DOCUMENTATION.md#enable-custom-installations)?

that got it working :+1: thanks
