### ISSUE TITLE
Merge `Flatseal` and `Warehouse` features into one application

### ISSUE THREAD

**Issue by ovari** [tchx84/Flatseal#737]
Please merge `Flatseal` and `Warehouse` features into one application.

### Flatseal

https://github.com/tchx84/Flatseal/

https://flathub.org/apps/com.github.tchx84.Flatseal

### Warehouse

https://github.com/flattool/warehouse

https://flathub.org/apps/io.github.flattool.Warehouse

https://www.linuxfordevices.com/tutorials/linux/install-setup-warehouse-flatpak

What do you think?

Thank you

https://github.com/flattool/warehouse/issues/153

**Comment by rusty-snake** [comment]
TBH, merging a JavaScript app with a Python app might be more work then a rewrite.

**Comment by tchx84** [comment]
hey @ovari , both apps solve a different problem. The fact both are really good at solving these problems, has a lot to do with the fact that they're separate apps.
