### ISSUE TITLE
Window decoration does not feel native

### ISSUE THREAD

**Issue by hep-mh** [tchx84/Flatseal#74]
Hey,

I am using KDE Neon 5.18 and when installing Flatseal, the window decoration does not adapt to my theme (in my case simply Breeze). Any chance that we can get this fixed?

**Comment by tchx84** [comment]
Hello @skumblex , thanks for reaching out.

Flatseal design is heavily inspired by the GNOME [Human Interface Guidelines](https://developer.gnome.org/hig/stable/) and style, and, for the time being, I am not planning to actively support other themes.

**Comment by hep-mh** [comment]
Hi, thanks for your answer. To be honest, I do not know how flatpaks are packaged, but shouldn't it be possible to both comply with the guidelines and use the correct theme? For example, the Snap Store app on my system looks like this
![image](https://user-images.githubusercontent.com/47532112/81752721-5935a980-94b2-11ea-8a56-be360f1c612d.png)
and therefore comply with the guidelines and uses the correct Breeze theme. Flatseal on the other hand has this design
![image](https://user-images.githubusercontent.com/47532112/81752856-ae71bb00-94b2-11ea-8913-9ba2274fcbbb.png)
which to me looks like it could not find the correct theme.

I also found these images on the web https://www.ostechnix.com/how-to-easily-configure-flatpak-apps-permissions-with-flatseal/
which imply that Flatseal is able to correctly adapt to the default Ubuntu theme, so this should also be possible with the Breeze theme, shouldn't it?

There is a flatpak called org.gtk.Gtk3theme.Breeze. Maybe this need to be added to the dependencies?

**Comment by tchx84** [comment]
My first guess would be that, that theme, doesn't "know" how to style the libhandy's HdyTitleBar, which is what Flatseal uses as client side decoration.

**Comment by tchx84** [comment]
Maybe this is useful for you https://github.com/flathub/flathub/issues/1384

**Comment by hep-mh** [comment]
Thanks!
Seems like this is indeed some issue with X11. Installing xsettingsd kind of fixes the problem in X11, but the decorations are still slightly off. However, things are looking different when switching to Wayland. In this case, the window decoration seems native (except for the color sheme). Then you only have to install gnome-settings-daemon to get the font right.

**Comment by tchx84** [comment]
Glad it helped!
