### ISSUE TITLE
[Feature request] Add the ability to launch an app through flatseal (might be a duplicate)

### ISSUE THREAD

**Issue by Twig6943** [tchx84/Flatseal#741]
Something like this
![image](https://github.com/user-attachments/assets/6c1e956e-0f13-4f7f-9418-8ee1d9759e65)

**Comment by tchx84** [comment]
Hi @Twig6943 all non-permission-related features are out of scope for Flatseal. If you're interested in the rationale please feel free to explore similar issues opened in the past. TLDR: A line must to be drawn to define the scope of any tool, and Flatseal has drawn its line to only manage permissions.
