### ISSUE TITLE
Add --talk-name=org.freedesktop.Flatpak 

### ISSUE THREAD

**Issue by digitalethics** [tchx84/Flatseal#84]
The [Sandbox Permissions Reference](https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html) mentions: 

`--talk-name=org.freedesktop.secrets | Talk to a named service on the session bus`

More specifically, I'd like to be able to set permissions for `--talk-name=org.freedesktop.Flatpak` Is this the same permission that is referenced above? Could you add such an option to allow users access to this? 

Linking to [corresponding issue](https://github.com/johnfactotum/foliate/issues/477) in Foliate.

**Comment by tchx84** [comment]
This is on my TODO already, I will find the time to implement this after I get the current release out.

**Comment by digitalethics** [comment]
Fantastic! Thanks a lot for implementing this.

**Comment by tchx84** [comment]
I can always use help with testing ;) give it a try!
