### ISSUE TITLE
Display permission options more explicitly to conform to Sandbox Permissions Reference

### ISSUE THREAD

**Issue by digitalethics** [tchx84/Flatseal#85]
Currently, permission options are written in _italics_ below the individual items. Could you specify them to match the more specific [Sandbox Permissions Reference](https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html)? For example (one among many others), instead of _**shared=network**_ it should be _**--share=network**_. 

Linking to [original issue](https://github.com/johnfactotum/foliate/issues/477) in Foliate.

**Comment by digitalethics** [comment]
Thanks a lot for getting to this so quickly!

**Comment by tchx84** [comment]
No problem, it was long due :)
