### ISSUE TITLE
hu translation using the GitHub web interface

### ISSUE THREAD

**Issue by ovari** [tchx84/Flatseal#9]
Can we provide a hu translation using the GitHub web interface?

Can you create and advise the files which need to have the translations?

What do you think?

Thank you

**Comment by tchx84** [comment]
I added https://github.com/tchx84/Flatseal/blob/master/po/hu.po feel free to translate it and send a PR ;)

Thanks!

**Comment by ovari** [comment]
L59 msgid "Pemission"

Should it be `Permission`?

**Comment by AsciiWolf** [comment]
@ovari Nice catch! Definitely a typo [here](https://github.com/tchx84/Flatseal/blob/master/src/permissionEntryRow.ui#L29) and [here](https://github.com/tchx84/Flatseal/blob/master/src/permissionSwitchRow.ui#L29).

**Comment by tchx84** [comment]
Yes! :man_facepalming:  Good catch indeed.

EDIT: luckily these aren't user visible really, Ill just get rid of these translatable tag later.

**Comment by ovari** [comment]
Please accept https://github.com/tchx84/Flatseal/pull/23

Should
`msgid "Reset this application permissions"`
be
`msgid "Reset this application’s permissions"`
?
